### ISSUE TITLE
running ingest throws attribute error module 'chromadb' has no attribute 'PersistentClient'

### ISSUE THREAD

**Issue by Gamesh** [imartinez/privateGPT#1007]
```
(privategpt-py3.11) (base) ➜  privateGPT git:(main) ✗ python ingest.py
Traceback (most recent call last):
  File "/Volumes/Projects/privateGPT/ingest.py", line 169, in <module>
    main()
  File "/Volumes/Projects/privateGPT/ingest.py", line 146, in main
    chroma_client = chromadb.PersistentClient(settings=CHROMA_SETTINGS , path=persist_directory)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'chromadb' has no attribute 'PersistentClient'

```

.env file:

```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4
```

**Environment (please complete the following information):**
 - OS / hardware: macOS 13.5.1
 - Python version 3.11.5

any idea what's wrong here or how to solve it?

**Comment by jj09** [comment]
Seems like that issue started occurring since 3f5f82d ([Update dependencies. Upgrade chromadb integration.](https://github.com/imartinez/privateGPT/commit/7b294ed31f71fe3401dc9d544123470bccf61280)). 
Temp workaround: revert back to 3f5f82d

**Comment by LUN000** [comment]
Are you running with poetry?
If so, it's  due to poetry install file not been update. I have a PR #1015 to fix it.

**Comment by Gamesh** [comment]
yes, i was

**Comment by nshi-travelers** [comment]
Any updates on the fix? I was facing the same issue

**Comment by Andross007** [comment]
Yes I was facing the same issue too (but didn't used poetry).

**Comment by vincentteyssier** [comment]
same issue, installing with apt, chromadb==0.3.29

**Comment by pandeyManish1230** [comment]
can i run it on python 3.8??
