### ISSUE TITLE
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

### ISSUE THREAD

**Issue by Comput3rUs3r** [imartinez/privateGPT#1012]
Getting this error when running python ingest.py
(privategpt) D:\privategpt\privateGPT>python ingest.py
Traceback (most recent call last):
  File "D:\privategpt\privateGPT\ingest.py", line 169, in <module>
    main()
  File "D:\privategpt\privateGPT\ingest.py", line 146, in main
    chroma_client = chromadb.PersistentClient(settings=CHROMA_SETTINGS , path=persist_directory)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\__init__.py", line 106, in PersistentClient
    return Client(settings)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\__init__.py", line 143, in Client
    api = system.instance(API)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\config.py", line 243, in instance
    impl = type(self)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 82, in __init__
    self._manager = self.require(SegmentManager)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\config.py", line 184, in require
    inst = self._system.instance(type)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\config.py", line 243, in instance
    impl = type(self)
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\segment\impl\manager\local.py", line 73, in __init__
    // PersistentLocalHnswSegment.get_file_handle_count()
  File "C:\Users\Itanimulli\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\segment\impl\vector\local_persistent_hnsw.py", line 405, in get_file_handle_count
    hnswlib_count = hnswlib.Index.file_handle_count
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

**Comment by JoeLorenzoMontano** [comment]
I am also running into this error.

**Comment by bigcat26** [comment]
+1. same issue

**Comment by Ananderz** [comment]
Same error, however downgrading to 0.4.3 did not fix the issue for me. Trying to figure it out

**Comment by SuperSlamUSA** [comment]
Same problem here. Is planned to solve this? How did you work around this error? Downgrading to 0.4.3 did not fix the issue for me neither.

**Comment by DLOVRIC2** [comment]
I am on Python 3.10.13 and downgrading to 0.4.3 fixed the issue for me.

After downgrading this is what I have:

Name: chromadb
Version: 0.4.3

Name: hnswlib
Version: 0.7.0

Name: chroma-hnswlib
Version: 0.7.1

**Comment by LIdro** [comment]
The problem is caused by poorly commenting the line 

// PersistentLocalHnswSegment.get_file_handle_count()

To solve this, you need to: 
- look for the line in the error stack that shows 
File "C:\Users\phyln\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\segment\impl\manager\local.py", line 73, in __init__
    // PersistentLocalHnswSegment.get_file_handle_count()
- then you shift click on the link (or copy and paste the link in your file explorer). 
- If you followed the link, you will need to open the local.py file in you IDE and edit the line 73 as below.

# PersistentLocalHnswSegment.get_file_handle_count()

That should solve your problem.

**Comment by MosterCheeseInc** [comment]
> The problem is caused by poorly commenting the line
> 
> // PersistentLocalHnswSegment.get_file_handle_count()
> 
> To solve this, you need to:
> 
> * look for the line in the error stack that shows
>   File "C:\Users\phyln\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\segment\impl\manager\local.py", line 73, in **init**
>   // PersistentLocalHnswSegment.get_file_handle_count()
> * then you shift click on the link (or copy and paste the link in your file explorer).
> * If you followed the link, you will need to open the local.py file in you IDE and edit the line 73 as below.
> 
> # PersistentLocalHnswSegment.get_file_handle_count()
> 
> That should solve your problem.

This worked for me fixed the issue I had with completing the >python ingest.py

**Comment by macksjlazarus** [comment]
> The problem is caused by poorly commenting the line
> 
> // PersistentLocalHnswSegment.get_file_handle_count()
> 
> To solve this, you need to:
> 
>     * look for the line in the error stack that shows
>       File "C:\Users\phyln\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\segment\impl\manager\local.py", line 73, in **init**
>       // PersistentLocalHnswSegment.get_file_handle_count()
> 
>     * then you shift click on the link (or copy and paste the link in your file explorer).
> 
>     * If you followed the link, you will need to open the local.py file in you IDE and edit the line 73 as below.
> 
> 
> # PersistentLocalHnswSegment.get_file_handle_count()
> 
> That should solve your problem.

This worked for me!

**Comment by HammadB** [comment]
Hi folks - I don't think this is due to "poorly commenting" the line `// PersistentLocalHnswSegment.get_file_handle_count()` is floor division by the file handle count of the index. 

The problem here is likely that you have both hnswlib and chroma-hnswlib in your env, we need to clean this up but hnswlib shadows chroma-hnswlib. Can you remove hnswlib from your env (using `pip freeze` to confirm) and this _should_ go away.

Sorry for the confusion.

**Comment by BullzeyeBG** [comment]
> Hi folks - I don't think this is due to "poorly commenting" the line. `// PersistentLocalHnswSegment.get_file_handle_count()` is floor division by the file handle count of the index.
> 
> The problem here is likely that you have both hnswlib and chroma-hnswlib in your env, we need to clean this up but hnswlib shadows chroma-hnswlib. Can you remove hnswlib from your env (using `pip freeze` to confirm) and this _should_ go away.
> 
> Sorry for the confusion.

This worked for me - uninstalled "hnswlidb" but kept "chroma-hnswlib".

**Comment by Prathmesh-1991** [comment]
> > Hi folks - I don't think this is due to "poorly commenting" the line. `// PersistentLocalHnswSegment.get_file_handle_count()` is floor division by the file handle count of the index.
> > The problem here is likely that you have both hnswlib and chroma-hnswlib in your env, we need to clean this up but hnswlib shadows chroma-hnswlib. Can you remove hnswlib from your env (using `pip freeze` to confirm) and this _should_ go away.
> > Sorry for the confusion.
> 
> This worked for me - uninstalled "hnswlid" but kept "chroma-hnswlib". Also - guys, do not follow the suggestion above to comment line 73, cause it will deem your chromadb unusable - I spent 3 hours wondering why my similarity search would not work!!!
> 
> Just follow the hnswlib advise!

I have tried uninstalling hnswlib and importing import chroma-hnswlib but it is giving me error
from chromadb.segment.impl.vector.local_hnsw import (
  File "C:\Private GPT\privategpt\lib\site-packages\chromadb\segment\impl\vector\local_hnsw.py", line 27
    import chroma-hnswlib

**Comment by quantuan125** [comment]
Why is this closed? This issue is never solved properly.

**Comment by MichaelJWelsh** [comment]
Still having issues ^^^

**Comment by anilpillai007** [comment]
Still having issues. Tried the above

**Comment by anilpillai007** [comment]
okay I figured it. It is primarily a path problem. 
1. I had multiple "local_persistent_hnsw.py" files, and it was picking from the wrong directory.  That wrong file had a call to  get_file_handle_count()
2. I uninstalled that version of chromadb and it solved the problem. I never used that version anyways. 

E.g. on my mac, I had 
1. /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py
2. /usr/local/lib/python3.11/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py

I ran "pip uninstall chromadb" and it removed the 2nd local_persistent_hnsw.py


One should never go ahead and edit the installed files like someone had commented earlier.

**Comment by Lockearaec** [comment]
Thx to yall for the trouble shoots!

**Comment by Danielskry** [comment]
> okay I figured it. It is primarily a path problem.
> 
>     1. I had multiple "local_persistent_hnsw.py" files, and it was picking from the wrong directory.  That wrong file had a call to  get_file_handle_count()
> 
>     2. I uninstalled that version of chromadb and it solved the problem. I never used that version anyways.
> 
> 
> E.g. on my mac, I had
> 
>     1. /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py
> 
>     2. /usr/local/lib/python3.11/site-packages/chromadb/segment/impl/vector/local_persistent_hnsw.py
> 
> 
> I ran "pip uninstall chromadb" and it removed the 2nd local_persistent_hnsw.py
> 
> One should never go ahead and edit the installed files like someone had commented earlier.

Cheers for this! This was also my problem. In my case I was using Poetry and after having installed both `hnswlib` and `chroma-hnswlib` I got this issue. Removing them from the `pyproject.toml` didn't help, I had to manually delete the current environment and reinstall it.

**Comment by mehedihassanbinhafiz** [comment]
> I am on Python 3.10.13 and downgrading to 0.4.3 fixed the issue for me.
> 
> After downgrading this is what I have:
> 
> Name: chromadb Version: 0.4.3
> 
> Name: hnswlib Version: 0.7.0
> 
> Name: chroma-hnswlib Version: 0.7.1

This solution is working for me. Though I am using python 3.8.10

**Comment by sivahariditty** [comment]
dsf

> For me I uninstall both chroma-hnswlib and hnswlib. And installed again chroma-hnswlib.
> 
> ```
> pip uninstall hnswlib
> pip uninstall chroma-hnswlib
> pip install chroma-hnswlib
> ```

This worked for me as well.
