### ISSUE TITLE
Process breaks while ingesting EML files

### ISSUE THREAD

**Issue by staleks** [imartinez/privateGPT#1018]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**

Preparation completed according to README.md:
1. Python/Pip installed 
2. requirements.txt installed 
3. Model GPT4All downloaded and places in correct folder
4. Placed > 30.000 EML files (Enron email data set) into `source_documents` folder

Started ingestion.py process:
```
$ python3 ingest.py
```

Output is:
```
Loading new documents: 100%|████████████| 32394/32394 [00:09<00:00, 3256.71it/s]
Loaded 32394 new documents from source_documents
Split into 0 chunks of text (max. 500 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "/Users/astoisavljevic/work-home/privateGPT/workspace/privateGPT/ingest.py", line 169, in <module>
    main()
  File "/Users/astoisavljevic/work-home/privateGPT/workspace/privateGPT/ingest.py", line 161, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS, client=chroma_client)
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/chroma.py", line 612, in from_documents
    return cls.from_texts(
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/chroma.py", line 576, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/langchain/vectorstores/chroma.py", line 235, in add_texts
    self._collection.upsert(
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/chromadb/api/models/Collection.py", line 294, in upsert
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/chromadb/api/models/Collection.py", line 346, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
  File "/Users/astoisavljevic/Library/Python/3.9/lib/python/site-packages/chromadb/api/types.py", line 99, in maybe_cast_one_to_many
    if isinstance(target[0], (int, float)):
IndexError: list index out of range
```

Any ideas?

**Expected behavior**

Ingestion of `source_documents` should finish with success.

**Environment (please complete the following information):**
 - OS / hardware: macOS Ventura 13.5.2 / M1
 - Python version - 3.9.6

**Additional context**

**Comment by codespearhead** [comment]
Seems to be the same problem as #1040 . Try [this](https://github.com/imartinez/privateGPT/issues/1040#issuecomment-1732806574).

**Comment by codespearhead** [comment]
@staleks Seems to be the same problem as #1040 . Try [this](https://github.com/imartinez/privateGPT/issues/1040#issuecomment-1732806574).
