### ISSUE TITLE
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by azumukupoe** [imartinez/privateGPT#1022]
**Describe the bug and how to reproduce it**
trying to run `python privateGPT.py` after having setup poetry

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: Ubuntu 22.04.3 LTS on WSL
 - Python version 3.11.4
- Other relevant information

**Additional context**
```
Traceback (most recent call last):
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/azumukupoe/miniconda3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/wsl/LLM/privateGPT/ingest.py", line 169, in <module>
    main()
  File "/mnt/c/wsl/LLM/privateGPT/ingest.py", line 144, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 56, in __init__
    import sentence_transformers
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 189, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/mnt/c/wsl/LLM/privateGPT', '/home/azumukupoe/miniconda3/lib/python311.zip', '/home/azumukupoe/miniconda3/lib/python3.11', '/home/azumukupoe/miniconda3/lib/python3.11/lib-dynload', '/home/azumukupoe/.cache/pypoetry/virtualenvs/privategpt-BVwjtiIy-py3.11/lib/python3.11/site-packages', '/mnt/c/wsl/LLM/privateGPT']
```

**Comment by vareyan** [comment]
Installing CUDA and sentence_transformers(possibly unrelated) fixed it for me: 

sudo apt-get install nvidia-cuda-toolkit nvidia-cuda-toolkit-gcc

pip install sentence_transformers

**Comment by imartinez** [comment]
We've just merged a fix for the problem, which comes from pytorch itself https://stackoverflow.com/questions/76327419/valueerror-libcublas-so-0-9-not-found-in-the-system-path
