### ISSUE TITLE
Slow response times

### ISSUE THREAD

**Issue by hyperp0ppy** [imartinez/privateGPT#1023]
When I ran my privateGPT, I would get very slow responses, going all the way to 184 seconds of response time, when I only asked a simple question. Does this have to do with my laptop being under the minimum requirements to train and use this AI or am I missing something? I've heard that GPT4All is more CPU-intensive, so my initial thought might be that. I also tried changing the number of threads the model uses to slightly higher, but it still stayed the same.

I have these specifications I believe are involved.
 - Python version [e.g. 3.11.3]
 - Processor: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz, 2400 Mhz, 4 Core(s), 8 Logical Processor(s)
 - Total Physical Memory: 11.8 GB
 - Model used: ggml-gpt4all-j-v1.3-groovy.bin & ggml-model-gpt4all-falcon-q4_0.bin

```
PS C:\Users\User\Documents\GitHub\privateGPT>  c:; cd 'c:\Users\User\Documents\GitHub\privateGPT'; & 'C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\User\.vscode\extensions\ms-python.python-2023.16.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '57340' '--' 'C:\Users\User\Documents\GitHub\privateGPT\privateGPT.py'
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: What is NATO?
 NATO stands for North Atlantic Treaty Organization, which is an alliance of 29 countries in Europe that work together to promote security and stability across the continent. The organization was formed after World War II as a response to Soviet aggression during the Cold War. Today, it plays a 
crucial role in maintaining peace and cooperation among its member states through various initiatives such as military exercises, joint operations, 
and partnerships with other international organizations like the United Nations and OSCE (Organization for Security and Cooperation in Europe).

> Question:
What is NATO?

> Answer (took 184.69 s.):
 NATO stands for North Atlantic Treaty Organization, which is an alliance of 29 countries in Europe that work together to promote security and stability across the continent. The organization was formed after World War II as a response to Soviet aggression during the Cold War. Today, it plays a 
crucial role in maintaining peace and cooperation among its member states through various initiatives such as military exercises, joint operations, 
and partnerships with other international organizations like the United Nations and OSCE (Organization for Security and Cooperation in Europe).     

> source_documents\state_of_the_union.txt:
Our forces are not going to Europe to fight in Ukraine, but to defend our NATO Allies – in the event that Putin decides to keep moving west.        

For that purpose we’ve mobilized American ground forces, air squadrons, and ship deployments to protect NATO countries including Poland, Romania, Latvia, Lithuania, and Estonia.

As I have made crystal clear the United States and our Allies will defend every inch of territory of NATO countries with the full force of our collective power.

> source_documents\state_of_the_union.txt:
Our forces are not going to Europe to fight in Ukraine, but to defend our NATO Allies – in the event that Putin decides to keep moving west.        

For that purpose we’ve mobilized American ground forces, air squadrons, and ship deployments to protect NATO countries including Poland, Romania, Latvia, Lithuania, and Estonia.

As I have made crystal clear the United States and our Allies will defend every inch of territory of NATO countries with the full force of our collective power.

> source_documents\state_of_the_union.txt:
The United States is a member along with 29 other nations.

It matters. American diplomacy matters. American resolve matters.

Putin’s latest attack on Ukraine was premeditated and unprovoked.

He rejected repeated efforts at diplomacy.

He thought the West and NATO wouldn’t respond. And he thought he could divide us at home. Putin was wrong. We were ready.  Here is what we did.     

We prepared extensively and carefully.

> source_documents\state_of_the_union.txt:
The United States is a member along with 29 other nations.

It matters. American diplomacy matters. American resolve matters.

Putin’s latest attack on Ukraine was premeditated and unprovoked.

He rejected repeated efforts at diplomacy.

He thought the West and NATO wouldn’t respond. And he thought he could divide us at home. Putin was wrong. We were ready.  Here is what we did.     

We prepared extensively and carefully.

```

**Comment by zhangyong870524** [comment]
having the same slow perf issue.

**Comment by nborwankar** [comment]
I have a very recent 2023 MacBookPro M2 with 96G RAM and 12 CPU Cores, 38 GPU Cores and if I try an Llama model it can take as long as 80s So I don't think it is memory related - possibly ChromaDB is slow when doing the similarity search but I don't know enough about it to be sure

**Comment by hyperp0ppy** [comment]
I would also like to mention that there's another sort of issue that I have, although I'm not sure if it applies to this problem. When I tried running the command:

``python ingest.py``

I would get 

```
PS C:\Users\User\Documents\GitHub\privateGPT> python ingest.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\privateGPT\ingest.py", line 32, in <module>  
    from constants import CHROMA_SETTINGS
  File "C:\Users\User\Documents\GitHub\privateGPT\constants.py", line 3, in <module>
    from chromadb.config import Settings
ModuleNotFoundError: No module named 'chromadb'
PS C:\Users\User\Documents\GitHub\privateGPT> 
```
But if I started debugging with F5 everything runs alright. Did I miss a step or two?

**Comment by MarkusNylund** [comment]
+1
I have also unusable slow response time. Setup is in virtual machine which might affect the response time due to limited resources. 
Tested also with running query 'What is NATO?' and it took around 20 min to generate answer.

**Comment by zaalgol** [comment]
I have the same issue

**Comment by fakabbir** [comment]
Same here, I had about 10k documents that stuck during injection and with the query it takes long enough for not feasible to use with any quick production grade prototyping.

**Comment by bioshazard** [comment]
See https://github.com/imartinez/privateGPT/issues/931 for some tips on altering the repo to use GPU

**Comment by MikeyBeez** [comment]
My guess is that it's slow because it's running in unicorn.  Why does this need to run in a virtual machine?
