### ISSUE TITLE
Problem running the script on MacOs

### ISSUE THREAD

**Issue by YassineElyk** [imartinez/privateGPT#103]
Hello, 
I have followed all the steps correctly I think and I get this error. Any help would be appreciated.

```Loading documents from source_documents
Loaded 3208 documents from source_documents
Split into 39370 chunks of text (max. 500 tokens each)
llama.cpp: loading model from models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 1000
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 519143.73 KB
llama_model_load_internal: mem required  = 2298.98 MB (+ 2052.00 MB per state)
error loading model: llama.cpp: tensor 'norm.weight' is missing from model
llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/embeddings/llamacpp.py", line 78, in validate_environment
    values["client"] = Llama(
                       ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_cpp/llama.py", line 159, in __init__
    assert self.ctx is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/y.e/Desktop/privateGPT/ingest.py", line 62, in <module>
    main()
  File "/Users/y.e/Desktop/privateGPT/ingest.py", line 53, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/embeddings/llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: models/ggml-model-q4_0.bin```

**Comment by isthisausername2** [comment]
Double check that you have created  the 'models' folder in the 'privategpt' folder or you have referenced the exact location in the .env file. If these are correct, the download of the model may be corrupt so you could try re-downloading the models into the correct folder. Let me know how this goes.

**Comment by ClayWalker001** [comment]
that is right, i meet the same error and i re-download them, all good now

**Comment by YassineElyk** [comment]
I re-downloaded and no success.

I ran : `pip3 install -r requirements.txt --upgrade --force-reinstall`

Here's my configuration:

.env file:
```
PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000
```

and models directory inside the repo containing both ggml-gpt4all-j-v1.3-groovy.bin and ggml-model-q4_0.bin

**Comment by PierreVannier** [comment]
@YassineElyk try to put the absolute path toward your model. 
It seems it's a path problem.
```
PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=/Users/y.e/Desktop/privateGPT/models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=/Users/y.e/Desktop/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000
```

**Comment by YassineElyk** [comment]
I used the absolute paths and still the same issue :/

**Comment by PierreVannier** [comment]
> I used the absolute paths and still the same issue :/

Could you try running again the install process but with a virtual env (like conda) ?
```
git clone https://github.com/imartinez/privateGPT.git && cd privateGPT

conda create --name privateGPT && conda activate privateGPT

pip install -r requirements.txt

cd models && wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin 

wget https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

cd .. && python ingest.py
```

**Comment by PierreVannier** [comment]
> It worked thanks!

Great ! Maybe you can close the issue now. Enjoy ;-)
