### ISSUE TITLE
too many tokens

### ISSUE THREAD

**Issue by SilvaRaulEnrique** [imartinez/privateGPT#1044]
.env:
PERSIST_DIRECTORY=db
MODEL_TYPE=LlamaCpp
MODEL_PATH=llama-2-13b-chat.Q8_0.gguf
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=1024
TARGET_SOURCE_CHUNKS=4

In runing python privateGPT.py say's:
llama_tokenize_with_model: too many tokens
...

`Enter a query: hi
llama_tokenize_with_model: too many tokens
Traceback (most recent call last):
  File "/home/raul/Desktop/Librerias/privateGPT/privateGPT.py", line 87, in <module>
    main()
  File "/home/raul/Desktop/Librerias/privateGPT/privateGPT.py", line 58, in main
    res = qa(query)
          ^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 139, in _call
    answer = self.combine_documents_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 480, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 105, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 171, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/llm.py", line 255, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/llm.py", line 91, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/chains/llm.py", line 101, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line 467, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line 602, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line 504, in _generate_helper
    raise e
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line 491, in _generate_helper
    self._generate(
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/base.py", line 981, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/llamacpp.py", line 254, in _call
    for chunk in self._stream(
  File "/home/raul/miniconda3/lib/python3.11/site-packages/langchain/llms/llamacpp.py", line 304, in _stream
    for part in result:
  File "/home/raul/miniconda3/lib/python3.11/site-packages/llama_cpp/llama.py", line 901, in _create_completion
    raise ValueError(
ValueError: Requested tokens (528) exceed context window of 512
`

What is the problem?

**Comment by tlauss** [comment]
Are your requirements up to date?
`pip install -r requirements.txt`

**Comment by rfiacne** [comment]
I encountered the same problem. And I set TARGET_SOURCE_CHUNKS = 2 the problem goes away.

**Comment by SilvaRaulEnrique** [comment]
this work's, thankyou

**Comment by jackfood** [comment]
If each chunk is 500, you take two chunks means 1000, and to produce output requires maybe 300-500, so min is 1500 or more.

**Comment by alxspiker** [comment]
Oh sh.....t, who changed n_ctx to max_tokens, that explains the issues everyone's having in terms of tokens. I spent so many hours researching and perfecting those numbers but I guess it didn't matter. Very misleading ENV file now.
