### ISSUE TITLE
Embedding dimension x does not match collection dimensionality y

### ISSUE THREAD

**Issue by forgetso** [imartinez/privateGPT#1045]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
Trained the model on hundreds of TypeScript files, loaded with the `TextLoader`. Entered a query and it failed.

```
python privateGPT.py
/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/torch/cuda/__init__.py:107: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
models/ggml-gpt4all-j-v1.3-groovy.bin GPT4All
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: What does the cli package do?
Traceback (most recent call last):
  File "/media/user/research/privateGPT/privateGPT.py", line 88, in <module>
    main()
  File "/media/user/research/privateGPT/privateGPT.py", line 59, in main
    res = qa(query)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/chains/base.py", line 282, in __call__
    raise e
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/chains/base.py", line 276, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 136, in _call
    docs = self._get_docs(question, run_manager=_run_manager)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 216, in _get_docs
    return self.retriever.get_relevant_documents(
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/schema/retriever.py", line 208, in get_relevant_documents
    raise e
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/schema/retriever.py", line 201, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 562, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 259, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 332, in similarity_search_with_score
    results = self.__query_collection(
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/utils/utils.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 155, in __query_collection
    return self._collection.query(
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 220, in query
    return self._client._query(
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/chromadb/api/segment.py", line 470, in _query
    self._validate_dimension(coll, len(embedding), update=False)
  File "/home/user/anaconda3/envs/docs/lib/python3.10/site-packages/chromadb/api/segment.py", line 586, in _validate_dimension
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 768
```

**Expected behavior**
Expect to be able to query the embeddings

**Environment (please complete the following information):**
 - OS / hardware: Linux 5.4.0-156-generic 173-Ubuntu
 - Python version 3.10.0
- Other relevant information

**Additional context**
I would like to use codebert for this as mentioned [here](https://github.com/imartinez/privateGPT/issues/122) but I don't know how to set it up to use a different model.

**Comment by lee-jian-hui** [comment]
is this fixed, i encoutered this issue with the latest version of privateGPT

**Comment by NitinNR** [comment]
i am getting the same issue at mhy side is this fix by now ?
