### ISSUE TITLE
Run ingest.py:Failed to establish a new connection: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by CosyMM** [imartinez/privateGPT#1070]
Describe the bug and how to reproduce it
I am using python 3.10.5 and Centos7. I am able to install all the required packages from requirements.txt.Due to the install failed of sentence_transformers,torch-2.1.0-cp310-cp310-manylinux1_x86_64.whl was replaced by torch-2.1.0+cpu-cp310-cp310-linux_x86_64.whl .
While executing the ingest.py file, I failed to establish a new connection.  Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3e9810c0d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))")

Expected behavior
The python ingest.py command should run successfully

Environment (please complete the following information):

OS / hardware: Centos7
Python version: 3.10.5
Other relevant information
.env file has below settings:
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
MODEL_N_BATCH=8
TARGET_SOURCE_CHUNKS=4

Additional context
Error log:
Traceback (most recent call last):
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe9fc570970>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe9fc570970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/Disk/gpt/privateGPT/ingest.py", line 188, in <module>
    main()
  File "/mnt/Disk/gpt/privateGPT/ingest.py", line 158, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 66, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/python3.10.5/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe9fc570970>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 306fbd9f-c8bd-45cc-9b86-670c26e920bf)')

**Comment by alxspiker** [comment]
Might be an OS dependent error when trying to use an HTTPS connection. Make sure all the libraries installed are supported by linux, personally have only developed this on Windows and don't know much about cross platform dependencies. My first thought is it might have to do with torch.

**Comment by JiXia830** [comment]
I am meeting the same problem, have you ever solved it?

**Comment by CosyMM** [comment]
> I am meeting the same problem, have you ever solved it?

Sorry，I have made many attempts, but it seems that none of them are working properly.

**Comment by CosyMM** [comment]
> Might be an OS dependent error when trying to use an HTTPS connection. Make sure all the libraries installed are supported by linux, personally have only developed this on Windows and don't know much about cross platform dependencies. My first thought is it might have to do with torch.

Thanks for your kind help.I made many attempts,but none of them was working， it seems that the problem cannot be attributed to the torch.
