### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by leviathofnoesia** [imartinez/privateGPT#1092]
2023-10-21 08:18:04,561 - INFO - ingest.py:153 - Loaded 1429 documents from C:\Users\billy\localGPT/SOURCE_DOCUMENTS
2023-10-21 08:18:04,561 - INFO - ingest.py:154 - Split into 0 chunks of text
2023-10-21 08:18:06,628 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length 512
Traceback (most recent call last):
File "C:\Users\billy\localGPT\ingest.py", line 181, in
main()
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1157, in call
return self.main(*args, **kwargs)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1078, in main
rv = self.invoke(ctx)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\click\core.py", line 783, in invoke
return __callback(*args, **kwargs)
File "C:\Users\billy\localGPT\ingest.py", line 168, in main
db = Chroma.from_documents(
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 613, in from_documents
return cls.from_texts(
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 577, in from_texts
chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 187, in add_texts
embeddings = self._embedding_function.embed_documents(texts)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\langchain\embeddings\huggingface.py", line 169, in embed_documents
embeddings = self.client.encode(instruction_pairs, **self.encode_kwargs)
File "C:\Users\billy\anaconda3\envs\localGPT\lib\site-packages\InstructorEmbedding\instructor.py", line 524, in encode
if isinstance(sentences[0],list):
IndexError: list index out of range

**Comment by imartinez** [comment]
Looks like you are using an old version of privateGPT (what we call primordial): We are not using langchain to access the vectorstore anymore, and you stack trace points in that direction. 

Please checkout main branch and run a clean install following the docs at https://docs.privategpt.dev/

**Comment by leviathofnoesia** [comment]
I was trying to use the newest version and already followed those directions and they led to this?
