### ISSUE TITLE
chromadb error

### ISSUE THREAD

**Issue by TylerWJ** [imartinez/privateGPT#11]
Hey, I love the idea behind this repo, keep up the good work.

I am getting the following error:

```
Traceback (most recent call last):
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 111, in __query_collection
    return self._collection.query(
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 202, in query
    return self._client._query(
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/chromadb/api/local.py", line 247, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 520, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 223, in get_nearest_neighbors
    raise NoIndexException("Index not found, please create an instance before querying")
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tjones/Projects/privateGPT/privateGPT.py", line 27, in <module>
    main()
  File "/Users/tjones/Projects/privateGPT/privateGPT.py", line 24, in main
    qa.run(query)    
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/chains/base.py", line 238, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/chains/base.py", line 142, in __call__
    raise e
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/chains/base.py", line 136, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 333, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 171, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 217, in similarity_search_with_score
    results = self.__query_collection(
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/utils.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/Users/tjones/Projects/privateGPT/privatechatenv/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 117, in __query_collection
    except chromadb.errors.NotEnoughElementsException:
NameError: name 'chromadb' is not defined. Did you mean: 'Chroma'?
[2023-05-08 15:38:15,087] {duckdb.py:445} INFO - PersistentDuckDB del, about to run persist
[2023-05-08 15:38:15,087] {duckdb.py:388} INFO - Persisting DB to disk, putting it in the save folder: db
```

chromadb is installed in the right directory, I checked the chromadb version, and I also tried importing it into privateGPT.py. I also uninstalled and reinstalled all of the dependencies in requirements.txt, same issue.

**Comment by imartinez** [comment]
Did you follow the ingest process of your document? Was the 'db' directory created during that ingestion?

**Comment by TylerWJ** [comment]
Yes. I have the db directory and two files under it: chroma-collections.parquet and chroma-embeddings.parquet.

**Comment by Rivaltoss** [comment]
Same error here. Trying to solve it at the moment :)

**Comment by TylerWJ** [comment]
It might actually have something to do with code I added. I added a function to preprocess the text and eliminate any special characters:

```
def preprocess_text(text):
    # Remove special characters and multiple spaces
    cleaned_text = re.sub(r"[^a-zA-Z0-9\s]+", " ", text)
    cleaned_text = re.sub(r"\s+", " ", cleaned_text)
    
    return cleaned_text
    
def main():
    # Load document and split in chunks
    loader = TextLoader(argv[1], encoding="utf8")
    documents = loader.load()

    # Pre-process documents
    for doc in documents:
        doc.page_content=preprocess_text(doc.page_content)

    text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    texts = text_splitter.split_documents(documents)
    # Create embeddings
    llama = LlamaCppEmbeddings(model_path="./models/ggml-model-q4_0.bin")
    # Create and store locally vectorstore
    persist_directory = 'db'
    db = Chroma.from_documents(texts, llama, persist_directory=persist_directory)
    db.persist()
    db = None

if __name__ == "__main__":
    main()
```

**Comment by TylerWJ** [comment]
Yeah just realized that the document gets split after the split function lol. So this issue is on my end.

**Comment by TylerWJ** [comment]
@Rivaltoss did you make any code changes?

**Comment by Rivaltoss** [comment]
No.

Anyway, now i found out the DB folder is created and two parquet files are there, however i tried to do the Ingest part again and saw error. So actually my embedding DB is not created properly and there is errror there. That is why obviously the second part doesnt work and i got to the same error as you.

Now i get:
`llama_tokenize: too many tokens`

What is the limit? My txt is very short. Or is that some config settings?

**Comment by TylerWJ** [comment]
One thing: 
Within the DB folder there should be the two files but also an index directory as well. When I was getting the error, there was no index directory.

In terms of the limit, I believe it is 508.

**Comment by imartinez** [comment]
> No.
> 
> Anyway, now i found out the DB folder is created and two parquet files are there, however i tried to do the Ingest part again and saw error. So actually my embedding DB is not created properly and there is errror there. That is why obviously the second part doesnt work and i got to the same error as you.
> 
> Now i get:
> `llama_tokenize: too many tokens`
> 
> What is the limit? My txt is very short. Or is that some config settings?

Fixed in the last commit, by changing the text splitter. Please pull, reinstall dependencies and ingest again.

**Comment by TylerWJ** [comment]
> > No.
> > Anyway, now i found out the DB folder is created and two parquet files are there, however i tried to do the Ingest part again and saw error. So actually my embedding DB is not created properly and there is errror there. That is why obviously the second part doesnt work and i got to the same error as you.
> > Now i get:
> > `llama_tokenize: too many tokens`
> > What is the limit? My txt is very short. Or is that some config settings?
> 
> Fixed in the last commit, by changing the text splitter. Please pull, reinstall dependencies and ingest again.

The ingest script works now; however, when I run `python privateGPT.py` I get the following error:
```
llama_model_load: loading model from './models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
llama_model_load: invalid model file './models/ggml-gpt4all-j-v1.3-groovy.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
llama_init_from_file: failed to load model
zsh: segmentation fault  python privateGPT.py
```
It seems as though we need to update the models.

**Comment by toninog** [comment]
I got the same error - after refreshing the download from the link provided

**Comment by toninog** [comment]
Looks like this is related to Langchain versions... running the 

pip install -r requierments.txt resolved this error - but produced a new one

    llm = GPT4All(model='./models/ggml-gpt4all-j-v1.3-groovy.bin', backend='gptj', callbacks=callbacks, verbose=True)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Could not import pygpt4all python package. Please install it with `pip install pygpt4all`. (type=value_error)
[2023-05-09 12:53:52,792] {duckdb.py:414} INFO - Persisting DB to disk, putting it in the save folder: db

**Comment by AKBuggy** [comment]
Traceback (most recent call last):
  File "C:\Users\ankit\OneDrive\Desktop\AK\GitHub Contributions\privateGPT\privateGPT.py", line 39, in <module>
    main()
  File "C:\Users\ankit\OneDrive\Desktop\AK\GitHub Contributions\privateGPT\privateGPT.py", line 15, in main
    llm = GPT4All(model='./models/ggml-gpt4all-j-v1.3-groovy.bin', backend='gptj', callbacks=callbacks, verbose=False)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Could not import pygpt4all python package. Please install it with `pip install pygpt4all`. (type=value_error)

Anyone have an idea why this is happening?

**Comment by AKBuggy** [comment]
llm = GPT4All(model='./models/ggml-gpt4all-j-v1.3-groovy.bin', backend='gptj', callbacks=callbacks, verbose=False)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Could not import pygpt4all python package. Please install it with `pip install pygpt4all`. (type=value_error)

Anyone have an idea why this is happening?

**Comment by toninog** [comment]
same new error for me as well

**Comment by TtRd-83** [comment]
hello, to fix this error please do the following:

pip install gpt4all

replace at line 32 from privateGPT.py: 
llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)

by

llm = gpt4all.GPT4All(model_name="ggml-gpt4all-j-v1.3-groovy", model_path="models", model_type="gptj")
