### ISSUE TITLE
When trying to reingest in privtegpt

### ISSUE THREAD

**Issue by Musthafamoz** [imartinez/privateGPT#1103]
Creating a new vectorstore
Loading documents from source_documents
Loading new documents: 100%|████████████████████| 48/48 [00:10<00:00,  4.71it/s]
Loaded 994 new documents from source_documents
Split into 11798 chunks of text (max. 166 tokens each)
Creating embeddings. May take some minutes...
Traceback (most recent call last):
  File "C:\Users\mustafa\Desktop\moos\ingest.py", line 172, in <module>
    main()
  File "C:\Users\mustafa\Desktop\moos\ingest.py", line 164, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS, client=chroma_client)
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 612, in from_documents
    return cls.from_texts(
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 576, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 222, in add_texts
    raise e
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\langchain\vectorstores\chroma.py", line 208, in add_texts
    self._collection.upsert(
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\chromadb\api\models\Collection.py", line 298, in upsert
    self._client._upsert(
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\chromadb\api\segment.py", line 290, in _upsert
    self._producer.submit_embeddings(coll["topic"], records_to_submit)
  File "C:\Users\mustafa\Desktop\moos\privateGPT\lib\site-packages\chromadb\db\mixins\embeddings_queue.py", line 127, in submit_embeddings
    raise ValueError(
ValueError:
                Cannot submit more than 166 embeddings at once.
                Please submit your embeddings in batches of size
                166 or less.

**Comment by imartinez** [comment]
This was fixed in https://github.com/imartinez/privateGPT/pull/1087
Please make sure you pull the latest version of main branch and try again.
