### ISSUE TITLE
gym.error.DeprecatedEnv

### ISSUE THREAD

**Issue by AdvanceXplorer** [imartinez/privateGPT#1105]
Hi,

I am using Python 3.10.9 with gym = 0.21.0. When i try to run imitation-master\examples\quickstart.py, I get the following error:

Traceback (most recent call last):
  File "C:\Users\advan\anaconda3\lib\site-packages\gym\envs\registration.py", line 158, in spec
    return self.env_specs[id]
KeyError: 'seals/CartPole-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\advan\OneDrive\Masaüstü\imitation-master\examples\quickstart.py", line 17, in <module>
    env = make_vec_env(
  File "C:\Users\advan\anaconda3\lib\site-packages\imitation\util\util.py", line 107, in make_vec_env
    spec = gym.spec(env_name)
  File "C:\Users\advan\anaconda3\lib\site-packages\gym\envs\registration.py", line 239, in spec
    return registry.spec(id)
  File "C:\Users\advan\anaconda3\lib\site-packages\gym\envs\registration.py", line 185, in spec
    raise error.DeprecatedEnv(
gym.error.DeprecatedEnv: Env seals/CartPole-v0 not found (valid versions include ['CartPole-v0', 'CartPole-v1']),

which is the same as: 
https://imitation.readthedocs.io/_/downloads/en/stable/pdf/).readthedocs.io/_/downloads/en/stable/pdf/.

How can i fix this?

**Comment by lopagela** [comment]
This error is not about this project, proposing a `won't do`
