### ISSUE TITLE
Error while running PGPT_PROFILES=local poetry run python -m private_gpt

### ISSUE THREAD

**Issue by vijayt-mobile1** [imartinez/privateGPT#1147]
I am trying to run the code on CPU. The code is getting executed till chroma DB and it is getting stuck in sqlite3.OperationalError: database is locked.

llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: mem required  = 4165.46 MB
...............................................................................................
llama_new_context_with_model: n_ctx      = 3900
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  =  487.50 MB
llama_new_context_with_model: compute buffer total size = 281.25 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
13:09:11.755 [INFO    ] chromadb.telemetry.product.posthog - Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.

Traceback (most recent call last):
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.vector_store.vector_store_component.VectorStoreComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/genaivijay2/code/users/Vijay.Anand6/private_GPT/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/genaivijay2/code/users/Vijay.Anand6/private_GPT/privateGPT/private_gpt/main.py", line 106, in <module>
    from private_gpt.ui.ui import mount_in_app
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/genaivijay2/code/users/Vijay.Anand6/private_GPT/privateGPT/private_gpt/ui/ui.py", line 19, in <module>
    ingest_service = root_injector.get(IngestService)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/genaivijay2/code/users/Vijay.Anand6/private_GPT/privateGPT/private_gpt/components/vector_store/vector_store_component.py", line 39, in __init__
    chroma_client = chromadb.PersistentClient(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/__init__.py", line 137, in PersistentClient
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/api/client.py", line 49, in _create_system_if_not_exists
    new_system.start()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/config.py", line 308, in start
    component.start()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/impl/sqlite.py", line 99, in start
    self.initialize_migrations()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/migrations.py", line 134, in initialize_migrations
    self.apply_migrations()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/migrations.py", line 155, in apply_migrations
    self.setup_migrations()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/impl/sqlite.py", line 156, in setup_migrations
    with self.tx() as cur:
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/impl/sqlite.py", line 51, in __exit__
    self._conn.commit()
  File "/anaconda/envs/privateGPT/lib/python3.11/site-packages/chromadb/db/impl/sqlite_pool.py", line 31, in commit
    self._conn.commit()
sqlite3.OperationalError: database is locked

**Comment by Jawn78** [comment]
Have you tried deleting the DB and starting over? It sounds like something is hung up, using the database, or a permission issue.  As far as I know, there is no concurrency handling or WAL in PrivateGPT. It could be a missing commit() to release the locks after a transaction to the DB. 

At any rate, Delete the files in privateGPT\local_data\private_gpt and try restarting it. That will remove the chroma_db and replace it when you restart the program.

**Comment by pabloogc** [comment]
Did @Jawn78 fix this issue @vijayt-mobile1 ? if so I'll close it. But I encourage you to forward this to the chromadb team.

**Comment by vijayt-mobile1** [comment]
> Have you tried deleting the DB and starting over? It sounds like something is hung up, using the database, or a permission issue. As far as I know, there is no concurrency handling or WAL in PrivateGPT. It could be a missing commit() to release the locks after a transaction to the DB.
> 
> At any rate, Delete the files in privateGPT\local_data\private_gpt and try restarting it. That will remove the chroma_db and replace it when you restart the program.



> Have you tried deleting the DB and starting over? It sounds like something is hung up, using the database, or a permission issue. As far as I know, there is no concurrency handling or WAL in PrivateGPT. It could be a missing commit() to release the locks after a transaction to the DB.
> 
> At any rate, Delete the files in privateGPT\local_data\private_gpt and try restarting it. That will remove the chroma_db and replace it when you restart the program.

Hi @Jawn78 thank you for the suggestion. I tried the above steps and deleted files present in privateGPT\local_data\private_gpt  and rerun the code twice. I am still getting sqlite3.OperationalError: database is locked.

**Comment by vijayt-mobile1** [comment]
> Did @Jawn78 fix this issue @vijayt-mobile1 ? if so I'll close it. But I encourage you to forward this to the chromadb team.

@pabloogc how to forward this issue to chromadb team. Plz suggest.
