### ISSUE TITLE
ImportError: docx2txt is required to read Microsoft Word files: `pip install docx2txt`

### ISSUE THREAD

**Issue by donnadulcinea** [imartinez/privateGPT#1150]
I'm have no idea why this is happening:

I see that docx are supported:
` ".docx": DocxReader,`

In executed `pip install docx2txt` just to be sure it was a global library, and I also tried to edit the poetry pyproject.toml file adding the dependency with no success.

But I still get the following when trying to upload a docx via gradio UI (I still didn't try bulk document ingestion).

I installed privateGPT in Ubuntu 22 with no GPU if this can be useful for troubleshooting. For the rest it works well.

```
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/llama_index/readers/file/docs_reader.py", line 58, in load_data
    import docx2txt
ModuleNotFoundError: No module named 'docx2txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/dd/ai/privateGPT/private_gpt/ui/ui.py", line 96, in _upload_file
    ingest_service.ingest(file_name=path.name, file_data=path)
  File "/home/dd/ai/privateGPT/private_gpt/server/ingest/ingest_service.py", line 92, in ingest
    documents = reader.load_data(file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/.cache/pypoetry/virtualenvs/private-gpt-ua63sb5q-py3.11/lib/python3.11/site-packages/llama_index/readers/file/docs_reader.py", line 60, in load_data
    raise ImportError(
ImportError: docx2txt is required to read Microsoft Word files: `pip install docx2txt`
06:02:11.249 [INFO    ]             uvicorn.error - connection closed

```

**Comment by maozdemir** [comment]
You night gave it installed for Python 2 if you used pip. Try pip3.

**Comment by donnadulcinea** [comment]
Actually as per the documentation the project seems to be using pyenv. Is it not?
I'm correctly activating the local environment before anything, but still gives the problem.
I also tried both pip, pip3.

```
dd@mvac-ai:~/ai/privateGPT$ pyenv --version
pyenv 2.3.31
dd@mvac-ai:~/ai/privateGPT$ pyenv local 3.11.6
dd@mvac-ai:~/ai/privateGPT$ pip install docx2txt
Requirement already satisfied: docx2txt in /home/dd/.pyenv/versions/3.11.6/lib/python3.11/site-packages (0.8)
dd@mvac-ai:~/ai/privateGPT$ pip3 install docx2txt
Requirement already satisfied: docx2txt in /home/dd/.pyenv/versions/3.11.6/lib/python3.11/site-packages (0.8)
```

**Comment by unalignedcoder** [comment]
same problem here. it complains about missing docx2txt, but when installing the module it says "Requirement already satisfied"

**Comment by maozdemir** [comment]
> Actually as per the documentation the project seems to be using pyenv. Is it not? I'm correctly activating the local environment before anything, but still gives the problem. I also tried both pip, pip3.
> 
> ```
> dd@mvac-ai:~/ai/privateGPT$ pyenv --version
> pyenv 2.3.31
> dd@mvac-ai:~/ai/privateGPT$ pyenv local 3.11.6
> dd@mvac-ai:~/ai/privateGPT$ pip install docx2txt
> Requirement already satisfied: docx2txt in /home/dd/.pyenv/versions/3.11.6/lib/python3.11/site-packages (0.8)
> dd@mvac-ai:~/ai/privateGPT$ pip3 install docx2txt
> Requirement already satisfied: docx2txt in /home/dd/.pyenv/versions/3.11.6/lib/python3.11/site-packages (0.8)
> ```

No idea, I don't support the current state of this project. Use the older and more superior version, there are no such issues there, and it's much simpler to customize, as this new "look" has been overcomplicated.

**Comment by donnadulcinea** [comment]
Ok I succeed to solve, I share it here:

* Check and activate the poetry environment

```
dd@storebook-ai:~/ai/privateGPT$ poetry env list
private-gpt-ua63sb5q-py3.11 (Activated)
```

* Add the requested dependency 
```
dd@storebook-ai:~/ai/privateGPT$ poetry add docx2txt
Using version ^0.8 for docx2txt
Updating dependencies
Resolving dependencies... (4.6s)
Package operations: 1 install, 0 updates, 0 removals
  • Installing docx2txt (0.8)
Writing lock file
```

* Repeat the procedure for other dependencies (e.g., whisper is required for audio and video)
```
dd@storebook-ai:~/ai/privateGPT$ poetry add whisper
Using version ^1.1.10 for whisper
Updating dependencies
Resolving dependencies... (2.9s)
Package operations: 1 install, 0 updates, 0 removals
  • Installing whisper (1.1.10)
Writing lock file
```
