### ISSUE TITLE
Error while running " PGPT_PROFILES=local poetry run python -m private_gpt" command without internet. 

### ISSUE THREAD

**Issue by umarshahid** [imartinez/privateGPT#1151]
**I am getting this error when I try to run the command  " PGPT_PROFILES=local poetry run python -m private_gpt"  offline.**

```
Traceback (most recent call last):
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.pyenv/versions/3.11.6/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc4efaf58d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc4efaf58d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/umar/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/umar/privateGPT/private_gpt/main.py", line 4, in <module>
    import llama_index
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/__init__.py", line 21, in <module>
    from llama_index.indices.common.struct_store.base import SQLDocumentContextBuilder
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.document_summary.base import DocumentSummaryIndex
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/indices/document_summary/__init__.py", line 4, in <module>
    from llama_index.indices.document_summary.base import (
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/indices/document_summary/base.py", line 14, in <module>
    from llama_index.indices.base import BaseIndex
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/condense_question.py", line 6, in <module>
    from llama_index.chat_engine.types import (
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/types.py", line 11, in <module>
    from llama_index.memory import BaseMemory
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/memory/__init__.py", line 1, in <module>
    from llama_index.memory.chat_memory_buffer import ChatMemoryBuffer
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 12, in <module>
    class ChatMemoryBuffer(BaseMemory):
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 18, in ChatMemoryBuffer
    default_factory=cast(Callable[[], Any], GlobalsHelper().tokenizer),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/llama_index/utils.py", line 52, in tokenizer
    enc = tiktoken.get_encoding("gpt2")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 11, in gpt2
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/tiktoken/load.py", line 75, in data_gym_to_mergeable_bpe_ranks
    vocab_bpe_contents = read_file_cached(vocab_bpe_file).decode()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/tiktoken/load.py", line 48, in read_file_cached
    contents = read_file(blobpath)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/tiktoken/load.py", line 24, in read_file
    resp = requests.get(blobpath)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umar/.cache/pypoetry/virtualenvs/private-gpt-VWrw_b68-py3.11/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc4efaf58d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```
I want to setup private_gpt for offline setting where not internet is available.

**Comment by jackfood** [comment]
Yes, Same issue here. It seems it requires internet connection when first started.

**Comment by lopagela** [comment]
Indeed - from my experience, it is downloading the differents models it need on the first run (e.g. embedding model, LLM models, that kind of stuff)

**Comment by jackfood** [comment]
> Indeed - from my experience, it is downloading the differents models it need on the first run (e.g. embedding model, LLM models, that kind of stuff)

Acutally i have downloaded the first run and has the required embedding. I am figuring out which are the files needed for PrivateGPT, but i cannot find all. (e.g. .cache / %appdata%/local).

e.g. Poetry is in 'Local' folder if not wrong.

**Comment by jackfood** [comment]
> @jackfood if you want a "portable setup", if I were you, I would do the following:
> 
> First of all, assert that `python` is installed the same way wherever I want to run my "local setup"; in other words, I'd be assuming some path/bin stability.
> 
> Then, I'd create a venv on that portable thumb drive, install poetry in it, and make poetry install all the deps **inside the venv** (`python3 -m venv venv && source venv/bin/activate && pip install --upgrade pip poetry && poetry install`). With this, it makes all the lib/bin required for this project to be isolated in that `venv` (i.e. on your thumb drive).
> 
> However, depending on the hardware you gave, given that `llama-cpp-python` (installed in your `venv`) is installed by local compilation (i.e. building python wheels), it is very likely that the binary of `llama-cpp-python` will not run on another computer (because again of the lib being present on one computer, and not on the other, especially thinking to the CUDA, libblas and co).
> 
> If the above (`llama-cpp-python`) is indeed causing issues with its bean, you could consider re-building `llama-cpp-python` on your computer that is about to run `privateGPT` (it can be done offline as soon as you also `git clone` the `llama.cpp` and `llama-cpp-python` repos.

Managed to find out that it requires two files from Openai.
vocab.bpe & encoder.json.

Just download from here:
```
https://openaipublic.blob.core.windows.net/gpt-2/encodings/main/vocab.bpe

https://openaipublic.blob.core.windows.net/gpt-2/encodings/main/encoder.json
```

save it somewhere and remember the directory.

The code can be found in the following line 12-13.
`\Lib\site-packages\tiktoken_ext\openai_public.py`


Change the code to the directory of the saved files after you downloaded from openai.

```
def gpt2():
    mergeable_ranks = data_gym_to_mergeable_bpe_ranks(
        vocab_bpe_file=r"D:\mklink_cache\Privategpt\vocab.bpe",
        encoder_json_file=r"D:\mklink_cache\Privategpt\encoder.json",
    )
```

**Comment by Tyrannas** [comment]
@jackfood Do you know if by any chances those files are unavailable in France ? I get the same error as this issue when trying to start the make run, and I have internet. I tried your links directly in my browser but I'm getting timed out too (i mean this link https://openaipublic.blob.core.windows.net/gpt-2/encodings/main/vocab.bpe)

**Comment by lopagela** [comment]
@Tyrannas are you on Windows?

I'm in Belgium (chez nos amis les Belges 😉 ) and I have no issues to download the link you gave.

I tried with my commercial VPN (location set in France), and I have no errors.
I guess it must be linked to your network. Try to change of network, or start a VPN and try do download again.

**Comment by Tyrannas** [comment]
@lopagela (haha salut voisin!) yes I'm on windows, but I guess that should not have any influence on my ability to download the file with the direct link... I might have a dns issue maybe, thanks for trying with the VPN anyway !

**Comment by lopagela** [comment]
I am aware that some windows users are having SSL certificates issues with `requests`.
For that specific issue (`requests` on windows), it is apparently a common one (from the google queries I've been doing on that matter lately).

It might be your DNS indeed - you might be blocked by your network (if your are in universities or in restricted network, such as enterprise network).

**Comment by jackfood** [comment]
@Tyrannas 
[https://github.com/jackfood/Half-codeInterpreter](url)

**Comment by snikhil17** [comment]
What did you do for the embedding model. It downloads it everytime you run poetry run python scripts/setup.
