### ISSUE TITLE
Everything I have been trying to ingest caused an encoding error

### ISSUE THREAD

**Issue by unalignedcoder** [imartinez/privateGPT#1153]
On Windows 10, Python 3.11.6

Using bulk ingestion, with the command:
`poetry run python scripts/ingest_folder.py "folder\path"`

I keep getting this error:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 169: character maps to <undefined>`, after which ingestion stops. In fact, judging from the Gradio interface, nothing has been ingested at all.

I have seen previous similar issues being addressed by making a correction in relation to encoding, to a file name `ingest.py`, which however I cannot find anywhere.

Full console error message:

```
Traceback (most recent call last):
  File "I:\privateGPT-0.0.2\scripts\ingest_folder.py", line 41, in <module>
    _recursive_ingest_folder(path)
  File "I:\privateGPT-0.0.2\scripts\ingest_folder.py", line 28, in _recursive_ingest_folder
    _recursive_ingest_folder(file_path)
  File "I:\privateGPT-0.0.2\scripts\ingest_folder.py", line 28, in _recursive_ingest_folder
    _recursive_ingest_folder(file_path)
  File "I:\privateGPT-0.0.2\scripts\ingest_folder.py", line 26, in _recursive_ingest_folder
    _do_ingest(file_path)
  File "I:\privateGPT-0.0.2\scripts\ingest_folder.py", line 34, in _do_ingest
    ingest_service.ingest(changed_path.name, changed_path)
  File "I:\privateGPT-0.0.2\private_gpt\server\ingest\ingest_service.py", line 80, in ingest
    text = file_data.read_text()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\.pyenv\pyenv-win\versions\3.11.6\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Users\<user>\.pyenv\pyenv-win\versions\3.11.6\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 169: character maps to <undefined>
```

**Comment by unalignedcoder** [comment]
no ideas or suggestions? I can't be the only one who's having this problem...

**Comment by imamcs19** [comment]
I still have the same problem. 
'charmap' codec can't decode byte 0x9d in position 321: character maps to <undefined>

I upload a file via http://localhost:8001/ 
some *.txt files are successful, but other files contain unicode get error above.

**Comment by TomLucidor** [comment]
Same here but for HTML pages like @imamcs19 with TXT, I think there is an issue with auto-detecting text encoding.
Not sure if any of these are useful https://github.com/chardet/chardet https://github.com/douban/PyCharlockHolmes https://github.com/sonicdoe/detect-character-encoding https://github.com/CharsetDetector/UTF-unknown

**Comment by gthieleb** [comment]
https://dev.to/methane/python-use-utf-8-mode-on-windows-212i

**Comment by urlan** [comment]
**ingest_helper.py** can be found on private_gpt > components > ingest

However, about this:

> `return string_reader.load_data([file_data.read_text(errors='replace')])`

I suggest NOT to use this solution. It only makes garbage.
