### ISSUE TITLE
llama_index.chat_engine.types - Encountered exception writing response to history: Requested tokens (11953) exceed context window of 3900

### ISSUE THREAD

**Issue by yaziciali** [imartinez/privateGPT#1175]
I only asked "beşi beş kuruştan beş yumurta kaç kuruş eder?" then it gives error below, How can fix that?

AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | 
00:00:01.890 [INFO    ]             uvicorn.error - Started server process [16055]
00:00:01.890 [INFO    ]             uvicorn.error - Waiting for application startup.
00:00:01.890 [INFO    ]             uvicorn.error - Application startup complete.
00:00:01.891 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
00:11:39.762 [INFO    ]            uvicorn.access - 127.0.0.1:55481 - "GET / HTTP/1.1" 200
00:11:39.837 [INFO    ]            uvicorn.access - 127.0.0.1:55481 - "GET /info HTTP/1.1" 200
00:11:39.887 [INFO    ]            uvicorn.access - 127.0.0.1:55481 - "GET /theme.css HTTP/1.1" 200
00:11:39.910 [INFO    ]            uvicorn.access - 127.0.0.1:55481 - "GET /assets/StaticMarkdown-06312fb7.js HTTP/1.1" 200
00:11:54.329 [INFO    ]            uvicorn.access - 127.0.0.1:55483 - "POST /run/predict HTTP/1.1" 200
00:11:54.329 [INFO    ]            uvicorn.access - 127.0.0.1:55492 - "POST /run/predict HTTP/1.1" 200
00:11:54.354 [INFO    ]            uvicorn.access - 127.0.0.1:55492 - "POST /run/predict HTTP/1.1" 200
00:11:54.375 [INFO    ]             uvicorn.error - ('127.0.0.1', 55494) - "WebSocket /queue/join" [accepted]
00:11:54.376 [INFO    ]             uvicorn.error - connection open
00:11:54.919 [WARNING ] llama_index.chat_engine.types - Encountered exception writing response to history: Requested tokens (11953) exceed context window of 3900
Traceback (most recent call last):
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 437, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 498, in run_sync_iterator_async
    raise StopAsyncIteration() from None
StopAsyncIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ayazici/Library/Caches/pypoetry/virtualenvs/private-gpt-m0i6Ug4C-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 623, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
RuntimeError: async generator raised StopAsyncIteration
00:11:54.929 [INFO    ]             uvicorn.error - connection closed
00:11:54.942 [INFO    ]            uvicorn.access - 127.0.0.1:55492 - "POST /run/predict HTTP/1.1" 200

**Comment by alrex-benchmarking** [comment]
I also encountered this issue with the latest version after ingesting a csv file that has 135,000 rows.

`[WARNING ] llama_index.chat_engine.types - Encountered exception writing response to history: Requested tokens (25625) exceed context window of 3900`

**Comment by mrktechy** [comment]
I am encountering this problem today and dont know how it was solved. Could someone help? It is marked as stale but no other information.
