### ISSUE TITLE
Can't run quick start on mac silicon laptop

### ISSUE THREAD

**Issue by gvidaver** [imartinez/privateGPT#1184]
Hi,
 I followed the quick start steps (https://docs.privategpt.dev/#section/Quick-Local-Installation-steps), but when I go to launch I get the following:

 We're behind a proxy, maybe that's causing it?

```
(base) go22670@581622-MITLL privateGPT % PGPT_PROFILES=local make run

poetry run python -m private_gpt
12:20:08.405 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'local']

Traceback (most recent call last):
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/go22670/Projects/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/Users/go22670/Projects/privateGPT/private_gpt/main.py", line 106, in <module>
    from private_gpt.ui.ui import mount_in_app
  File "/Users/go22670/Projects/privateGPT/private_gpt/ui/ui.py", line 19, in <module>
    ingest_service = root_injector.get(IngestService)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/go22670/Projects/privateGPT/private_gpt/components/llm/llm_component.py", line 20, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "/Users/go22670/Library/Caches/pypoetry/virtualenvs/private-gpt-NfdSSkdX-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 105, in __init__
    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.

make: *** [run] Error 1
```

**Comment by lopagela** [comment]
I see in your prompt you are in a venv -- `(base)`

Are your sure this env have the proper versions of the required lib installed?

The issue must be linked to the way you did your installation, I'd suggest to try again in a clean `venv`.

**Comment by adrianboguszewski** [comment]
@gvidaver did you run `poetry run python scripts/setup` as stated in https://docs.privategpt.dev/#section/Quick-Local-Installation-steps?

**Comment by gvidaver** [comment]
The short answer is yes. Attached is a full log of all the steps and what I see. This is on a Mac Book Pro Silicon laptop running 13.6.1, running behind a firewall, if that helps.
[installLog.txt](https://github.com/imartinez/privateGPT/files/13386488/installLog.txt)

**Comment by adrianboguszewski** [comment]
The above solved the issue for me :)

**Comment by xiaobc1234** [comment]
> @gvidaver[您是否按照https://docs.privategpt.dev/#section/Quick-Local-Installation-steps](https://docs.privategpt.dev/#section/Quick-Local-Installation-steps)`poetry run python scripts/setup`中所述运行？[](https://docs.privategpt.dev/#section/Quick-Local-Installation-steps)

"poetry run python scripts/setup" I downloaded the llm model and embedding model manually, do I still need to execute this command? I now execute the "python3.11 -m private_gpt" command and it also reports an error

**Comment by ajay9438** [comment]
(privateGPT) C:\Users\AJAY\Desktop\PrivateGpt>poetry run python -m private_gpt
18:14:10.131 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
18:14:12.549 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
Traceback (most recent call last):
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\llama_index\llms\llama_cpp.py", line 102, in __init__
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AJAY\Desktop\PrivateGpt\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "C:\Users\AJAY\Desktop\PrivateGpt\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\Desktop\PrivateGpt\private_gpt\launcher.py", line 125, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AJAY\Desktop\PrivateGpt\private_gpt\components\llm\llm_component.py", line 31, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "C:\Users\AJAY\anaconda3\envs\privateGPT\Lib\site-packages\llama_index\llms\llama_cpp.py", line 104, in __init__
    raise ImportError(
ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`

**Comment by lopagela** [comment]
@ajay9438 did you try to run the command present in the output message?

**Comment by ajay9438** [comment]
@lopagela yes i did the following command but out was same

**Comment by lopagela** [comment]
Try the following:
1. Delete your venv
2. Delete `poetry.lock`
3. Re-run the quickstart
