### ISSUE TITLE
page label error

### ISSUE THREAD

**Issue by iplayfast** [imartinez/privateGPT#1189]
Uploaded some cpp files as a doc.
Asked it to list the functions in the file.
The screen showed a "page label error" and "error" but otherwise did nothing.
At the console side
Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/utils.py", line 623, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/chat_interface.py", line 437, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/privategpt/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/chris/ai/privateGPT/private_gpt/ui/ui.py", line 71, in _chat
    yield "\n\n\n".join(
          ^^^^^^^^^^^^^^
  File "/home/chris/ai/privateGPT/private_gpt/ui/ui.py", line 73, in <genexpr>
    f"(page {chunk.document.doc_metadata['page_label'] if chunk.document.doc_metadata else ''})**\n "
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'page_label'
14:38:17.001 [INFO    ]             uvicorn.error - connection closed
14:38:17.012 [INFO    ]            uvicorn.access - 127.0.0.1:43724 - "POST /run/predict HTTP/1.1" 200

**Comment by jromal** [comment]
Same error here. But it was the first time using PrivateGPT. 
PDF files were injected properly. But with Markdown text files ingested massively gave me this error.

**Comment by frankwmoyer** [comment]
Same error with asciidoc files.

= `adb` commands
:navtitle: `adb` commands

These are the Android Debug Bridge (`adb`) commands you can xref:manual-testing:device-controls.adoc#_adb_shell[run during a manual session], which includes installing apps, managing persmissions, analyzing performance, and more.

image:manual-testing:adb-shell-context.png[width=1100, alt="A manual session with the `adb` shell open."]

== Public devices

Since public devices are shared across all Kobiton users, only the following `adb` commands are supported:

* `dumpsys display`
* `dumpsys battery`
* `pm list packages -3`

== Private and local devices

You can run most `adb` commands on private and local devices--as long as they don't harm the device or alter systems in real-time.

These are the type of commands we *don't* allow:

* `kobiton/i`
* `logcat/i`
* `monkey/i`
* `top/i`
* `com.domobile.applock/i`
* `com.domobile.applockwatcher/i`
* `com.sp.protector.free/i`
* `com.manageengine.mdm.android/i`
* `com.manageengine.mdm.samsung.knox/i`
* `com.manageengine.mdm.samsung/i`
* `com.manageengine.admp/i`
* `com.android.systemui/i`
* `com.android.settings/i`
* `com.android.vending/i`
* `com.google.android.webview/i`
* `monkey -p com.myAppPackage -v 10000 -s 100`

**Comment by joshuachris2001** [comment]
I'm having the same error, but this seems to effect doc files, txt files, etc. while pdfs are working, I have a ton of non-pdf files and converting is inefficient.

**Comment by Exw27** [comment]
Ye I did some testing the Chunks Retrieval only works with pdf files, hopefully more file format will be supported in the next update.

**Comment by TheAnachronism** [comment]
I've just tried an HTML file and I get the same error.

**Comment by lopagela** [comment]
Working on a quick fix -- cc @imartinez (looks like the string formatting need to be a bit more robust when the context is being asked)

**Comment by PhotoNomad0** [comment]
I was able to get it to work by changing ui.py starting at line 85 to:
```
                yield "\n\n\n".join(
                    f"{index}. **{chunk.document.doc_metadata['file_name'] if 'file_name' in chunk.document.doc_metadata else ''} "
                    f"(page {chunk.document.doc_metadata['page_label'] if 'page_label' in chunk.document.doc_metadata else ''})**\n "
                    f"{chunk.text}"
                    for index, chunk in enumerate(response, start=1)
                )
```

**Comment by imartinez** [comment]
We just merged a fix. Check UI file. Please reopen if you experience it again. Thanks!
