### ISSUE TITLE
Internal Server Error when calling DELETE on /v1/ingest/{doc_id} endpoint

### ISSUE THREAD

**Issue by frankwmoyer** [imartinez/privateGPT#1210]
I deployed privateGPT locally without connection to OpenAI.

Here are the results of the `/v1/ingest/list` endpoint:

```
{"object":"list","model":"private-gpt","data":[{"object":"ingest.document","doc_id":"6afb5c70-3813-42e9-a892-71223298f943","doc_metadata":{"page_label":"18","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"a2c0033d-e126-47cc-9f8f-c744513138cd","doc_metadata":{"page_label":"11","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"178018d1-d530-4873-bd97-7f75b9e2723b","doc_metadata":{"page_label":"12","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"d490ea07-e491-48af-b44b-4ee1587888fd","doc_metadata":{"file_name":"adb-commands.adoc"}},{"object":"ingest.document","doc_id":"261cfdcb-c7fc-488b-9a64-3d35d1793310","doc_metadata":{"page_label":"19","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"3af1c86b-818a-457e-b878-f063b2cc52c2","doc_metadata":{"page_label":"13","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"ffb1a0ec-f88f-44b9-ad3c-9c7ff53080d2","doc_metadata":{"page_label":"4","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"205aad0c-be3c-4a01-8048-338f9e4e2b4f","doc_metadata":{"page_label":"1","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"55a3327b-fab7-40b1-be9d-4f6459bc85c3","doc_metadata":{"page_label":"8","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"8de004c3-d181-47a6-82cc-d5bf975af5c8","doc_metadata":{"page_label":"16","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"fad4d517-bac1-492c-bbbb-5937e9b71382","doc_metadata":{"page_label":"3","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"99ddc841-c680-4bcb-a869-521381dea67b","doc_metadata":{"page_label":"7","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"5153357d-3e36-467b-bbd3-6789ae1a77f0","doc_metadata":{"page_label":"17","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"d386813a-ac4d-41be-81ff-b7c6e1223929","doc_metadata":{"page_label":"20","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"5072702d-bec5-472e-80fd-b0697f6a10c5","doc_metadata":{"page_label":"23","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"881c8845-359f-4162-b2e2-c07962c703be","doc_metadata":{"page_label":"22","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"b09e39aa-4668-4e22-954f-a735ea502450","doc_metadata":{"page_label":"5","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"8389ceab-7224-484f-adef-ff9edf4a4b5b","doc_metadata":{"page_label":"14","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"1069812b-1a58-404d-af14-a25335488e62","doc_metadata":{"page_label":"10","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"f60da31e-2e5f-4c51-b870-63d75623b340","doc_metadata":{"file_name":"custom-gestures.adoc"}},{"object":"ingest.document","doc_id":"a110a903-10d3-458b-836a-3ca1445b65cc","doc_metadata":{"page_label":"15","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"c3e3b8e2-8172-44ea-9ea8-dd0324b256d8","doc_metadata":{"page_label":"2","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"d424752e-b72b-49da-b9a3-c0268d8f9799","doc_metadata":{"page_label":"6","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"ab9af793-ff44-49f6-aebb-0f1e82049d6b","doc_metadata":{"page_label":"21","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}},{"object":"ingest.document","doc_id":"bb90c39a-506b-4268-a5cc-631b54f99bbb","doc_metadata":{"page_label":"9","file_name":"Troubleshooting guideline - Kobiton - Confluence.pdf"}}]}
```

When I call `curl -X DELETE "http://localhost:8001/v1/ingest/178018d1-d530-4873-bd97-7f75b9e2723b"` to delete one of the ingested documents, the server throws an exception and the client receives `Internal Server Error`:
```
******
23:57:21.841 [INFO    ]            uvicorn.access - 127.0.0.1:64199 - "DELETE /v1/ingest/178018d1-d530-4873-bd97-7f75b9e2723b HTTP/1.1" 500
23:57:21.847 [ERROR   ]             uvicorn.error - Exception in ASGI application
Traceback (most recent call last):
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 192, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/src/privateGPT/private_gpt/server/ingest/ingest_router.py", line 60, in delete_ingested
    service.delete(doc_id)
  File "/Users/Frank/src/privateGPT/private_gpt/server/ingest/ingest_service.py", line 193, in delete
    index = load_index_from_storage(self.storage_context, store_nodes_override=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Frank/Library/Caches/pypoetry/virtualenvs/private-gpt-EIGzJky6-py3.11/lib/python3.11/site-packages/llama_index/indices/loading.py", line 40, in load_index_from_storage
    raise ValueError(
ValueError: Expected to load a single index, but got 3 instead. Please specify index_id.

```

**Comment by imartinez** [comment]
Fixed on main. 

You'll need to delete the local data folder and reingest your docs. Sorry for the inconveniences.
