### ISSUE TITLE
Issues installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by stofarius** [imartinez/privateGPT#1213]
Hi,

I have Ubuntu Server 22.04 without X. I cloned the repository and started to follow installation steps, however when I am trying to run the local server I get the error below:

`

 Using python3 (3.11.6)
Traceback (most recent call last):
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
           ^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 150, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 331, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/helpconfig.py", line 104, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1327, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1153, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 563, in _set_initial_conftests
    self._try_load_conftest(anchor, importmode, rootpath)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 580, in _try_load_conftest
    self._getconftestmodules(anchor, importmode, rootpath)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 609, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 657, in _importconftest
    self.consider_conftest(mod)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 739, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 498, in register
    self.consider_module(plugin)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 747, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 754, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 781, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/home/marius/Work/privateGPT/tests/fixtures/ingest_helper.py", line 6, in <module>
    from private_gpt.server.ingest.ingest_router import IngestResponse
  File "/home/marius/Work/privateGPT/private_gpt/server/ingest/ingest_router.py", line 5, in <module>
    from private_gpt.server.ingest.ingest_service import IngestedDoc, IngestService
  File "/home/marius/Work/privateGPT/private_gpt/server/ingest/ingest_service.py", line 7, in <module>
    from llama_index import (
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/__init__.py", line 17, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/embeddings/__init__.py", line 18, in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/embeddings/openai.py", line 18, in <module>
    from llama_index.llms.openai_utils import (
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/llms/__init__.py", line 2, in <module>
    from llama_index.llms.anyscale import Anyscale
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/llms/anyscale.py", line 11, in <module>
    from llama_index.llms.openai import OpenAI
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/llms/openai.py", line 28, in <module>
    from llama_index.llms.openai_utils import (
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/llama_index/llms/openai_utils.py", line 107, in <module>
    CompletionClientType = Union[Type[Completion], Type[ChatCompletion]]
                                 ~~~~^^^^^^^^^^^^
  File "/home/marius/.pyenv/versions/3.11.6/lib/python3.11/typing.py", line 355, in inner
    return cached(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.pyenv/versions/3.11.6/lib/python3.11/typing.py", line 1565, in __getitem__
    if not isinstance(params, tuple):
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/openai/_utils/_proxy.py", line 39, in __class__
    return self.__get_proxied__().__class__
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "/home/marius/.cache/pypoetry/virtualenvs/private-gpt-7O-on_Gt-py3.11/lib/python3.11/site-packages/openai/lib/_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
 
`

I checked and I have OpenAI 1.2.0, I even tried “OpenAI migrate” but I still have above error. Any ideea how can I fix this?

Thank you!

**Comment by Dimashaman** [comment]
So did you install older version or not?

**Comment by stofarius** [comment]
> So did you install older version or not?

Installed it, tried both versions in fact and it’s doing the same.
