### ISSUE TITLE
Command "poetry run python scripts/setup" on Conda Powershell returns that a module does not exists.

### ISSUE THREAD

**Issue by frenchiveruti** [imartinez/privateGPT#1223]
Hello, I am not sure if this is an implementation issue, a windows issue or what, I couldn't find any information online. 

I was following this video: 
https://www.youtube.com/watch?v=XFiof0V3nhA

I was able to get to:
```
poetry install --with ui,local
```

So far, so good, I've checked the modules installed in my conda environment: 
```
(privategpt)  ~\privateGPT  > conda list |select-string pydantic*

pydantic                  2.4.2                    pypi_0    pypi
pydantic-core             2.10.1                   pypi_0    pypi
pydantic-extra-types      2.1.0                    pypi_0    pypi
pydantic-settings         2.0.3                    pypi_0    pypi
```

I checked the folder: (...) miniconda3\envs\privategpt\Lib\site-packages\pydantic\v1  
And after all that, when I run the `poetry run python scripts/setup` I get the following error: 
```
> poetry run -vvv python scripts/setup
Using virtualenv: C:\Users\Fran\miniconda3\envs\privategpt
Traceback (most recent call last):
  File "C:\Users\Fran\privateGPT\scripts\setup", line 6, in <module>
    from private_gpt.paths import models_path, models_cache_path
  File "C:\Users\Fran\privateGPT\private_gpt\paths.py", line 4, in <module>
    from private_gpt.settings.settings import settings
  File "C:\Users\Fran\privateGPT\private_gpt\settings\settings.py", line 5, in <module>
    from private_gpt.settings.settings_loader import load_active_profiles
  File "C:\Users\Fran\privateGPT\private_gpt\settings\settings_loader.py", line 8, in <module>
    from pydantic.v1.utils import deep_update, unique_list
ModuleNotFoundError: No module named 'pydantic.v1'
```

I can't make sense of this, I am not sure how is conda setting the environment but I even did: 
```python 
(privategpt)   ~\privateGPT  git:main python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pydantic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pydantic' is not defined
>>> import pydantic
>>> pydantic
<module 'pydantic' from 'C:\\Users\\Fran\\AppData\\Roaming\\Python\\Python311\\site-packages\\pydantic\\__init__.cp311-win_amd64.pyd'> 
```

Another approach I had, using "poetry run python" alone to get a prompt:
``` python
(privategpt)   ~\privateGPT  git:main poetry run python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import functools
>>> import logging
>>> import os
>>> import sys
>>> from pathlib import Path
>>> from typing import Any
>>> from pydantic.v1.utils import deep_update,unique_list
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pydantic.v1'
```

Here I then ran "help()" and then "modules pydantic": 
``` 

help> modules pydantic

Here is a list of modules whose name or summary contains 'pydantic'.
If there are any, enter a module name to get more help.

openapi_schema_pydantic
openapi_schema_pydantic.util
openapi_schema_pydantic.v3
openapi_schema_pydantic.v3.v3_0_3 - OpenAPI v3.0.3 schema types, created according to the specification:
openapi_schema_pydantic.v3.v3_0_3.callback
openapi_schema_pydantic.v3.v3_0_3.components
openapi_schema_pydantic.v3.v3_0_3.contact
openapi_schema_pydantic.v3.v3_0_3.discriminator
openapi_schema_pydantic.v3.v3_0_3.encoding
openapi_schema_pydantic.v3.v3_0_3.example
openapi_schema_pydantic.v3.v3_0_3.external_documentation
openapi_schema_pydantic.v3.v3_0_3.header
openapi_schema_pydantic.v3.v3_0_3.info
openapi_schema_pydantic.v3.v3_0_3.license
openapi_schema_pydantic.v3.v3_0_3.link
openapi_schema_pydantic.v3.v3_0_3.media_type
openapi_schema_pydantic.v3.v3_0_3.oauth_flow
openapi_schema_pydantic.v3.v3_0_3.oauth_flows
openapi_schema_pydantic.v3.v3_0_3.open_api
openapi_schema_pydantic.v3.v3_0_3.operation
openapi_schema_pydantic.v3.v3_0_3.parameter
openapi_schema_pydantic.v3.v3_0_3.path_item
openapi_schema_pydantic.v3.v3_0_3.paths
openapi_schema_pydantic.v3.v3_0_3.reference
openapi_schema_pydantic.v3.v3_0_3.request_body
openapi_schema_pydantic.v3.v3_0_3.response
openapi_schema_pydantic.v3.v3_0_3.responses
openapi_schema_pydantic.v3.v3_0_3.schema
openapi_schema_pydantic.v3.v3_0_3.security_requirement
openapi_schema_pydantic.v3.v3_0_3.security_scheme
openapi_schema_pydantic.v3.v3_0_3.server
openapi_schema_pydantic.v3.v3_0_3.server_variable
openapi_schema_pydantic.v3.v3_0_3.tag
openapi_schema_pydantic.v3.v3_0_3.util
openapi_schema_pydantic.v3.v3_0_3.xml
openapi_schema_pydantic.v3.v3_1_0 - OpenAPI v3.1.0 schema types, created according to the specification:
openapi_schema_pydantic.v3.v3_1_0.callback
openapi_schema_pydantic.v3.v3_1_0.components
openapi_schema_pydantic.v3.v3_1_0.contact
openapi_schema_pydantic.v3.v3_1_0.discriminator
openapi_schema_pydantic.v3.v3_1_0.encoding
openapi_schema_pydantic.v3.v3_1_0.example
openapi_schema_pydantic.v3.v3_1_0.external_documentation
openapi_schema_pydantic.v3.v3_1_0.header
openapi_schema_pydantic.v3.v3_1_0.info
openapi_schema_pydantic.v3.v3_1_0.license
openapi_schema_pydantic.v3.v3_1_0.link
openapi_schema_pydantic.v3.v3_1_0.media_type
openapi_schema_pydantic.v3.v3_1_0.oauth_flow
openapi_schema_pydantic.v3.v3_1_0.oauth_flows
openapi_schema_pydantic.v3.v3_1_0.open_api
openapi_schema_pydantic.v3.v3_1_0.operation
openapi_schema_pydantic.v3.v3_1_0.parameter
openapi_schema_pydantic.v3.v3_1_0.path_item
openapi_schema_pydantic.v3.v3_1_0.paths
openapi_schema_pydantic.v3.v3_1_0.reference
openapi_schema_pydantic.v3.v3_1_0.request_body
openapi_schema_pydantic.v3.v3_1_0.response
openapi_schema_pydantic.v3.v3_1_0.responses
openapi_schema_pydantic.v3.v3_1_0.schema
openapi_schema_pydantic.v3.v3_1_0.security_requirement
openapi_schema_pydantic.v3.v3_1_0.security_scheme
openapi_schema_pydantic.v3.v3_1_0.server
openapi_schema_pydantic.v3.v3_1_0.server_variable
openapi_schema_pydantic.v3.v3_1_0.tag
openapi_schema_pydantic.v3.v3_1_0.xml
pydantic
pydantic._hypothesis_plugin
pydantic.annotated_types
pydantic.class_validators
pydantic.color
pydantic.config
pydantic.dataclasses
pydantic.datetime_parse
pydantic.decorator
pydantic.env_settings
pydantic.error_wrappers
pydantic.errors
pydantic.fields
pydantic.generics
pydantic.json
pydantic.main
pydantic.mypy
pydantic.networks
pydantic.parse
pydantic.schema
pydantic.tools
pydantic.types
pydantic.typing
pydantic.utils
pydantic.validators
pydantic.version
gradio.data_classes - Pydantic data models and other dataclasses. This is the only file that uses Optional[]
langchain.output_parsers.pydantic
langchain.pydantic_v1
langchain.pydantic_v1.dataclasses
langchain.pydantic_v1.main
langchain.tools.openapi.utils.api_models - Pydantic models for parsing an OpenAPI spec.
langchain.utils.pydantic - Utilities for tests.
llama_index.bridge.pydantic
llama_index.output_parsers.pydantic - Pydantic output parser.
llama_index.selectors.pydantic_selectors
pydantic_core
pydantic_core._pydantic_core
pydantic_core.core_schema - This module contains definitions to build schemas which `pydantic_core` can
pydantic_extra_types
pydantic_extra_types.color - Color definitions are used as per the CSS3
pydantic_extra_types.coordinate
pydantic_extra_types.country - Country definitions that are based on the ISO 3166 format
pydantic_extra_types.mac_address - MAC address Parsing and Validation
pydantic_extra_types.payment - Represents and validates payment cards (such as a debit or credit card),
pydantic_extra_types.phone_numbers
pydantic_extra_types.routing_number
pydantic_settings
```

Then, I asked ChatGPT and suggested the following: 
```python
import pydantic
print(pydantic.__file__)
```
This returned: 
`%Appdata%\Python\Python311\site-packages\pydantic\__init__.cp311-win_amd64.pyd`

Therefore, is this conda working wrong? 
I understand then that it's loading a pydantic module with the wrong version, basically it's giving zero effs about the conda environment, right?

Now, here's where IDK what is going on, I'm no python dev and packages/modules/environments confuse me. 

Can someone help me here? I'm really lost on what's the issue.

**Comment by pabloogc** [comment]
Seems like a conda issue. Maybe the package distributed here https://anaconda.org/conda-forge/pydantic is not the same as the one in pypy. 

Maybe you can try to install it directly with pip, `poetry run pip install pydantic` see if that helps

**Comment by frenchiveruti** [comment]
> Seems like a conda issue. Maybe the package distributed here https://anaconda.org/conda-forge/pydantic is not the same as the one in pypy.
> 
> Maybe you can try to install it directly with pip, `poetry run pip install pydantic` see if that helps

Yeah there's an issue with my conda installation, I think windows just loves to overcomplicate things. 
I'll try re-installing MiniConda.

**Comment by frenchiveruti** [comment]
Well, that didn't work. I have no idea why it's not registering the conda environment.

**Comment by frenchiveruti** [comment]
> Seems like a conda issue. Maybe the package distributed here https://anaconda.org/conda-forge/pydantic is not the same as the one in pypy.
> 
> Maybe you can try to install it directly with pip, `poetry run pip install pydantic` see if that helps

I was under the impression that poetry would use pypi instead of conda forge.

**Comment by frenchiveruti** [comment]
I ended up removing the roaming folder and that solved it. 
Still unsure how to handle conda properly.

**Comment by kolqueqo** [comment]
> I ended up removing the roaming folder and that solved it. Still unsure how to handle conda properly.

Hello! It seems like i have the same issue. What does "removing the roaming folder" mean? Did u remove .anaconda package from roaming folder or did u removed it from PATH somewhere? 

Thank you in advance

**Comment by frenchiveruti** [comment]
> > I ended up removing the roaming folder and that solved it. Still unsure how to handle conda properly.
> 
> Hello! It seems like i have the same issue. What does "removing the roaming folder" mean? Did u remove .anaconda package from roaming folder or did u removed it from PATH somewhere?
> 
> Thank you in advance

%Appdata% is the "roaming folder" and it's basically going in there, look for the folder called "Python311" and nuking it. 
`rm %appdata%\python\python311` in powershell
