### ISSUE TITLE
i get this exception in Ubuntu 22.0.4 while using LLM chat

### ISSUE THREAD

**Issue by namdroid** [imartinez/privateGPT#1237]
19:05:09.370 [INFO    ]            uvicorn.access - 79.236.150.39:64646 - "POST /run/predict HTTP/1.1" 200
19:05:09.432 [INFO    ]             uvicorn.error - ('79.236.150.39', 64647) - "WebSocket /queue/join" [accepted]
19:05:09.437 [INFO    ]             uvicorn.error - connection open
Traceback (most recent call last):
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 623, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 437, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by rmuhawieh** [comment]
> 19:05:09.370 [INFO ] uvicorn.access - 79.236.150.39:64646 - "POST /run/predict HTTP/1.1" 200 19:05:09.432 [INFO ] uvicorn.error - ('79.236.150.39', 64647) - "WebSocket /queue/join" [accepted] 19:05:09.437 [INFO ] uvicorn.error - connection open Traceback (most recent call last): File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction output = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function prediction = await utils.async_iteration(iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 623, in asyncgen_wrapper async for response in f(*args, **kwargs): File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 437, in _stream_fn first_response = await async_iteration(generator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/developer/.cache/pypoetry/virtualenvs/private-gpt-GE8Zy8jc-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^

Did you ever find the solution to this?
