### ISSUE TITLE
Runtime error, when starting privateGPT in Docker container.

### ISSUE THREAD

**Issue by angel1st** [imartinez/privateGPT#1246]
Hey there,
I made `docker-compose.yml` (see below):
````version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.external
      target: app
    ports:
      - "8080:8080"
    volumes:
      - ./local_data:/home/worker/app/local_data
      - ./models:/home/worker/app/models
````

then built image and run container.
When `docker-compose up` is executed, below is the error I have got:
````
[+] Running 1/1
 ✔ Container privategpt-app-1  Recreated                                                                                                                                                           0.2s 
Attaching to privategpt-app-1
privategpt-app-1  | 14:52:53.868 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
privategpt-app-1  | 14:52:54.915 [WARNING ]                matplotlib - Matplotlib created a temporary cache directory at /tmp/matplotlib-8j034ncq because the default path (/nonexistent/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
privategpt-app-1  | 14:52:55.584 [INFO    ]   matplotlib.font_manager - generated new fontManager
privategpt-app-1  | Traceback (most recent call last):
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
privategpt-app-1  |     return self._context[key]
privategpt-app-1  |            ~~~~~~~~~~~~~^^^^^
privategpt-app-1  | KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>
privategpt-app-1  | 
privategpt-app-1  | During handling of the above exception, another exception occurred:
privategpt-app-1  | 
privategpt-app-1  | Traceback (most recent call last):
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
privategpt-app-1  | 
privategpt-app-1  |     return self._context[key]
privategpt-app-1  |            ~~~~~~~~~~~~~^^^^^
privategpt-app-1  | KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>
privategpt-app-1  | 
privategpt-app-1  | During handling of the above exception, another exception occurred:
privategpt-app-1  | 
privategpt-app-1  | Traceback (most recent call last):
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
privategpt-app-1  | 
privategpt-app-1  |     return self._context[key]
privategpt-app-1  |            ~~~~~~~~~~~~~^^^^^
privategpt-app-1  | KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>
privategpt-app-1  | 
privategpt-app-1  | During handling of the above exception, another exception occurred:
privategpt-app-1  | 
privategpt-app-1  | Traceback (most recent call last):
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 88, in __init__
privategpt-app-1  | 
privategpt-app-1  |     from llama_cpp import Llama
privategpt-app-1  | ModuleNotFoundError: No module named 'llama_cpp'
privategpt-app-1  | 
privategpt-app-1  | During handling of the above exception, another exception occurred:
privategpt-app-1  | 
privategpt-app-1  | Traceback (most recent call last):
privategpt-app-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
privategpt-app-1  |   File "<frozen runpy>", line 88, in _run_code
privategpt-app-1  |   File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
privategpt-app-1  | 
privategpt-app-1  |     from private_gpt.main import app
privategpt-app-1  |   File "/home/worker/app/private_gpt/main.py", line 11, in <module>
privategpt-app-1  |     app = create_app(global_injector)
privategpt-app-1  | 
privategpt-app-1  |  ^^^^^^^^^^^^^^^^^
privategpt-app-1  | ^^^^
privategpt-app-1  | ^^^
privategpt-app-1  | ^^
privategpt-app-1  | ^
privategpt-app-1  |   File "/home/worker/app/private_gpt/launcher.py", line 125, in create_app
privategpt-app-1  |     ui = root_injector.get(PrivateGptUi)
privategpt-app-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  | 
privategpt-app-1  | ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
privategpt-app-1  |     provider_instance = scope_instance.get(interface, binding.provider)
privategpt-app-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  | ^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^
privategpt-app-1  | ^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
privategpt-app-1  |     instance = self._get_instance(key, provider, self.injector)
privategpt-app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
privategpt-app-1  |     return provider.get(injector)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
privategpt-app-1  |     return injector.create_object(self._cls)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
privategpt-app-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
privategpt-app-1  |     dependencies = self.args_to_inject(
privategpt-app-1  |                    ^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
privategpt-app-1  |     instance: Any = self.get(interface)
privategpt-app-1  |                     ^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
privategpt-app-1  |     provider_instance = scope_instance.get(interface, binding.provider)
privategpt-app-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  | ^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
privategpt-app-1  |     instance = self._get_instance(key, provider, self.injector)
privategpt-app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
privategpt-app-1  |     return provider.get(injector)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
privategpt-app-1  |     return injector.create_object(self._cls)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
privategpt-app-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
privategpt-app-1  |     dependencies = self.args_to_inject(
privategpt-app-1  |                    ^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
privategpt-app-1  |     instance: Any = self.get(interface)
privategpt-app-1  |                     ^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  | 
privategpt-app-1  |    ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
privategpt-app-1  |     provider_instance = scope_instance.get(interface, binding.provider)
privategpt-app-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
privategpt-app-1  |     return function(*args, **kwargs)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
privategpt-app-1  |     instance = self._get_instance(key, provider, self.injector)
privategpt-app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  | ^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
privategpt-app-1  |     return provider.get(injector)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
privategpt-app-1  |     return injector.create_object(self._cls)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
privategpt-app-1  |     self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
privategpt-app-1  |     return callable(*full_args, **dependencies)
privategpt-app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/private_gpt/components/llm/llm_component.py", line 20, in __init__
privategpt-app-1  |     self.llm = LlamaCPP(
privategpt-app-1  |                ^^^^^^^^^
privategpt-app-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 90, in __init__
privategpt-app-1  |     raise ImportError(
privategpt-app-1  | ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
privategpt-app-1 exited with code 1
````
I am under Windows and use Docker Desktop.

**Comment by pabloogc** [comment]
the `Dockerfile.external` is meant to use an external LLM (basically sagemaker, the only one we support out of the box). However, the default mode is local execution, that's why it's complaining about  llama-cpp. If you want to keep using local execution you will have to use `Dockerfile.local` or configure your docker service to use sagemaker.
