### ISSUE TITLE
Cannot start PrivateGPT with CUDA

### ISSUE THREAD

**Issue by AntoineQ1** [imartinez/privateGPT#1248]
Hello,

After solving numerous problems (involving copy/paste some files from CUDA to VS Build Tools), I finally managed to build llama with GPU :
` $env:CMAKE_ARGS="-DLLAMA_CUBLAS=on"; poetry run pip install --force-reinstall --no
-cache-dir llama-cpp-python`

However, PrivateGPT stops working :
```(private-gpt-py3.11) PS C:\Users\Me\Documents\Dev\IA\privateGPT> make run
poetry run python -m private_gpt
18:28:45.177 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get 
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get 
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 69, in _lo
ad_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\anaconda3\envs\main311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_
cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\Documents\Dev\IA\privateGPT\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "C:\Users\Me\Documents\Dev\IA\privateGPT\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\Documents\Dev\IA\privateGPT\private_gpt\launcher.py", line 125, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get 
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get 
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get
_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get 
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 998, in crea
te_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in cal
l_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in arg
s_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get 
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get 
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get
_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get 
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 998, in crea
te_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in cal
l_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in arg
s_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get 
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapp
er
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get 
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get
_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get 
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 998, in crea
te_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\injector\__init__.py", line 1040, in cal
l_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\Documents\Dev\IA\privateGPT\private_gpt\components\llm\llm_component.py", line 20, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_index\llms\llama_cpp.py", line 88,
 in __init__
    from llama_cpp import Llama
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_cpp\__init__.py", line 1, in <modu
le>
    from .llama_cpp import *
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 82, in <mo
dule>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 71, in _lo
ad_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\lla
ma_cpp\llama.dll': Could not find module 'C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_
cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
make: *** [run] Erreur 1
```

Thanks in advance for your help :)

**Comment by pabloogc** [comment]
Well, looks like it didn't compile properly ```FileNotFoundError: Could not find module 'C:\Users\Me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TB-ZE-ag-py3.11\Lib\site-packages\llama_
cpp\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.```. that dll was not generated. 

I will close this issue because it's not really related to PrivateGPT, [llama.cpp]( https://github.com/ggerganov/llama.cpp) devs can probably help you with this.
