### ISSUE TITLE
Can't find model running local Docker

### ISSUE THREAD

**Issue by SjoerdBraaksma** [imartinez/privateGPT#1251]
Hi! 

I build the Dockerfile.local with an llm model installed in models following your instructions. However, I get the following error:

```
22:44:47.903 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
22:44:48.847 [WARNING ]                matplotlib - Matplotlib created a temporary cache directory at /tmp/matplotlib-7k50nlkq because the default path (/nonexistent/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
22:44:49.455 [INFO    ]   matplotlib.font_manager - generated new fontManager
Traceback (most recent call last):
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/worker/app/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/worker/app/private_gpt/main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/private_gpt/launcher.py", line 125, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/worker/app/.venv/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/private_gpt/components/llm/llm_component.py", line 20, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 105, in __init__
    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.
```

Do I need to change specific paths I missed?

**Comment by pabloogc** [comment]
did you mount the models folder as volume?

**Comment by SjoerdBraaksma** [comment]
hey pabloogc!

I am quite new to building from a dockerfile, so I just ran it expecting it to grab the model from models during build. I understand I need to mount it in the dockerfile to a specific location?

ANy  help would be greatly appreciated, I would love to present your work to my team tomorrow!

**Comment by SjoerdBraaksma** [comment]
I think my download jsut got corrupted, I re-downloaded the model using the script and it works!

**Comment by pabloogc** [comment]
I can give you an example docker compose service as reference, note the environment variables, I am using a custom profile `docker` withe the model I want to use.

I suggest to go back to the documentation make sure you understand how profiles and llm modes work, most likely you missed something.

```
  private-gpt:
    build:
      context: ../privategpt
      dockerfile: Dockerfile.local
    volumes:
      - ../privategpt/local_data/:/home/worker/app/local_data
      - ../privategpt/models/:/home/worker/app/models
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local
```

**Comment by evansnguyen** [comment]
@SjoerdBraaksma 

Similar to @pabloogc answer

I added a docker-compose file to mount local_data, models
and create a port to expose the container 

check out the example here:
https://github.com/imartinez/privateGPT/pull/1277

**Comment by jochalek** [comment]
I also encountered this problem, and found a workaround.

First, the models have to be downloaded into the 'models' volume that will be mounted by the container. The containerized application does not download them for you. This must be done before running the container.

Second, the application being run by the container system user, 'worker', for some reason does not have write permissions. I changed the Dockerfile so that

```
RUN adduser --system worker
```
is now
```
RUN adduser worker
```

Then everything worked.

Is there a better way of doing this? Does running the application as a system user provide some security benefit that should be preserved?

**Comment by williamzebrowskI** [comment]
> @SjoerdBraaksma
> 
> Similar to @pabloogc answer
> 
> I added a docker-compose file to mount local_data, models and create a port to expose the container
> 
> check out the example here: #1277
> 
> after added docker-compose run:
> 
> ```shell
> docker compose up
> ```

Hi @evansnguyen - mind checking out my docker issue for a sec?  Followed your description, here's an issue I just created: 

https://github.com/imartinez/privateGPT/issues/1290

Thank you!

**Comment by M0E-lnx** [comment]
> I can give you an example docker compose service as reference, note the environment variables, I am using a custom profile `docker` withe the model I want to use.
> 
> I suggest to go back to the documentation make sure you understand how profiles and llm modes work, most likely you missed something.
> 
> ```
>   private-gpt:
>     build:
>       context: ../privategpt
>       dockerfile: Dockerfile.local
>     volumes:
>       - ../privategpt/local_data/:/home/worker/app/local_data
>       - ../privategpt/models/:/home/worker/app/models
>     environment:
>       PORT: 8080
>       PGPT_PROFILES: docker
>       PGPT_MODE: local
> ```

I have also encountered this issue, and tried this solution.
- Added the docker-compose file
- Ran ``docker compose build --no-cache``
- Ran ``docker compose up`` .. 

It still fails to run says cannot find the model and is asking for a URL to download.  Is there a way to pass the url through a variable maybe?

**Comment by KingPin** [comment]
same here the docker setup has no actual documentation on the docs page and as per this topic, no one can run it.

**Comment by rogercarvalhos** [comment]
I had to use the same model as in `settings-docker.yaml#10` (mistral-7b-instruct-v0.1.Q4_K_M.gguf)
`llm_hf_model_file: ${PGPT_HF_MODEL_FILE:mistral-7b-instruct-v0.1.Q4_K_M.gguf}`
Maybe it just needs to match the file name.
But then I got the error:
`PermissionError: [Errno 13] Permission denied: 'local_data/private_gpt'`
So, as a quick fix, I edited the Dockerfile to not use the user worker.

**Comment by cooltheobob** [comment]
Here is my solution.  It works for me
I moved all the contents which in dir (Mistral-7B-Instruct-v0.1-GGUF) to the privateGPT/models.
![image](https://github.com/imartinez/privateGPT/assets/145950499/8ce65541-e16a-44d1-ab18-dbd466f8e5a4)

**Notice you don't need to change any files such as docker-compose.yaml or setting-docker.yaml and so on**

It works
![image](https://github.com/imartinez/privateGPT/assets/145950499/6f46e218-449a-4b45-94ab-027ed2b164c1)
