### ISSUE TITLE
Delete API does not appear to work.

### ISSUE THREAD

**Issue by Kaotic3** [imartinez/privateGPT#1287]
According to this:

https://docs.privategpt.dev/api-reference/api-reference/ingestion/delete-ingested

The command is:

`curl -X DELETE --url "localhost:8001/v1/ingest/c6734dd6-dd5a-4138-b1ba-1a54a581f1d4"`

I updated the port because the documentation says 8000 but the actual port is 8001 now.

I receive back "Internal Server Error"

I can list:

`curl --url "localhost:8001/v1/ingest/list"`

```
{"object":"list","model":"private-gpt","data":[{"object":"ingest.document","doc_id":"c6734dd6-dd5a-4138-b1ba-1a54a581f1d4","doc_metadata":{"file_name":"xxxx March 2020.docx"}},{"object":"ingest.document","doc_id":"e9d438e4-5d6b-4e1e-a01a-9db606a8c49e","doc_metadata":{"file_name":"20230628 Sxxzz.docx"}}]}
```

So I know my doc_id is correct, and I don't get back a value error which is what you should receive should the document not exist.

This is the router py in case it helps, followed by the delete function just in case someone can spot an issue.

```
@ingest_router.delete("/ingest/{doc_id}", tags=["Ingestion"])
def delete_ingested(request: Request, doc_id: str) -> None:
    """Delete the specified ingested Document.

    The `doc_id` can be obtained from the `GET /ingest/list` endpoint.
    The document will be effectively deleted from your storage context.
    """
    service = request.state.injector.get(IngestService)
    service.delete(doc_id)
```

```
def delete(self, doc_id: str) -> None:
        """Delete an ingested document.

        :raises ValueError: if the document does not exist
        """
        logger.info(
            "Deleting the ingested document=%s in the doc and index store", doc_id
        )

        # Load the index with store_nodes_override=True to be able to delete them
        index = load_index_from_storage(self.storage_context, store_nodes_override=True)

        # Delete the document from the index
        index.delete_ref_doc(doc_id, delete_from_docstore=True)

        # Save the index
        self.storage_context.persist(persist_dir=local_data_path)
```

I am not such a python guru that I can tell you if anything is wrong with this - I can only say that the delete call seems to fail.

**Comment by lopagela** [comment]
@Kaotic3 is there any logs in the servers that comes with the internal server error?

**Comment by Kaotic3** [comment]
Yeah sorry should have included:

```
09:20:17.099 [INFO    ] llama_index.indices.loading - Loading all indices.
09:20:17.620 [INFO    ]            uvicorn.access - 127.0.0.1:54414 - "DELETE /v1/ingest/62b75eca-28c3-4d48-80a5-9ad47d78b36a HTTP/1.1" 500
09:20:17.620 [ERROR   ]             uvicorn.error - Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\privategpt\Lib\site-packages\llama_index\llms\utils.py", line 29, in resolve_llm
    validate_openai_api_key(llm.api_key)
  File "C:\ProgramData\miniconda3\envs\privategpt\Lib\site-packages\llama_index\llms\openai_utils.py", line 371, in validate_openai_api_key
    raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)
ValueError: No API key found for OpenAI.
```

I am using a local model so not sure why it would need this - also not really sure why it would need an OpenAI key to delete documents from the vector store?

**Comment by Raghavendhrareddy** [comment]
i have alreadt worked on deleting the ingested documents. if any one needs the code , ping mw on my whats app +91 9087195451 or raghava600@gmail.com

**Comment by Kaotic3** [comment]
I am querying a local LLM - so pretty sure that is set to local.  I am also able to list and ingest without issue.

I will look at what you have posted - but I would wonder why there would be a setting that would allow you to ingest and list - but not delete, for that function it would fail?

Does the delete function require something that ingest and list do not require?

**Comment by lee-jian-hui** [comment]
@Kaotic3 i had this yesterday but it resolved by itself, can you provide any info regarding your network? is it public or closed off network.

**Comment by Kaotic3** [comment]
It is on a local machine, there is no network - it is localhost.

I have not had a chance to test it since i posted, but will update when I get a chance.

**Comment by Dmitry-cybe** [comment]
I do this, but privateGPT displays for each "page_label", not for the entire file. Can you tell me how to fix it

**Comment by Dmitry-cybe** [comment]
"doc_id":"7fcdb4fe-f646-4a40-a387-cd9b90d00704","doc_metadata":{"page_label":"8","file_name":"1.pdf"}},{"object":"ingest.document","doc_id":"e2d99808-9411-4189-962a-8d12704ebf2d","doc_metadata":{"page_label":"4","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"a17610ad-d2de-45f1-be27-84501fc2c0cd","doc_metadata":{"page_label":"43","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"238c6c63-fa5b-405f-9c51-26a7c1a84a9f","doc_metadata":{"page_label":"137","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"edf06ea8-62c3-4a25-84ff-0b94e65ddf7e","doc_metadata":{"page_label":"7","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"b895c620-bbdb-4acc-a3ed-f7c72815576b","doc_metadata":{"page_label":"58","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"6b046ade-4000-4ca3-88c3-a46f75d71ceb","doc_metadata":{"page_label":"12","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"bb9e9341-3f6c-44d1-be92-3500160e920b","doc_metadata":{"page_label":"7","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"1ca97a40-3cf8-4ada-b66d-7af1ec8555be","doc_metadata":{"page_label":"26","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"63f9c113-d157-4875-be65-347f259bbe65","doc_metadata":{"page_label":"23","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"1671f694-9dcc-4eb5-98f4-b6d40847c0fb","doc_metadata":{"page_label":"102","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"e74f8dbe-ea58-4559-8f42-4112f90d0612","doc_metadata":{"page_label":"132","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"91d03a1e-5357-412c-8f69-9225dc2a0868","doc_metadata":{"page_label":"9","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"dca1379e-ac10-4e55-89df-73854428857e","doc_metadata":{"page_label":"6","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"6a2e1c68-09ec-4789-b52d-0378b3a95409","doc_metadata":{"page_label":"5","file_name":"1.pdf"}},{"object":"ingest.document","doc_id":"dcd9bc5b-b004-4918-869e-5aa62c7636d8","doc_metadata":{"page_label":"8","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"f30859be-83f9-4d7b-b20e-8a8b0dd117eb","doc_metadata":{"page_label":"74","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"3dfe6b06-8b61-4059-87b9-7d2da63a96ec","doc_metadata":{"page_label":"140","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"e7a17a1e-488f-4530-9385-c4b0221679ec","doc_metadata":{"page_label":"54","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"a4e566cb-a46b-4352-9b15-78d35cd9708e","doc_metadata":{"page_label":"153","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"c6160bcb-ab01-47e3-8514-a881be026660","doc_metadata":{"page_label":"157","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"a8ae98c8-398b-484d-bc74-693c1ddbd65e","doc_metadata":{"page_label":"65","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"d82476b1-12fd-4cde-b828-eebb3b39daa1","doc_metadata":{"page_label":"135","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"9c4050ec-95fb-49eb-af82-99ae5debc76b","doc_metadata":{"page_label":"27","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"83dd71b9-58cb-415f-936a-8098273b60c7","doc_metadata":{"page_label":"95","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"daab5018-260b-4482-b87c-1a230fbb9487","doc_metadata":{"page_label":"33","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"929d08b7-4de1-4f33-a932-4819b988fd86","doc_metadata":{"page_label":"116","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"d85ab490-d949-4710-9b40-255a596b0e12","doc_metadata":{"page_label":"71","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"b2eee645-2bd7-4c69-866e-12c27600b235","doc_metadata":{"page_label":"159","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"69f9f504-9f68-41e0-ac7e-a62dd79019b9","doc_metadata":{"page_label":"145","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"f95ad8e4-532f-4b39-8eca-6865cd2d2d30","doc_metadata":{"page_label":"10","file_name":"Chalcogenide_Thin_Films-Holographic_Media_for_Augm.pdf"}},{"object":"ingest.document","doc_id":"50989d8c-2cea-47d9-9f40-9259a570ecfb","doc_metadata":{"page_label":"9","file_name":"1.pdf"}},{"object":"ingest.document","doc_id":"d91d26bf-cb82-43f6-b2a7-29d583052dc3","doc_metadata":{"page_label":"30","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"75b40731-f70c-492e-886a-aaff1eb28ac0","doc_metadata":{"page_label":"87","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"0f5deb1b-2de3-4b58-9d48-443191ef01d4","doc_metadata":{"page_label":"38","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"8420b0b5-b63b-4c54-a5ee-51fd4d42763a","doc_metadata":{"page_label":"67","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"8d6a2b9f-df88-45f5-a40a-195ac3723b26","doc_metadata":{"page_label":"163","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"1df86f13-5869-42b0-bfef-fdd6ce4539b4","doc_metadata":{"page_label":"166","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"665b6efc-ba61-40e3-bbf7-1ecca98bb24e","doc_metadata":{"page_label":"3","file_name":"1.pdf"}},{"object":"ingest.document","doc_id":"b679bd73-20a7-4cc3-95c7-87c81920b80d","doc_metadata":{"page_label":"68","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"2cdd37d2-41e1-40da-a279-f99bdb207ba5","doc_metadata":{"page_label":"164","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"33f211b5-e42a-4e4c-b717-e07c470d1845","doc_metadata":{"page_label":"121","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"462c33ee-a3ab-4774-8b72-12e19148ae57","doc_metadata":{"page_label":"127","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"81a0c29f-e907-41e9-b1c8-f75527048d0c","doc_metadata":{"page_label":"114","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"cbf72a94-22c1-462d-b0ff-cf75db4ab82d","doc_metadata":{"page_label":"55","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"a5b1e7a2-2344-4336-83eb-279f8590cafb","doc_metadata":{"page_label":"111","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"1abf0179-3a29-4f7f-bf51-c648c9a53491","doc_metadata":{"page_label":"105","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"c3d8afb4-c1b1-45b7-946d-3f152cf96552","doc_metadata":{"page_label":"1","file_name":"1.pdf"}},{"object":"ingest.document","doc_id":"76700152-45cc-4305-94fa-a490813ca831","doc_metadata":{"page_label":"2","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"6745142f-6925-48c1-b0c3-e2cc4c8564a1","doc_metadata":{"page_label":"152","file_name":"1324549.pdf"}},{"object":"ingest.document","doc_id":"c6e2f85e-773e-4372-a11d-a23c9738ddb6","doc_metadata":{"page_label":"52","file_name":"1324549.pdf"}}]}
