### ISSUE TITLE
Issues running in Docker local

### ISSUE THREAD

**Issue by williamzebrowskI** [imartinez/privateGPT#1290]
I'm having some issues when it comes to running this in docker.  

Does it seem like I'm missing anything?

The UI is able to populate but when I try chatting via LLM Chat, I'm receiving errors shown below from the logs:

```
privategpt-private-gpt-1  | 19:02:45.455 [INFO    ]         private_gpt.ui.ui - Mounting the gradio UI, at path=/
privategpt-private-gpt-1  | 19:02:45.493 [INFO    ]             uvicorn.error - Started server process [7]
privategpt-private-gpt-1  | 19:02:45.493 [INFO    ]             uvicorn.error - Waiting for application startup.
privategpt-private-gpt-1  | 19:02:45.494 [INFO    ]             uvicorn.error - Application startup complete.
privategpt-private-gpt-1  | 19:02:45.495 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
privategpt-private-gpt-1  | 19:03:40.523 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "GET / HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:40.578 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "GET /info HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:40.581 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "GET /theme.css HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:40.673 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "POST /run/predict HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:45.106 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "POST /run/predict HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:45.108 [INFO    ]            uvicorn.access - 172.22.0.1:62518 - "POST /run/predict HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:45.121 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "POST /run/predict HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:45.140 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "GET /queue/join?fn_index=4&session_hash=05gr90e9nl1 HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:50.522 [INFO    ]            uvicorn.access - 172.22.0.1:62514 - "POST /queue/data HTTP/1.1" 500
privategpt-private-gpt-1  | 19:03:50.523 [ERROR   ]             uvicorn.error - Exception in ASGI application
privategpt-private-gpt-1  | Traceback (most recent call last):
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
privategpt-private-gpt-1  |     result = await app(  # type: ignore[func-returns-value]
privategpt-private-gpt-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
privategpt-private-gpt-1  |     return await self.app(scope, receive, send)
privategpt-private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
privategpt-private-gpt-1  |     await super().__call__(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
privategpt-private-gpt-1  |     await self.middleware_stack(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, _send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, sender)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
privategpt-private-gpt-1  |     raise e
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
privategpt-private-gpt-1  |     await route.handle(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
privategpt-private-gpt-1  |     await super().__call__(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
privategpt-private-gpt-1  |     await self.middleware_stack(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, _send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
privategpt-private-gpt-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, sender)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
privategpt-private-gpt-1  |     raise e
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
privategpt-private-gpt-1  |     await route.handle(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
privategpt-private-gpt-1  |     response = await func(request)
privategpt-private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
privategpt-private-gpt-1  |     raw_response = await run_endpoint_function(
privategpt-private-gpt-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
privategpt-private-gpt-1  |     return await dependant.call(**values)
privategpt-private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/gradio/routes.py", line 668, in queue_data
privategpt-private-gpt-1  |     blocks._queue.attach_data(body)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/gradio/queueing.py", line 161, in attach_data
privategpt-private-gpt-1  |     raise ValueError("Event not found", event_id)
privategpt-private-gpt-1  | ValueError: ('Event not found', 'c95938ee4977437b85876b33dfd5fce9')
privategpt-private-gpt-1  | 19:03:53.525 [INFO    ]            uvicorn.access - 172.22.0.1:57584 - "GET /queue/join?fn_index=4&session_hash=05gr90e9nl1 HTTP/1.1" 200
privategpt-private-gpt-1  | 19:03:58.899 [INFO    ]            uvicorn.access - 172.22.0.1:57584 - "POST /queue/data HTTP/1.1" 500
privategpt-private-gpt-1  | 19:03:58.900 [ERROR   ]             uvicorn.error - Exception in ASGI application
privategpt-private-gpt-1  | Traceback (most recent call last):
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
privategpt-private-gpt-1  |     result = await app(  # type: ignore[func-returns-value]
privategpt-private-gpt-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
privategpt-private-gpt-1  |     return await self.app(scope, receive, send)
privategpt-private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
privategpt-private-gpt-1  |     await super().__call__(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
privategpt-private-gpt-1  |     await self.middleware_stack(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, _send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, sender)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
privategpt-private-gpt-1  |     raise e
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
privategpt-private-gpt-1  |     await route.handle(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
privategpt-private-gpt-1  |     await super().__call__(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
privategpt-private-gpt-1  |     await self.middleware_stack(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, _send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
privategpt-private-gpt-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
privategpt-private-gpt-1  |     raise exc
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, sender)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
privategpt-private-gpt-1  |     raise e
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
privategpt-private-gpt-1  |     await route.handle(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
privategpt-private-gpt-1  |     await self.app(scope, receive, send)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
privategpt-private-gpt-1  |     response = await func(request)
privategpt-private-gpt-1  |                ^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
privategpt-private-gpt-1  |     raw_response = await run_endpoint_function(
privategpt-private-gpt-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
privategpt-private-gpt-1  |     return await dependant.call(**values)
privategpt-private-gpt-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/gradio/routes.py", line 668, in queue_data
privategpt-private-gpt-1  |     blocks._queue.attach_data(body)
privategpt-private-gpt-1  |   File "/home/worker/app/.venv/lib/python3.11/site-packages/gradio/queueing.py", line 161, in attach_data
privategpt-private-gpt-1  |     raise ValueError("Event not found", event_id)
privategpt-private-gpt-1  | ValueError: ('Event not found', '7c31eb907ede4880b0d3f9dca0e93a34')
```

I am using docker compose and I'll share the Dockerfile.local and docker-compose.yaml

### Dockerfile.local
```
### IMPORTANT, THIS IMAGE CAN ONLY BE RUN IN LINUX DOCKER
### You will run into a segfault in mac
FROM python:3.11.6-bookworm as base

# Install poetry
RUN pip install pipx
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"

# Dependencies to build llama-cpp
RUN apt-get update && apt-get install -y --fix-missing \
  libopenblas-dev \
  ninja-build \
  build-essential \
  pkg-config \
  wget

# https://python-poetry.org/docs/configuration/#virtualenvsin-project
ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/worker/app
COPY pyproject.toml poetry.lock ./

RUN poetry install --with local
RUN poetry install --with ui

FROM base as app

ENV PYTHONUNBUFFERED=1
ENV PORT=8080
EXPOSE 8080

# Prepare a non-root user
RUN adduser worker
# RUN adduser --system worker
WORKDIR /home/worker/app

# Copy the models folder
COPY --chown=worker models/ models/

RUN mkdir local_data; chown worker local_data
RUN mkdir models; chown worker models
COPY --chown=worker --from=dependencies /home/worker/app/.venv/ .venv
COPY --chown=worker private_gpt/ private_gpt
COPY --chown=worker docs/ docs
COPY --chown=worker *.yaml *.md ./

USER worker
ENTRYPOINT .venv/bin/python -m private_gpt
```

### docker-compose.yaml

```
services:
  private-gpt:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - 127.0.0.1:8080:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local

```

### model details from logs:

```
privategpt-private-gpt-1  | llm_load_print_meta: model type       = 7B
privategpt-private-gpt-1  | llm_load_print_meta: model ftype      = mostly Q4_K - Medium
privategpt-private-gpt-1  | llm_load_print_meta: model params     = 7.24 B
privategpt-private-gpt-1  | llm_load_print_meta: model size       = 4.07 GiB (4.83 BPW) 
privategpt-private-gpt-1  | llm_load_print_meta: general.name   = mistralai_mistral-7b-instruct-v0.1
```

**Comment by Raghavendhrareddy** [comment]
hi @williamzebrowskI , its workoing for me. if you need the process .please feel to ping me at whatsapp +91 9087195451

**Comment by williamzebrowskI** [comment]
> hi @williamzebrowskI , its workoing for me. if you need the process .please feel to ping me at whatsapp +91 9087195451

Hey @Raghavendhrareddy - Thanks.  Any chance you have the code sitting somewhere I can check out?  Appreciate any help you can provide.

**Comment by evansnguyen** [comment]
@williamzebrowskI 
It seems like your Docker image was built and run successfully,
The application runs and throws an error before rendering the UI. The root error might be from gradio lib. Try lock 
```
name = "gradio"
version = "3.50.2"
```
This version works for me.

If it's still not working, disable UI option to try using privateGPT with API.
