### ISSUE TITLE
Make Run throws error

### ISSUE THREAD

**Issue by jesperplantenervisma** [imartinez/privateGPT#1293]
Hi guys.

I'm trying to get PrivateGPT to run on my local Macbook Pro (intel based), but I'm stuck on the Make Run step, after following the installation instructions (which btw seems to be missing a few pieces, like you need CMAKE).

This is the log from Make Run:
 ```
make run
poetry run python -m private_gpt
10:10:29.185 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 102, in __init__
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/launcher.py", line 125, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/components/llm/llm_component.py", line 20, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 104, in __init__
    raise ImportError(
ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
make: *** [run] Error 1

```

It recommends running pip install llama-cpp-python which I tried. That gives the following output:
```
Requirement already satisfied: llama-cpp-python in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.2.19)
Requirement already satisfied: typing-extensions>=4.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (4.8.0)
Requirement already satisfied: numpy>=1.20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (1.26.2)
Requirement already satisfied: diskcache>=5.6.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (5.6.3)

```

I tried building the official llama.cpp package, which builds just fine.

**Comment by imartinez** [comment]
Try using the

ARCHFLAGS="-arch x86_64"

when installing requirements. 

In the previous version of privategpt most people got that problem solved by running

ARCHFLAGS="-arch x86_64" pip3 install -r requirements.txt

There is no requirements.txt usage anymore, but you can try to follow the same idea with poetry

**Comment by fajar-hida** [comment]
> use: $env:PGPT_PROFILES="local" poetry run python -m private_gpt

still got error..

**Comment by rmuhawieh** [comment]
> Hi guys.
> 
> I'm trying to get PrivateGPT to run on my local Macbook Pro (intel based), but I'm stuck on the Make Run step, after following the installation instructions (which btw seems to be missing a few pieces, like you need CMAKE).
> 
> This is the log from Make Run:
> 
> ```
> make run
> poetry run python -m private_gpt
> 10:10:29.185 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
> Traceback (most recent call last):
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
>    return self._context[key]
>           ~~~~~~~~~~~~~^^^^^
> KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
>    return self._context[key]
>           ~~~~~~~~~~~~~^^^^^
> KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
>    return self._context[key]
>           ~~~~~~~~~~~~~^^^^^
> KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 102, in __init__
>    from llama_cpp import Llama
> ModuleNotFoundError: No module named 'llama_cpp'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "<frozen runpy>", line 198, in _run_module_as_main
>  File "<frozen runpy>", line 88, in _run_code
>  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/__main__.py", line 5, in <module>
>    from private_gpt.main import app
>  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/main.py", line 11, in <module>
>    app = create_app(global_injector)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/launcher.py", line 125, in create_app
>    ui = root_injector.get(PrivateGptUi)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
>    provider_instance = scope_instance.get(interface, binding.provider)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
>    instance = self._get_instance(key, provider, self.injector)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
>    return provider.get(injector)
>           ^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
>    return injector.create_object(self._cls)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
>    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
>    dependencies = self.args_to_inject(
>                   ^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
>    instance: Any = self.get(interface)
>                    ^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
>    provider_instance = scope_instance.get(interface, binding.provider)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
>    instance = self._get_instance(key, provider, self.injector)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
>    return provider.get(injector)
>           ^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
>    return injector.create_object(self._cls)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
>    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
>    dependencies = self.args_to_inject(
>                   ^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
>    instance: Any = self.get(interface)
>                    ^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
>    provider_instance = scope_instance.get(interface, binding.provider)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
>    return function(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
>    instance = self._get_instance(key, provider, self.injector)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
>    return provider.get(injector)
>           ^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
>    return injector.create_object(self._cls)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
>    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
>    return callable(*full_args, **dependencies)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/jesperplantener/Documents/git/privateGPT/private_gpt/components/llm/llm_component.py", line 20, in __init__
>    self.llm = LlamaCPP(
>               ^^^^^^^^^
>  File "/Users/jesperplantener/Library/Caches/pypoetry/virtualenvs/private-gpt-4sFmnZIl-py3.11/lib/python3.11/site-packages/llama_index/llms/llama_cpp.py", line 104, in __init__
>    raise ImportError(
> ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
> make: *** [run] Error 1
> ```
> 
> It recommends running pip install llama-cpp-python which I tried. That gives the following output:
> 
> ```
> Requirement already satisfied: llama-cpp-python in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.2.19)
> Requirement already satisfied: typing-extensions>=4.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (4.8.0)
> Requirement already satisfied: numpy>=1.20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (1.26.2)
> Requirement already satisfied: diskcache>=5.6.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from llama-cpp-python) (5.6.3)
> ```
> 
> I tried building the official llama.cpp package, which builds just fine.

I'm having this same issue and was wondering what the solution was for this?

**Comment by thebrothbobo** [comment]
Have you found any solution ? I get the same issue
