### ISSUE TITLE
 Preparing metadata (pyproject.toml) ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Anitajahani** [imartinez/privateGPT#1314]
While installing" pip install google-colab", I faced this problem:
```
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

``` 
What should I do?

**Comment by gsanju-beacon** [comment]
@Anitajahani could you please help with the fix for this issue? What did you do to resolve this issue?

**Comment by RavishankarManishankar** [comment]
@Anitajahani Facing same issue here. Can you point to solution? Issue I am encountering has snippet below:

 Using cached pandas-0.19.2.tar.gz (9.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:39: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by adhavan18** [comment]
I have the same issue, while installing google-colab
 Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

any solutions guys? @Anitajahani

**Comment by stephanebdc** [comment]
(probably) Same Issue, on Macbook Pro 2019 intel i9

 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/XXXXXXX/fastsdcpu/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "XXXXXXXXX/fastsdcpu/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "XXXXXXXXX/fastsdcpu/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/XXXXXXXXX/fastsdcpu/env/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 629, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-install-63v0jghg/pyqt5_b4271bfde51449479a89efdf5d083a20/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 243, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/mg/kblk06s932737tkngrt07ygm0000gn/T/pip-build-env-adigqjpj/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 49, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
