### ISSUE TITLE
IndexError: index out of range in self error while bulk ingesting PDF or TXT documents

### ISSUE THREAD

**Issue by EEmlan** [imartinez/privateGPT#1337]
I'm getting the following Error when Bulk ingesting PDF or plain TXT Files.
I have many PDF and TXT Files. For some ingestion works but for some the following error is thrown.
There is no recognizable difference between the files where ingestion is working and to those where it is not working.

What could be the issue with some PDF/TXT files throwing that error?

```
]Traceback (most recent call last):
  File "E:\privateGPT\privateGPT010\privateGPT\scripts\ingest_folder.py", line 94, in <module>
    worker.ingest_folder(root_path)
  File "E:\privateGPT\privateGPT010\privateGPT\scripts\ingest_folder.py", line 37, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "E:\privateGPT\privateGPT010\privateGPT\scripts\ingest_folder.py", line 41, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "E:\privateGPT\privateGPT010\privateGPT\private_gpt\server\ingest\ingest_service.py", line 83, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\privateGPT\privateGPT010\privateGPT\private_gpt\components\ingest\ingest_component.py", line 129, in bulk_ingest
    saved_documents.extend(self._save_docs(documents))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\privateGPT\privateGPT010\privateGPT\private_gpt\components\ingest\ingest_component.py", line 136, in _save_docs
    self._index.insert(document, show_progress=True)
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\indices\base.py", line 191, in insert
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\ingestion\pipeline.py", line 70, in run_transformations
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\embeddings\base.py", line 334, in __call__
    embeddings = self.get_text_embedding_batch(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\embeddings\base.py", line 255, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\embeddings\huggingface.py", line 199, in _get_text_embeddings
    return self._embed(texts)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\llama_index\embeddings\huggingface.py", line 158, in _embed
    model_output = self._model(**encoded_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\transformers\models\xlm_roberta\modeling_xlm_roberta.py", line 830, in forward
    embedding_output = self.embeddings(
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\transformers\models\xlm_roberta\modeling_xlm_roberta.py", line 131, in forward
    position_embeddings = self.position_embeddings(position_ids)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "C:\Users\<Username>\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-dV1vPKPt-py3.11\Lib\site-packages\torch\nn\functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index out of range in self
Generating embeddings:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
make: *** [Makefile:52: ingest] Error 1
```

**Comment by lopagela** [comment]
And by general curiosity, how many files are you trying to bulk ingest at the same time?

**Comment by EEmlan** [comment]
Also it would be great if the output of the bulk ingestion would tell the name of the document where an error is thrown.
If you have a lot of files and in the middle of ingestion there is a error you don't know at which document this is happening.
