### ISSUE TITLE
Make Run errors

### ISSUE THREAD

**Issue by newmonte** [imartinez/privateGPT#1351]
Hello, after a huge amount of trial and error I got this installed in Win 10 but when I "make run" I get the following, I have tried to troubleshoot, (well google the errors) and was lead back here where there is a similar issue reported. Any help gratefully received.
Thank you.

I followed all instructions from here, only thing I did not do was pyenv, I was happy to run in the OS environment, is that an issue ?

Main issues encountered during install were poetry which was resolved by removal and reinstall and make for the llama.cpp, didnt realise in Windows had to be done through VS2022

`C:\Users\J***\privateGPT>poetry run python -m private_gpt
17:42:50.705 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
17:42:53.340 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
Traceback (most recent call last):
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 69, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\Programs\Python\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\J***\privateGPT\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "C:\Users\J***\privateGPT\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\privateGPT\private_gpt\launcher.py", line 125, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\privateGPT\private_gpt\components\llm\llm_component.py", line 31, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_index\llms\llama_cpp.py", line 102, in __init__
    from llama_cpp import Llama
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 82, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_cpp\llama_cpp.py", line 71, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\Users\J***\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-wYPNE1R7-py3.11\Lib\site-packages\llama_cpp\llama.dll': [WinError 193] %1 is not a valid Win32 application`

**Comment by lopagela** [comment]
Can you write here the full list of command or operation that you've made for your local installation please?

I guess you have read the installation guide from the documentation https://docs.privategpt.dev/installation, and that you also run the `set CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python`

**Comment by newmonte** [comment]
Thank you Lopagela,

I followed the installation guide from the documentation, the original issues I had with the install were not the fault of privateGPT, I had issues with cmake compiling until I called it through VS 2022, I also had initial issues with my poetry install, but now after running
set CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python

privateGPT is now working, I had seen this command but mistakenly assumed it was optional and only needed to run it if I wanted to use gpu.

Thankyou very much for your help.

**Comment by tfsJoe** [comment]
I was facing similar issues.

1. Is the installation guide up to date? I searched it for the line you suggested, @lopagela: `set CMAKE_ARGS='-DLLAMA_CUBLAS=on'; poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python` and came up empty.
2. Nevertheless, I did run that line in PowerShell and was able to get further in the process. But only because I discovered your comment on this issue. After that, I would execute `make run`, and it would fail with this message:
> File "C:\Users\me\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-TFCUF6yI-py3.11\Lib\site-packages\llama_index\llms\llama_cpp.py", line 119, in __init__
>    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.
make: *** [Makefile:36: run] Error 1

Whereas the installation guide says that at this point, I should be able to visit the UI in-browser.
3. Nevertheless, I continued with the next steps of running `poetry install --with local` and `poetry run python scripts/setup`. At that point, I was able to use the UI

So I think that the installation guide might be mistaken, have missing parts, be out of date, or at least not cover some configurations or environments.

**Comment by Anton-V-K** [comment]
I also tend to think that some steps are missing in the installation guide.
After finishing the chapter 'Install dependencies' I expected to get working UI with a mock LLM, but executing `poetry run python -m private_gpt` ends with the errors:
```
...
  File "C:\Temp\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Temp\privateGPT\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\privateGPT\private_gpt\components\llm\llm_component.py", line 28, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "C:\Temp\privateGPT\Lib\site-packages\llama_index\llms\llama_cpp.py", line 119, in __init__
    raise ValueError(
ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.
```
One step is certainly missing at this point - installing `llama-cpp-python`:
```
pip install llama-cpp-python==0.2.18
```
At this point the subdir `models` is usually empty, and it seems some model are expected to be found there.

According to the guide the models are downloaded later (with a command like `poetry run python scripts/setup`).

**Comment by airtonix** [comment]
same, followed the guide but with one exception: 

```shell
devbox global add pyenv
devbox global shell

... now follow rest of guide.
```

and i had to finally do this: 

```shell
poetry add uvicorn
```

otherwise i get 

```shell
privateGPT on git main is pkg v0.1.0 via py v3.11.4 via nix impure (nix-shell-env) took 14s 
> poetry run python -m private_gpt                                                                       
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/Store/Projects/Others/privateGPT/private_gpt/__main__.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

```

**Comment by airtonix** [comment]
woops, not the end of it `-_-` 

```shell
poetry run python -m private_gpt
17:10:52.923 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/Store/Projects/Others/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/mnt/Store/Projects/Others/privateGPT/private_gpt/main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Store/Projects/Others/privateGPT/private_gpt/launcher.py", line 48, in create_app
    from private_gpt.ui.ui import PrivateGptUi
  File "/mnt/Store/Projects/Others/privateGPT/private_gpt/ui/ui.py", line 8, in <module>
    import gradio as gr  # type: ignore
    ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'gradio'
make: *** [Makefile:36: run] Error 1
```

**Comment by Anton-V-K** [comment]
@airtonix , the modules like `gradio` or `uvicorn` are usually installed when executing `poetry install --with ui`. Anyway that's great you've solved your issue on your own! :)

The error like `ValueError: Provided model path does not exist. Please check the path or provide a model_url to download.` when running LLM in so called mock-mode ([reference](https://github.com/imartinez/privateGPT/issues/1351#issuecomment-1850510900)) usually means that `settings.yaml` is incorrect: by default it specifies `mode: local` for `llm` (which isn't set up unless you executed `poetry install --with local` earlier), so changing this setting to `mode: mock` can help you to resolve this issue, and ... reach another one when you open a browser and send any message to LLM:
```
Traceback (most recent call last):
  File "C:\Temp\privateGPT\Lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\privateGPT\Lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: Collection make_this_parameterizable_per_api_call not found
```
As proposed in https://github.com/imartinez/privateGPT/issues/1334#issuecomment-1847997849 you should tune your `settings.yaml` one more time - change `database: qdrant` (for `vectorstore`) with `database: chroma`, and execute `poetry install --extras chroma` ([documentation](https://docs.privategpt.dev/manual/storage/vector-stores#chroma-configuration)).
And this is what I finally get in mock-mode:
![image](https://github.com/imartinez/privateGPT/assets/20116984/cf424072-e2b2-4eca-9b87-2d7e25cf00f0)
I'm not sure it works as expected (I guess, it should echo messages), but at least it doesn't crash :)

**Comment by Henrique-Vicentini** [comment]
> same, followed the guide but with one exception:
> 
> ```shell
> devbox global add pyenv
> devbox global shell
> 
> ... now follow rest of guide.
> ```
> 
> and i had to finally do this:
> 
> ```shell
> poetry add uvicorn
> ```
> 
> otherwise i get
> 
> ```shell
> privateGPT on git main is pkg v0.1.0 via py v3.11.4 via nix impure (nix-shell-env) took 14s 
> > poetry run python -m private_gpt                                                                       
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/mnt/Store/Projects/Others/privateGPT/private_gpt/__main__.py", line 3, in <module>
>     import uvicorn
> ModuleNotFoundError: No module named 'uvicorn'
> ```

how did you solve it? i'm having this problem with the uvicorn. Use: poetry add uvicorn but the probem stills here

**Comment by matar3** [comment]
I hadn't solved it in that moment. But now some days ago a new version of privateGPT has been released, with new documentation, and it uses ollama instead of llama. Try with the new version. At most you could use a docker, instead. Join the discord group for updates.
