### ISSUE TITLE
I keep running into 'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by Error-418** [imartinez/privateGPT#1381]
I know for some files it has to do with an 0x0a5 in certain locations. Others have different multi-byte characters that are causing issues. Thing is, they're all downloaded as .txt files (I'm gathering with UTF-8 encoding). I'd figure these would be fairly simple to ingest, but this has me stumped.

Can anyone lend a hand on how to resolve these ingestion issues? Will this be a problem ingesting say, Japanese?

The specific error message I keep running into is:

Traceback (most recent call last):
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\scripts\ingest_folder.py", line 94, in <module>
    worker.ingest_folder(root_path)
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\scripts\ingest_folder.py", line 37, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\scripts\ingest_folder.py", line 41, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\private_gpt\server\ingest\ingest_service.py", line 83, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\private_gpt\components\ingest\ingest_component.py", line 126, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 30, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<myfolder>\Desktop\PrivateGPT_Local\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 48, in _load_file_to_documents
    return string_reader.load_data([file_data.read_text()])
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<myfolder>\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 25405: illegal multibyte sequence
make: *** [Makefile:52: ingest] Error 1

Where 0x93 varies between different UTF-8 encoded characters, and I'm not clear on how to get it to use UTF-8 for ingestion instead of GBK.

**Comment by Error-418** [comment]
I was able to cobble together a workaround for this using info from #1153 which I'll need to implement going forward since UTF-8 covers, I think, everything that I'll need to ingest going forward.

This could use a better solution than the bodge I made of adding `encoding='utf-8'` to ingest_helper.py.

Maybe run some error fails for different common encodings until the file ingests successfully?

**Comment by alpargun** [comment]
I suspect it is due to loading the weights .pkl file. Can you try loading in binary form?

```
with open(filename, 'rb') as f:
    datadict = pickle.load(f) 
```

Notice the 'rb' parameter to the open statement. An alternative can be setting the encoding as: `encoding='utf-8'`
