### ISSUE TITLE
Error reading file in ingest.py

### ISSUE THREAD

**Issue by shamresh** [imartinez/privateGPT#143]
I am seeing the following error when trying to process a single pdf file:

$ python ingest.py
Loading documents from source_documents
Traceback (most recent call last):
  File "C:\Work\Personal\private-gpt\privateGPT\ingest.py", line 62, in <module>
    main()
  File "C:\Work\Personal\private-gpt\privateGPT\ingest.py", line 46, in main
    documents = load_documents(source_directory)
  File "C:\Work\Personal\private-gpt\privateGPT\ingest.py", line 34, in load_documents
    return [load_single_document(file_path) for file_path in all_files]
  File "C:\Work\Personal\private-gpt\privateGPT\ingest.py", line 34, in <listcomp>
    return [load_single_document(file_path) for file_path in all_files]
  File "C:\Work\Personal\private-gpt\privateGPT\ingest.py", line 25, in load_single_document
    return loader.load()[0]
  File "C:\Python310\lib\site-packages\langchain\document_loaders\pdf.py", line 206, in load
    return list(self.lazy_load())
  File "C:\Python310\lib\site-packages\langchain\document_loaders\pdf.py", line 213, in lazy_load
    yield from self.parser.parse(blob)
  File "C:\Python310\lib\site-packages\langchain\document_loaders\base.py", line 87, in parse
    return list(self.lazy_parse(blob))
  File "C:\Python310\lib\site-packages\langchain\document_loaders\parsers\pdf.py", line 35, in lazy_parse
    text = extract_text(pdf_file_obj)
  File "C:\Python310\lib\site-packages\pdfminer\high_level.py", line 120, in extract_text
    with open(pdf_file, "rb") as fp, StringIO() as output_string:
TypeError: expected str, bytes or os.PathLike object, not BufferedReader

On windows.

**Comment by shamresh** [comment]
My mistake. When created an virutal environment, seems to be working.
