### ISSUE TITLE
llama_cpp Library Installation Issue During PrivateGPT Setup For Windows 11 When Running `make run`

### ISSUE THREAD

**Issue by Kiddo-Kris** [imartinez/privateGPT#1450]
`It would be appreciated if any explanation or instruction could be simple, I have very limited knowledge on programming and AI development.`

I’ve been meticulously following the setup instructions for PrivateGPT as outlined on their official documentation at https://docs.privategpt.dev/installation on Windows 11.

However, I’ve encountered an issue during the final step where I use the `make run` command to test the setup. Despite having installed the llama_cpp library as instructed(`pip install llama-cpp-python`), I’m still receiving error messages prompting me to install it. 

I’m at a loss as to how to proceed and would appreciate any guidance or suggestions.

Console output are as follows:

```
Using python3 (3.11.0)
04:11:37.980 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
04:11:39.391 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
Traceback (most recent call last):
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.llm.llm_component.LLMComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\llama_index\llms\llama_cpp.py", line 102, in __init__
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\AI\Application\Text\privateGPT-0.2.0\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "E:\AI\Application\Text\privateGPT-0.2.0\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Application\Text\privateGPT-0.2.0\private_gpt\launcher.py", line 50, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\Application\Text\privateGPT-0.2.0\private_gpt\components\llm\llm_component.py", line 28, in __init__
    self.llm = LlamaCPP(
               ^^^^^^^^^
  File "C:\Users\Xbox2\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-a_5Z5rxh-py3.11\Lib\site-packages\llama_index\llms\llama_cpp.py", line 104, in __init__
    raise ImportError(
ImportError: Could not import llama_cpp library.Please install llama_cpp with `pip install llama-cpp-python`.See the full installation guide for GPU support at `https://github.com/abetlen/llama-cpp-python`
make: *** [Makefile:36: run] Error 1
```

**Comment by amsheldon** [comment]
Make sure you have gcc and g++ installed. Also, newer versions of llama_index can cause issues, make sure to use version 0.9.3 if needed.

**Comment by amsheldon** [comment]
Try: pip install llama_index==0.9.3

Depending on how you installed the rest of the project you may need to use: python3.11 -m pip install llama-index==0.9.3
