### ISSUE TITLE
Exception: 'charmap' codec can't decode byte 0x8f in position 827: character maps to <undefined>

### ISSUE THREAD

**Issue by Threatintel-be** [imartinez/privateGPT#1484]
When I want to upload a docx or a pdf file I get:

2:02:42.520 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=local
12:02:43.908 [INFO    ] llama_index.indices.loading - Loading all indices.
12:02:44.015 [INFO    ]         private_gpt.ui.ui - Mounting the gradio UI, at path=/
12:02:44.059 [INFO    ]             uvicorn.error - Started server process [13276]
12:02:44.059 [INFO    ]             uvicorn.error - Waiting for application startup.
12:02:44.059 [INFO    ]             uvicorn.error - Application startup complete.
12:02:44.059 [INFO    ]             uvicorn.error - Uvicorn running on http://0.0.0.0:8001 (Press CTRL+C to quit)
12:02:58.092 [INFO    ]            uvicorn.access - 127.0.0.1:57147 - "POST /upload HTTP/1.1" 200
12:02:58.096 [INFO    ]            uvicorn.access - 127.0.0.1:57147 - "POST /queue/join HTTP/1.1" 200
12:02:58.100 [INFO    ]            uvicorn.access - 127.0.0.1:57147 - "GET /queue/data?session_hash=trj0fzx8qo HTTP/1.1" 200
12:02:58.147 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['2023.12.08 - besluiten digitribe - V1.PDF']
Traceback (most recent call last):
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\ui\ui.py", line 206, in _upload_file
    self._ingest_service.bulk_ingest([(str(path.name), path) for path in paths])
  File "C:\Users\bertc\code\privateGPT\private_gpt\server\ingest\ingest_service.py", line 92, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_component.py", line 127, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 30, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 48, in _load_file_to_documents
    return string_reader.load_data([file_data.read_text()])
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 827: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\ui\ui.py", line 206, in _upload_file
    self._ingest_service.bulk_ingest([(str(path.name), path) for path in paths])
  File "C:\Users\bertc\code\privateGPT\private_gpt\server\ingest\ingest_service.py", line 92, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_component.py", line 127, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 30, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\code\privateGPT\private_gpt\components\ingest\ingest_helper.py", line 48, in _load_file_to_documents
    return string_reader.load_data([file_data.read_text()])
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 827: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bertc\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-vGqeKW3c-py3.11\Lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: 'charmap' codec can't decode byte 0x8f in position 827: character maps to <undefined>

**Comment by ZederBreys** [comment]
I have the same problem

**Comment by ZederBreys** [comment]
I solved the problem [this way](https://github.com/imartinez/privateGPT/issues/1153#issuecomment-1826874539)

**Comment by kalle07** [comment]
may you take al look at GPT4all  ^^

or docfetcher (its old and java) but it works great ^^
