### ISSUE TITLE
Trying to upload a file when the embedding model "hkunlp/instructor-xl", "google/flan-t5-small"

### ISSUE THREAD

**Issue by juerware** [imartinez/privateGPT#1499]
When trying to upload a file using a embedding model like "hkunlp/instructor-xl" it launches a following error:
```shell
11:42:01.003 [INFO    ] private_gpt.server.ingest.ingest_service - Ingesting file_names=['Example_File.pdf']
Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 742.49it/s]
Generating embeddings:   0%|                                                                                                                                                                                        | 0/5 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/privateGPT/private_gpt/ui/ui.py", line 206, in _upload_file
    self._ingest_service.bulk_ingest([(str(path.name), path) for path in paths])
  File "/home/aramirez/privateGPT/private_gpt/server/ingest/ingest_service.py", line 92, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/privateGPT/private_gpt/components/ingest/ingest_component.py", line 130, in bulk_ingest
    saved_documents.extend(self._save_docs(documents))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/privateGPT/private_gpt/components/ingest/ingest_component.py", line 137, in _save_docs
    self._index.insert(document, show_progress=True)
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/indices/base.py", line 191, in insert
    nodes = run_transformations(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/ingestion/pipeline.py", line 70, in run_transformations
    nodes = transform(nodes, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 334, in __call__
    embeddings = self.get_text_embedding_batch(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/embeddings/base.py", line 255, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 200, in _get_text_embeddings
    return self._embed(texts)
           ^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 159, in _embed
    model_output = self._model(**encoded_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/transformers/models/t5/modeling_t5.py", line 1518, in forward
    decoder_outputs = self.decoder(
                      ^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/transformers/models/t5/modeling_t5.py", line 1011, in forward
    raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds")
ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds
``` 
Based on the standard configuration with only one change as follows:
```shell
diff --git a/settings.yaml b/settings.yaml
index b2ea0c6..9c4acb1 100644
--- a/settings.yaml
+++ b/settings.yaml
@@ -54,7 +54,8 @@ local:
   prompt_style: "llama2"
   llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
   llm_hf_model_file: mistral-7b-instruct-v0.2.Q4_K_M.gguf
-  embedding_hf_model_name: BAAI/bge-small-en-v1.5
+  #embedding_hf_model_name: BAAI/bge-small-en-v1.5
+  embedding_hf_model_name: hkunlp/instructor-xl
``` 
So far the question right now is how many embedding models are supported by this software?
Thanks in advance.

**Comment by juerware** [comment]
Same error for embedding model "google/flan-t5-small" according following:
```shell
Traceback (most recent call last):
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.embedding.embedding_component.EmbeddingComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 103, in __init__
    max_length = int(self._model.config.max_position_embeddings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aramirez/.cache/pypoetry/virtualenvs/private-gpt-2FxDpPAl-py3.11/lib/python3.11/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'T5Config' object has no attribute 'max_position_embeddings'
``` 
The code has to be prepared for default value in case that 'max_position_embeddings' parameter is not defined in config for embedding model, may be there is another config parameter to take into account in case 'max_position_embeddings' is not defined in embedding model config.
