### ISSUE TITLE
MultiGPU Ingestion

### ISSUE THREAD

**Issue by Luis-Sarabando** [imartinez/privateGPT#1521]
Currently it seems that this does not support mutli-gpu ingestion.

This is if you run it with the following config:
settings.yaml 

```
embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: parallel
```
Output:
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
Generating embeddings:   0%|                                                                                                                                                                                                    | 0/1 [00:18<?, ?it/s]
make: *** [Makefile:52: ingest] Error 1
```

If you run it in simple ingest mode it will load up only one GPU, so that's a workaround for people with multiple GPUs, while only using one.

```
embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: simple
```

Tried batch mode, another error:

```
embedding:
  # Should be matching the value above in most cases
  mode: local
  ingest_mode: batch
```
Output error:
```
Traceback (most recent call last):
  File "/home/ubuntu/privateGPT/.venv/lib/python3.11/site-packages/injector/__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 30, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 48, in _load_file_to_documents
    return string_reader.load_data([file_data.read_text()])
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 10: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/privateGPT/scripts/ingest_folder.py", line 94, in <module>
    worker.ingest_folder(root_path)
  File "/home/ubuntu/privateGPT/scripts/ingest_folder.py", line 37, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "/home/ubuntu/privateGPT/scripts/ingest_folder.py", line 41, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "/home/ubuntu/privateGPT/private_gpt/server/ingest/ingest_service.py", line 92, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/privateGPT/private_gpt/components/ingest/ingest_component.py", line 184, in bulk_ingest
    self._file_to_documents_work_pool.starmap(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 10: invalid continuation byte
make: *** [Makefile:52: ingest] Error 1
```

**Comment by Koesters** [comment]
This used to work. 

Add -DLLAMA_MPI=ON

I have two GPUS I compiled with 
CMAKE_ARGS='-DLLAMA_CUBLAS=on -DLLAMA_MPI=ON' poetry run pip install --force-reinstall --no-cache-dir llama-cpp-python

This way you can get it to not complain about two GPUs

But as soon as only some layers are outsourced to GPU, tested on two computers, garbage comes out. 
./private_gpt/components/llm/llm_component.py
model_kwargs={"n_gpu_layers": 30}, or less. 


This used to work too.

I have another system that has only one GPU it still produces garbage as soon as I am putting layers to the GPU.

**Comment by stratus-ss** [comment]
Recompiling didn't work for me unless I am doing something wrong

```
CUDACXX=/usr/local/cuda-12/bin/nvcc CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=native -DLLAMA_MPI=ON" poetry run pip install llama-cpp-python --no-cache-dir --force-reinstall --upgrade

```

But I still end up with the same error

```
Exception: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by SuperSonnix71** [comment]
I have been trying to fix the embedding component for couple of days  now and still getting the runtime error 
When using PyTorch dataparallel to use more than 1 GPU

RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
 
I have tried different approaches to ensure that the model is on the correct device before wrapping the model with DataParallel.

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = model.to(device)

wrapping with the dataparallel :

if torch.cuda.device_count() > 1:
    logger.info(f"Configuring model for multi-GPU use with {torch.cuda.device_count()} GPUs")
    model = torch.nn.DataParallel(model, device_ids=[0, 1])

 And still getting the same runtime error. Any idea on how to fix this?

**Comment by gittea-rpi** [comment]
While this is being worked on (thanks SuperSonnix71), is there a work around to force privateGPT to use only one of the available GPUs?

**Comment by SuperSonnix71** [comment]
We Thought we had it here but we might have a a issue since during some ingestions we got "Segmentation fault (core dumped)" I used PyTorch's DataParallel for simplicity but DataParallel seems to have some issues with the distribution. It works though but at some point you might hit it.

It's seems that PyTorch recommends using "DistributedDataParallel" rather than "DataParalle" so im reading up in their docs to try that.
still, you can use the one we wrote with DataParallel since now it works.

**Comment by SuperSonnix71** [comment]
Hey! i hope you all had a great weekend. can you please, try out  this code which uses "DistrubutedDataParallel" instead. i cannot test it out on my own. we took out the rest of GPU's since the service went offline when adding more than one GPU and im not at the office at the moment. 
https://gist.github.com/SuperSonnix71/bc144b7cc8ec396f851f171a4e6043c8

**Comment by bharrison-it** [comment]
@SuperSonnix71  most recent gist is working for me with multiGPU ingestion. For some reason the os vars aren't loading but modifying the rank and world_size directly works.

**Comment by SuperSonnix71** [comment]
Thanks for confirming @bharrison-it.  @imartinez I will set up a PR for this as soon I get a verification from Jeff as well.
PyTorch "DataParallel" is unstable. The best approach is to use "DistributedDataParalle"

**Comment by hyjin-asc** [comment]
@gittea-rpi

I'm having the same problem. First of all, I forced it as below and then implemented it to solve it.

```
export CUDA_VISIBLE_DEVICES=0
poetry run python -m private_gpt
```

**Comment by neofob** [comment]
@SuperSonnix71 : your [patch][0] works on my machine in [docker with GPU support and Mixtral 8x7B][1] for 2 Nvidia P40.

Thanks for awesome work!

[0]: https://gist.github.com/SuperSonnix71/e6ed139497f5176a68960db529e06163
[1]: https://github.com/neofob/privateGPT/tree/tp-docker

**Comment by jaluma** [comment]
@neofob could you open a PR with these changes?
It sounds really useful :)
