### ISSUE TITLE
make: *** [Makefile:36: run] Error 1

### ISSUE THREAD

**Issue by EXISTM4YH3M** [imartinez/privateGPT#1533]
Got to the end, when i try to use "make run" it does this:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dylan/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "/home/dylan/privateGPT/private_gpt/main.py", line 3, in <module>
    import llama_index
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/__init__.py", line 21, in <module>
    from llama_index.indices import (
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/indices/composability/__init__.py", line 4, in <module>
    from llama_index.indices.composability.graph import ComposableGraph
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/indices/composability/graph.py", line 5, in <module>
    from llama_index.core import BaseQueryEngine
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/core/__init__.py", line 2, in <module>
    from llama_index.core.base_retriever import BaseRetriever
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 7, in <module>
    from llama_index.service_context import ServiceContext
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/service_context.py", line 10, in <module>
    from llama_index.indices.prompt_helper import PromptHelper
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/indices/prompt_helper.py", line 20, in <module>
    from llama_index.node_parser.text.token import TokenTextSplitter
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/node_parser/__init__.py", line 12, in <module>
    from llama_index.node_parser.relational.hierarchical import (
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/node_parser/relational/__init__.py", line 2, in <module>
    from llama_index.node_parser.relational.unstructured_element import (
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/llama_index/node_parser/relational/unstructured_element.py", line 5, in <module>
    import pandas as pd
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat import (
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/home/dylan/.cache/pypoetry/virtualenvs/private-gpt-IPeNk3GF-py3.11/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
                            ^^^^^^^^^^^^^^
AttributeError: module 'pyarrow' has no attribute '__version__'
make: *** [Makefile:36: run] Error 1

**Comment by Rubiel1** [comment]
Oh I got another make error: 
``` File "/home/eric/.conda/envs/py311/lib/python3.11/site-packages/referencing/_core.py", line 115, in Specification
    ] = field(alias="anchors_in")
        ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: field() got an unexpected keyword argument 'alias'
make: *** [Makefile:36: run] Error 1
```
