### ISSUE TITLE
Poetry run problem on first installation

### ISSUE THREAD

**Issue by Hammerstale** [imartinez/privateGPT#1543]
Hi,

I tried to installe privateGPT on my W10 computer. I followed a tutorial on Youtube (https://www.youtube.com/watch?v=XFiof0V3nhA) but when I run the webui, I meet a problem.

I don't think it download the model I choose (Mistral) as it run in mere seconds. I don't have an error message so I don't know why I meet an error. Do you have any idea ? I tried installing localGPT to compare but I have old P6000 (compute 6.1) so it doesn't work with some dependancies, maybe it's the same here.

Below is the informations I received after launching my command:

(privategpt) F:\privateGPT>poetry run python scripts/setup
19:35:28.007 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Traceback (most recent call last):
  File "F:\privateGPT\scripts\setup", line 8, in <module>
    from private_gpt.paths import models_path, models_cache_path
  File "F:\privateGPT\private_gpt\paths.py", line 4, in <module>
    from private_gpt.settings.settings import settings
  File "F:\privateGPT\private_gpt\settings\settings.py", line 255, in <module>
    unsafe_settings = load_active_settings()
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\privateGPT\private_gpt\settings\settings_loader.py", line 53, in load_active_settings
    loaded_profiles = [
                      ^
  File "F:\privateGPT\private_gpt\settings\settings_loader.py", line 54, in <listcomp>
    load_settings_from_profile(profile) for profile in active_profiles
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\privateGPT\private_gpt\settings\settings_loader.py", line 44, in load_settings_from_profile
    config = load_yaml_with_envvars(f)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\privateGPT\private_gpt\settings\yaml.py", line 39, in load_yaml_with_envvars
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 251, in fetch_more_tokens
    return self.fetch_double()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 655, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 666, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 1151, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_spaces(double, start_mark))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\My_Ter\miniconda3\envs\privategpt\Lib\site-packages\yaml\scanner.py", line 1238, in scan_flow_scalar_spaces
    raise ScannerError("while scanning a quoted scalar", start_mark,
yaml.scanner.ScannerError: while scanning a quoted scalar
  in "F:\privateGPT\settings.yaml", line 55, column 19
found unexpected end of stream
  in "F:\privateGPT\settings.yaml", line 66, column 1

Thank you,
Hammerstale

**Comment by Hammerstale** [comment]
The problem came from a mistake in the link to the repository of the model. Hope it may help someone in the future.
