### ISSUE TITLE
Unable to query document in french

### ISSUE THREAD

**Issue by madagaga** [imartinez/privateGPT#1544]
Hi, 

I'm trying to use privateGTP in local mode.
Installation is OK i can query in english without any issues. 

For the french i have an error : 
```
Traceback (most recent call last):
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/madagaga/privateGPT/private_gpt/ui/ui.py", line 134, in _chat
    query_stream = self._chat_service.stream_chat(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/privateGPT/private_gpt/server/chat/chat_service.py", line 145, in stream_chat
    streaming_response = chat_engine.stream_chat(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 189, in stream_chat
    context_str_template, nodes = self._generate_context(message)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 103, in _generate_context
    nodes = self._retriever.retrieve(message)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 34, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 86, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 163, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/vector_stores/qdrant.py", line 354, in query
    response = self._client.search(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 340, in search
    return self._client.search(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/qdrant_local.py", line 164, in search
    return collection.search(
           ^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/local_collection.py", line 388, in search
    scores = calculate_distance(query_vector, vectors[: len(self.payload)], distance)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/distances.py", line 121, in calculate_distance
    return cosine_similarity(query, vectors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/distances.py", line 78, in cosine_similarity
    return np.dot(vectors, query)
           ^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (378,384) and (768,) not aligned: 384 (dim 1) != 768 (dim 0)
Traceback (most recent call last):
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/madagaga/privateGPT/private_gpt/ui/ui.py", line 134, in _chat
    query_stream = self._chat_service.stream_chat(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/privateGPT/private_gpt/server/chat/chat_service.py", line 145, in stream_chat
    streaming_response = chat_engine.stream_chat(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 189, in stream_chat
    context_str_template, nodes = self._generate_context(message)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 103, in _generate_context
    nodes = self._retriever.retrieve(message)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/core/base_retriever.py", line 34, in retrieve
    return self._retrieve(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 86, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 163, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/llama_index/vector_stores/qdrant.py", line 354, in query
    response = self._client.search(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 340, in search
    return self._client.search(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/qdrant_local.py", line 164, in search
    return collection.search(
           ^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/local_collection.py", line 388, in search
    scores = calculate_distance(query_vector, vectors[: len(self.payload)], distance)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/distances.py", line 121, in calculate_distance
    return cosine_similarity(query, vectors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/madagaga/.cache/pypoetry/virtualenvs/private-gpt-yNRikbQL-py3.11/lib/python3.11/site-packages/qdrant_client/local/distances.py", line 78, in cosine_similarity
    return np.dot(vectors, query)
           ^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (378,384) and (768,) not aligned: 384 (dim 1) != 768 (dim 0)
```

Here is my settings-fr.yaml (same as explained in 'recipes') 
```yaml
  local:
  llm_hf_repo_id: TheBloke/Vigogne-2-7B-Instruct-GGUF
  llm_hf_model_file: vigogne-2-7b-instruct.Q4_K_M.gguf
  embedding_hf_model_name: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
  prompt_style: "default"
  # prompt_style: "tag" # also works
  # The default system prompt is injected only when the `prompt_style` != default, and there are no system message in the discussion
  default_system_prompt: Vous êtes un assistant IA qui répond à la question posée à la fin en utilisant le contexte suivant. Si vous ne connaissez pas la réponse, dites simplement que vous ne savez pas, n'essayez pas d'inventer une réponse. Veuillez répondre exclusivement en français.
```

If someone have a working instance for french documents it could be helpful.
Thanks

**Comment by sjssmits** [comment]
Changing the embeddings model to one different dimensions does not work currently for me as well.
