### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by well-it-wasnt-me** [imartinez/privateGPT#155]
Hi,  running `ingest.py` or `privateGPT.py` i receive the following error (and yes the pip install -r requirements.txt gave no error):

```bash
Traceback (most recent call last):
  File "/home/antonio/Tools/privateGPT/ingest.py", line 6, in <module>
    from langchain.document_loaders import TextLoader, PDFMinerLoader, CSVLoader
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/tools/__init__.py", line 13, in <module>
    from langchain.tools.gmail import (
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/tools/gmail/__init__.py", line 3, in <module>
    from langchain.tools.gmail.create_draft import GmailCreateDraft
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/tools/gmail/create_draft.py", line 11, in <module>
    from langchain.tools.gmail.base import GmailBaseTool
  File "/home/antonio/.local/lib/python3.10/site-packages/langchain/tools/gmail/base.py", line 17, in <module>
    from googleapiclient.discovery import Resource
  File "/usr/lib/python3/dist-packages/googleapiclient/discovery.py", line 56, in <module>
    from googleapiclient import _auth
  File "/usr/lib/python3/dist-packages/googleapiclient/_auth.py", line 33, in <module>
    import oauth2client.client
  File "/usr/lib/python3/dist-packages/oauth2client/client.py", line 45, in <module>
    from oauth2client import crypt
  File "/usr/lib/python3/dist-packages/oauth2client/crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "/usr/lib/python3/dist-packages/oauth2client/_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

```

**Comment by pazDontExist** [comment]
Downgrading Cryptography did the trick
`pip install cryptography==38.0.4`

Now i have another problem....

`AttributeError: 'Llama' object has no attribute 'ctx'`

**Comment by pazDontExist** [comment]
reading better....i mispelled the folder "models".
now it works

**Comment by AlvinKimata** [comment]
> 

Thanks a lot! It worked for me.
