### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by zdavatz** [imartinez/privateGPT#1566]
Great tool! Thank you!

I am currently getting this error.

```
Traceback (most recent call last):
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/.venv/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/ui/ui.py", line 122, in _chat
    all_messages = [*build_history(), new_message]
                     ^^^^^^^^^^^^^^^
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/ui/ui.py", line 104, in build_history
    *[
     ^
  File "/Users/zdavatz/Documents/software/privateGPT/private_gpt/ui/ui.py", line 109, in <listcomp>
    content=interaction[1].split(SOURCES_SEPARATOR)[0],
            ^^^^^^^^^^^^^^^^^^^^
```

**Comment by zdavatz** [comment]
restarting `poetry run python3.11 -m private_gpt` helped.

**Comment by vanboom** [comment]
This error occurs when using the Query Docs feature with no documents ingested.  After the error occurs the first time, switching back to LLM Chat does not resolve the error -- the model needs to be restarted.  Suggest reopening this issue to resolve the initial error  -- the case of no documents should be handled more gracefully without requiring the model to be restarted.

**Comment by ShahResearchGroup** [comment]
The error also occurs if a query for the ingested document is canceled.

**Comment by gobetti** [comment]
@imartinez please see @vanboom 's feedback above. Thank you! 🙏
