### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by stefkos** [imartinez/privateGPT#1574]
I tried to add local documents using:
make ingest /Users/sk/Privat/Archiv -- --watch --log-file ./file.log

Parsing nodes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 231.79it/s]
Generating embeddings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 61/61 [00:00<00:00, 65.41it/s]
Generating embeddings: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/sk/privateGPT/scripts/ingest_folder.py", line 94, in <module>
    worker.ingest_folder(root_path)
  File "/Users/sk/privateGPT/scripts/ingest_folder.py", line 37, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "/Users/sk/privateGPT/scripts/ingest_folder.py", line 41, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "/Users/sk/privateGPT/private_gpt/server/ingest/ingest_service.py", line 92, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sk/privateGPT/private_gpt/components/ingest/ingest_component.py", line 127, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sk/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 30, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sk/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 48, in _load_file_to_documents
    return string_reader.load_data([file_data.read_text()])
                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte
make: *** [ingest] Error 1

===

Any idea what´s wrong?

**Comment by veniodev** [comment]
I had the same issue and it was due to `.ico` in my case.

**Comment by jbferguson75** [comment]
Any Unicode characters cause this error.  I had to do a search and replace to make sure all my characters were just simple ASCII.  It would be nice if the document ingestion supported Unicode characters.

**Comment by gonzariosm** [comment]
I had the same issue, and was the `.DS_Store` file.

you can try the following command to delete all your `.DS_Store` files in the folder.

```bash
cd /Users/sk/Privat/Archiv
find . -type f -name ".DS_Store" -exec rm -v {} \
```

**Comment by stefkos** [comment]
> I had the same issue, and was the `.DS_Store` file.
> 
> you can try the following command to delete all your `.DS_Store` files in the folder.
> 
> ```shell
> cd /Users/sk/Privat/Archiv
> ```
> 
>  ```shell
> find . -type f -name ".DS_Store" -exec rm -v {} \
> ```

thx for this hint

**Comment by abhishekbhakat** [comment]
I changed the `file_data.read_text()` to:

```python
return string_reader.load_data([file_data.read_text("utf-8", errors="replace").replace("\x00", "\uFFFD")])
```

File "/Users/sk/privateGPT/private_gpt/components/ingest/ingest_helper.py", in _load_file_to_documents
