### ISSUE TITLE
 [Errno 2] No such file or directory: .... avatar-bot.ico

### ISSUE THREAD

**Issue by Dariusz1989** [imartinez/privateGPT#1575]
Hey
Fresh install & run >

```
16:47:28.129 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=local
16:47:32.606 [INFO    ] llama_index.indices.loading - Loading all indices.
Traceback (most recent call last):
  File "S:\01_Code\AI\privateGPT\privateGPT\private_gpt\ui\ui.py", line 281, in _build_ui_blocks
    chatbot=gr.Chatbot(
            ^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\component_meta.py", line 155, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\components\chatbot.py", line 134, in __init__
    processing_utils.move_resource_to_block_cache(avatar_images[1], self),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\blocks.py", line 257, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
               ^^^^^^^^^^^^^^^^^^^^
  File "S:\01_Code\AI\privateGPT\venvPrivateGPT\Lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'S:\\01_Code\\AI\\privateGPT\\privateGPT\\private_gpt\\private_gpt\\ui\\avatar-bot.ico'
```

Something seems broken?

**Comment by AshutoshUpadhya** [comment]
I just updated to new branch and got the same issue. I am yet to get familiar with entire arch but so far it seems one solution could be  to add the windows path to relative project path of the avatar-bot.ico file.

**Comment by AshutoshUpadhya** [comment]
I am also having the same issue. Took fresh pull and it gave this path error. While debugging on my windows machine I found:
1. The issue occurs while calculating Path.resolve(). It is providing an extra 'privategpt' in the path like F:\my_projects\privateGPT\private_gpt\private_gpt\ui\avatar-bot.ico instead of
 F:\my_projects\privateGPT\private_gpt\ui\avatar-bot.ico.

I thought this could be a bug in Path module but on running on command prompt for a sample, its giving correct output. 
Pls see below
![image](https://github.com/imartinez/privateGPT/assets/34449255/938c8ee1-00de-496d-ab32-afe273d80a26)



The path.resolve() method did

**Comment by AshutoshUpadhya** [comment]
I resolved it.
You may update line 28 of ui.py to 
AVATAR_BOT = Path(__file__).parent.relative_to(Path(__file__).parents[1]) / "avatar-bot.ico"
![image](https://github.com/imartinez/privateGPT/assets/34449255/fb22b819-f61d-4d41-bcbb-c6fc757f6f0e)

The issue was to remove additional folder name as it was an i ssue while resolving path using Pathlib through gradle blocks.
so, I am sending just the file'sparent and so it working for me
@imartinez : Do you find this good for a PR? so will raise one.

**Comment by Rubiel1** [comment]
I have the same problem in linux. ```FileNotFoundError: [Errno 2] No such file or directory 'private_gpt/ui/avatar-bot.ico'```
