### ISSUE TITLE
AttributeError: 'LLMComponent' object has no attribute 'llm'

### ISSUE THREAD

**Issue by hamnarif** [imartinez/privateGPT#1626]
I am trying to run command "make run" and it's giving me this error even the llm attribute is present in LLMComponent
(privateGPT) C:\llmai\privateGPT\privateGPT>poetry run python -m private_gpt
16:57:10.685 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
16:57:15.708 [INFO    ] private_gpt.components.llm.llm_component - Initializing the LLM in mode=local
16:57:16.388 [INFO    ] private_gpt.components.embedding.embedding_component - Initializing the embedding model in mode=local
Traceback (most recent call last):
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.ui.ui.PrivateGptUi'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\llmai\privateGPT\privateGPT\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "C:\llmai\privateGPT\privateGPT\private_gpt\main.py", line 11, in <module>
    app = create_app(global_injector)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llmai\privateGPT\privateGPT\private_gpt\launcher.py", line 50, in create_app
    ui = root_injector.get(PrivateGptUi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 811, in _get_instance       
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object       
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject     
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 811, in _get_instance       
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 998, in create_object       
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\cvi\anaconda3\envs\privateGPT\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\llmai\privateGPT\privateGPT\private_gpt\server\ingest\ingest_service.py", line 44, in __init__
    llm=self.llm_service.llm,
        ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LLMComponent' object has no attribute 'llm'

**Comment by makan1869** [comment]
have you updated llama_index or llama_cpp_python versions!? I experienced it a while ago because of an update in the project.toml

**Comment by hamnarif** [comment]
It worked thank you
