### ISSUE TITLE
Exception: async generator raised StopAsyncIteration when asking a question

### ISSUE THREAD

**Issue by rmuhawieh** [imartinez/privateGPT#1689]
Traceback (most recent call last):
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await [anyio.to](http://anyio.to/)_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 498, in run_sync_iterator_async
    raise StopAsyncIteration() from None
StopAsyncIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
RuntimeError: async generator raised StopAsyncIteration
Traceback (most recent call last):
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await [anyio.to](http://anyio.to/)_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 498, in run_sync_iterator_async
    raise StopAsyncIteration() from None
StopAsyncIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
RuntimeError: async generator raised StopAsyncIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: async generator raised StopAsyncIteration

**Comment by rmuhawieh** [comment]
> Traceback (most recent call last): File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn first_response = await async_iteration(generator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in **anext** return await [anyio.to](http://anyio.to/)_thread.run_sync( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future ^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 498, in run_sync_iterator_async raise StopAsyncIteration() from None StopAsyncIteration The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction output = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function prediction = await utils.async_iteration(iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper async for response in f(*args, **kwargs): RuntimeError: async generator raised StopAsyncIteration Traceback (most recent call last): File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/chat_interface.py", line 481, in _stream_fn first_response = await async_iteration(generator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 512, in **anext** return await [anyio.to](http://anyio.to/)_thread.run_sync( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread return await future ^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run result = context.run(func, *args) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 498, in run_sync_iterator_async raise StopAsyncIteration() from None StopAsyncIteration The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 459, in call_prediction output = await route_utils.call_process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1533, in process_api result = await self.call_function( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1163, in call_function prediction = await utils.async_iteration(iterator) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration return await iterator.**anext**() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 640, in asyncgen_wrapper async for response in f(*args, **kwargs): RuntimeError: async generator raised StopAsyncIteration The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 497, in process_events response = await self.call_prediction(awake_events, batch) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/rmuhawieh/.cache/pypoetry/virtualenvs/private-gpt-5J7_-Iqs-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 468, in call_prediction raise Exception(str(error) if show_error else None) from error Exception: async generator raised StopAsyncIteration

It was just working, I'm not sure what changed

**Comment by dbzoo** [comment]
I ran into this. This is what worked for me.  These commands are executed from the private_gpt clone dir.
**Delete the virtual env.**
$ poetry env list
private-gpt-XXXXX
$ poetry env remove private-gpt-XXXXX
Make sure you exit the poetry environment and start another shell and repopulate the environment again.
**Install new virtual env**
$ poetry shell
$ poetry install

**Comment by rmuhawieh** [comment]
> I ran into this. This is what worked for me. These commands are executed from the private_gpt clone dir. **Delete the virtual env.** $ poetry env list private-gpt-XXXXX $ poetry env remove private-gpt-XXXXX Make sure you exit the poetry environment and start another shell and repopulate the environment again. **Install new virtual env** $ poetry shell $ poetry install

In the step where you say repopulate the environment again, is that where you rerun the commands poetry install --with ui,local and poetry run python scripts/setup? Or is that done after the installation of the new virtual environment? I'm only asking because I don't remember install a virtual environment in following the privateGPT installation instructions but I see that there is one when I use poetry env list

**Comment by dbzoo** [comment]
The act of `poetry install` will [create a virtual environment](https://python-poetry.org/docs/configuration/#:~:text=If%20not%20set%20explicitly%2C%20poetry,root%20directory%20of%20the%20project)  Alternatively, you can clear the poetry cache.  I ran into poetry problems doing this.  After the virtenv is gone go through the setup again `--with` etc..

**Comment by rmuhawieh** [comment]
> The act of `poetry install` will [create a virtual environment](https://python-poetry.org/docs/configuration/#:~:text=If%20not%20set%20explicitly%2C%20poetry,root%20directory%20of%20the%20project) Alternatively, you can clear the poetry cache. I ran into poetry problems doing this. After the virtenv is gone go through the setup again `--with` etc..

Ah yes okay so just so I understand completely, this should work then right?

1. poetry env list
2. poetry env remove private-gpt-XXXXX
3. poetry shell
4. pyenv local 3.11
5. poetry install --with ui,local
6. poetry run python scripts/setup
