### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.core.callbacks'

### ISSUE THREAD

**Issue by johnhula** [imartinez/privateGPT#1710]
I updated the code and now there is an error message. Can anyone help me
Traceback (most recent call last):
File<frozen runpy>, line 198, in _run_module.as_main
File "<frozen run>", line 88, in _run_code
File "D: \ software \ privateept \ privateGPT \ privateugpt \ _main__. py", line 5, in<module>
From private_gpt.main import app
File "D: \ software \ privateept \ privateGPT \ privateugpt \ main. py", line 4, in<module>
From private_gpt.launcher import createapp
File "D: \ software \ privateept \ privateGPT \ privateugpt \ launcher. py", line 8, in<module>
From llama_index.core. callbacks import CallbackManager
ModuleNotFoundError: No module named 'llama_index. core. callbacks'
Make: * * * [Makefile: 36: run] Error 1

**Comment by seifmohamed1w** [comment]
same issue

**Comment by xuaaka** [comment]
Same issue for me as well.

**Comment by Siiriion** [comment]
Hi, same issue for me (Mac Silicon).

**Comment by UserMK99** [comment]
i solved that part with pip install llama_index, but now i have a new error
