### ISSUE TITLE
Chroma settings causing error when using privategpt.py

### ISSUE THREAD

**Issue by Eldiablozzz** [imartinez/privateGPT#172]
This is the error i get when i use python privategpt.py. (my ingest.py worked fine for me it took some time but did finish without any errors, but privategpt.py does not work)
Traceback (most recent call last):
  File "E:\pvt\privateGPT\privategpt.py", line 18, in <module>
    from constants import CHROMA_SETTINGS
  File "E:\pvt\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by shuxiangzhang** [comment]
I experienced the same issue.

**Comment by nickali** [comment]
Does the .env file exist?

**Comment by shuxiangzhang** [comment]
@nickali Thanks for the reply. It turns out I did not download the required models and place them in the **models** folder cause I initially thought they came with the GitHub zip file.  Creating the **models** folder and placing the downloaded LLMs for embedding and generation in the folder solves the problem for me.

**Comment by Eldiablozzz** [comment]
Yes, .env file is double checked. Both models are in model folder and their
names also checked.

**Comment by donvito** [comment]
Encountering the same issue

`Traceback (most recent call last):
  File "/ingest.py", line 24, in <module>
    from constants import CHROMA_SETTINGS
  File "/constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)`

@Eldiablozzz where did you download the model that worked? Which model was corrupted?

**Comment by sjssmits** [comment]
Same error here after 2nd query.

**Comment by Nemcade** [comment]
Also having the same issue. I have the .env file and the model set in the models folder but the problem persists.

E:\Programs\PrivateGPT\privateGPT>python privateGPT.py
Traceback (most recent call last):
  File "E:\Programs\PrivateGPT\privateGPT\privateGPT.py", line 20, in <module>
    from constants import CHROMA_SETTINGS
  File "E:\Programs\PrivateGPT\privateGPT\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Nemcade** [comment]
> @Nemcade that errors means your `.env` file is not setup correctly.

Wonder what's wrong with it. I renamed it to .env and it looks like this. 

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000

**Comment by PulpCattel** [comment]
The content seems correct. Make sure the file name is correct and that it's in the right folder.
