### ISSUE TITLE
Error while trying to ingest PowerPoint files

### ISSUE THREAD

**Issue by zerodev-exe** [imartinez/privateGPT#1722]
I'm on endeavourOS btw

This happens when I try to ingest some PowerPoint files.

Error code :
```Traceback (most recent call last):
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/llama_index/readers/file/slides/base.py", line 27, in __init__
    import torch  # noqa
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/gradio/route_utils.py", line 235, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1627, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/gradio/blocks.py", line 1173, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/gradio/utils.py", line 690, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/zero/Developer/privateGPT/private_gpt/ui/ui.py", line 252, in _upload_file
    self._ingest_service.bulk_ingest([(str(path.name), path) for path in paths])
  File "/home/zero/Developer/privateGPT/private_gpt/server/ingest/ingest_service.py", line 84, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/Developer/privateGPT/private_gpt/components/ingest/ingest_component.py", line 130, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/Developer/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 74, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zero/Developer/privateGPT/private_gpt/components/ingest/ingest_helper.py", line 95, in _load_file_to_documents
    return reader_cls().load_data(file_data)
           ^^^^^^^^^^^^
  File "/home/zero/.cache/pypoetry/virtualenvs/private-gpt-dxfqfqnq-py3.11/lib/python3.11/site-packages/llama_index/readers/file/slides/base.py", line 36, in __init__
    raise ImportError(
ImportError: Please install extra dependencies that are required for the PptxReader: `pip install torch transformers python-pptx Pillow`
09:29:56.187 [INFO    ]            uvicorn.access - 127.0.0.1:50118 - "GET /queue/data?session_hash=g8oleucobj9 HTTP/1.1" 200```

I think this error is due to the fact that I didn't download the dependencies for the poetry cli tool, but I have no clue how to use it. 
Can someone pls give me some commands that will fix this.

**Comment by akhvedelidze** [comment]
Hi

Did you try to install the library for ppt transformation 

pip install torch transformers python-pptx Pillow

**Comment by zerodev-exe** [comment]
> Hi
> 
> Did you try to install the library for ppt transformation
> 
> pip install torch transformers python-pptx Pillow

Yes I did it was the first thing I did but it still gives me the exact same error

**Comment by matbgn** [comment]
I got same error and can double that running 

```
pip install torch transformers python-pptx Pillow
```

Did not solve the problem.

**Comment by d-tdhillon** [comment]
@zerodev-exe any success with this ? I am also getting the same error in-spite of running 
`pip install torch transformers python-pptx Pillow`

**Comment by zerodev-exe** [comment]
> @zerodev-exe any success with this ? I am also getting the same error in-spite of running `pip install torch transformers python-pptx Pillow`
@d-tdhillon sorry I haven't. There are alternatives now, though.

**Comment by alekseevpg** [comment]
> > @zerodev-exe any success with this ? I am also getting the same error in-spite of running `pip install torch transformers python-pptx Pillow`
> > @d-tdhillon sorry I haven't. There are alternatives now, though.

What are the alternatives?

**Comment by zerodev-exe** [comment]
> > > @zerodev-exe any success with this ? I am also getting the same error in-spite of running `pip install torch transformers python-pptx Pillow`
> > > @d-tdhillon sorry I haven't. There are alternatives now, though.
> 
> What are the alternatives?

There's Open Web UI, which is fantastic (it's what I use now), which you should be able to download with the following command if you have docker and ollama installed :

## [Ollama download](https://ollama.com/download)

## Open Web UI download (with docker)
```
docker run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```

**Comment by yaziciali** [comment]
I have same issue,
I have installed libraries, but gave same error again.
Is there any other solution without docker?

Generating embeddings: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/private-gpt-gFR-EDxu-py3.11/lib/python3.11/site-packages/llama_index/readers/file/slides/base.py", line 28, in __init__
    import torch  # noqa
    ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 122, in <module>
    worker.ingest_folder(root_path, args.ignored)
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 58, in ingest_folder
    self._ingest_all(self._files_under_root_folder)
  File "/Users/user/AI/private-gpt/scripts/ingest_folder.py", line 62, in _ingest_all
    self.ingest_service.bulk_ingest([(str(p.name), p) for p in files_to_ingest])
  File "/Users/user/AI/private-gpt/private_gpt/server/ingest/ingest_service.py", line 87, in bulk_ingest
    documents = self.ingest_component.bulk_ingest(files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_component.py", line 132, in bulk_ingest
    documents = IngestionHelper.transform_file_into_documents(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_helper.py", line 74, in transform_file_into_documents
    documents = IngestionHelper._load_file_to_documents(file_name, file_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/AI/private-gpt/private_gpt/components/ingest/ingest_helper.py", line 100, in _load_file_to_documents
    documents = reader_cls().load_data(file_data)
                ^^^^^^^^^^^^
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/private-gpt-gFR-EDxu-py3.11/lib/python3.11/site-packages/llama_index/readers/file/slides/base.py", line 37, in __init__
    raise ImportError(
ImportError: Please install extra dependencies that are required for the PptxReader: `pip install torch transformers python-pptx Pillow`
make: *** [ingest] Error 1
user@ITMAC private-gpt % pip install torch transformers python-pptx Pillow
Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.5.1)
Requirement already satisfied: transformers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.46.3)
Requirement already satisfied: python-pptx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (9.5.0)
Requirement already satisfied: filelock in /Users/user/Library/Python/3.11/lib/python/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (4.66.1)
Requirement already satisfied: XlsxWriter>=0.5.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-pptx) (3.2.0)
Requirement already satisfied: lxml>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-pptx) (4.9.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2024.7.4)
user@ITMAC private-gpt % pip3.11 install torch transformers python-pptx Pillow 
Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.5.1)
Requirement already satisfied: transformers in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.46.3)
Requirement already satisfied: python-pptx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.0.2)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (9.5.0)
Requirement already satisfied: filelock in /Users/user/Library/Python/3.11/lib/python/site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (2024.10.0)
Requirement already satisfied: sympy==1.13.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (2.31.0)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (4.66.1)
Requirement already satisfied: XlsxWriter>=0.5.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-pptx) (3.2.0)
Requirement already satisfied: lxml>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-pptx) (4.9.3)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2024.7.4)

**Comment by matbgn** [comment]
😅 Not planning to fix a bug?! OK this is the first time I see that.

**Comment by alekseevpg** [comment]
no bug - no problem

**Comment by AlfonsoLozana** [comment]
We'll be doing a major update to the repository, so we're closing all current issues that no longer apply to the new version,
