### ISSUE TITLE
Error in Model Download and Tokenizer Fetching During Setup Script Execution

### ISSUE THREAD

**Issue by nejcar20** [imartinez/privateGPT#1724]
### Environment
Operating System: Macbook Pro M1
Python Version: 3.11

Description
I'm encountering an issue when running the setup script for my project. The script is supposed to download an embedding model and an LLM model from Hugging Face, followed by their respective tokenizers. While the script successfully downloads the embedding and LLM models, it fails when attempting to download the tokenizer with a 404 Client Error.

### Steps to Reproduce
Run `poetry run python scripts/setup`
Embedding model (BAAI/bge-small-en-v1.5) and the LLM model (mistral-7b-instruct-v0.2.Q4_K_M.gguf) are downloaded successfully.
The script then attempts to download a tokenizer and fails.

### Actual Behavior
The script throws an error when trying to download the tokenizer. The error message indicates a 404 Client Error: Not Found for url: https://huggingface.co/None/resolve/main/tokenizer_config.json. This suggests that either the tokenizer's name is not being correctly passed (as indicated by the 'None' in the URL) or there's an issue with the tokenizer's availability on Hugging Face.

### Logs
```bash
22:02:47.207 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default']
Downloading embedding BAAI/bge-small-en-v1.5
Fetching 14 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 14.81it/s]
Embedding model downloaded!
Downloading LLM mistral-7b-instruct-v0.2.Q4_K_M.gguf
LLM model downloaded!
Downloading tokenizer None
Traceback (most recent call last):
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/None/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1374, in hf_hub_download
    raise head_call_error
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 426, in _request_wrapper
    hf_raise_for_status(response)
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-65f21479-09e39977255bdb72502d4b8c;66371627-2d02-44c6-8f25-d115820c1986)

Repository Not Found for url: https://huggingface.co/None/resolve/main/tokenizer_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/User/Projects/Tests/privateGPT/scripts/setup", line 43, in <module>
    AutoTokenizer.from_pretrained(
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 767, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 600, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/Users/User/Projects/Tests/privateGPT/.venv/lib/python3.11/site-packages/transformers/utils/hub.py", line 421, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```
### Additional Information
It seems like the script is not correctly fetching the name or identifier for the tokenizer.
The issue might be related to how the tokenizer's name is being resolved or passed in the script (None).
I also tried with docker compose, yielding same results. Maybe it is just some setting that I am missing from the docs?

Thank you

**Comment by ItsCRC** [comment]
Please add `tokenizer: mistralai/Mistral-7B-Instruct-v0.2 in settings.yaml` under llm

**Comment by ItsCRC** [comment]
By the way, with recent update to repository, it is now added.

**Comment by embcla** [comment]
I'm having this same issue, but with `tokenizer: mistralai/Mistral-7B-Instruct-v0.2` but now the error is

```
TypeError: not all arguments converted during string formatting
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/claudio/privateGPT/private_gpt/__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/claudio/privateGPT/private_gpt/main.py", line 6, in <module>
    app = create_app(global_injector)
  File "/home/claudio/privateGPT/private_gpt/launcher.py", line 63, in create_app
    ui = root_injector.get(PrivateGptUi)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 811, in _get_instance
    return provider.get(injector)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 264, in get
    return injector.create_object(self._cls)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "/home/claudio/miniconda3/envs/privategpt/lib/python3.11/site-packages/injector/__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
  File "/home/claudio/privateGPT/private_gpt/components/llm/llm_component.py", line 37, in __init__
    logger.warning(
Message: 'Failed to download tokenizer %s. Falling back to default tokenizer.'
Arguments: ('mistralai/Mistral-7B-Instruct-v0.2', OSError('You are trying to access a gated repo.\nMake sure to have access to it at https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2.\n401 Client Error. (Request ID: Root=1-668a7826-2be4f1fd550ef55246512cef;2ed5ccb6-5618-4bb2-8545-08acacb4472e)\n\nCannot access gated repo for url https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/resolve/main/config.json.\nAccess to model mistralai/Mistral-7B-Instruct-v0.2 is restricted. You must be authenticated to access it.'))
```
