### ISSUE TITLE
installation using docker compose does not work  

### ISSUE THREAD

**Issue by itayo1010** [imartinez/privateGPT#1762]
i did : 
git clone https://github.com/imartinez/privateGPT 
cd privateGPT 
docker compose up 
and got : 
```

There was a problem when trying to write in your cache folder (/nonexistent/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
13:16:42.780 [INFO    ] private_gpt.settings.settings_loader - Starting application with profiles=['default', 'docker']
Traceback (most recent call last):
  File "/home/worker/app/scripts/setup", line 8, in <module>
    from private_gpt.paths import models_path, models_cache_path
  File "/home/worker/app/private_gpt/paths.py", line 4, in <module>
    from private_gpt.settings.settings import settings
  File "/home/worker/app/private_gpt/settings/settings.py", line 392, in <module>
    unsafe_typed_settings = Settings(**unsafe_settings)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/.venv/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
embedding.mode
  Input should be 'huggingface', 'openai', 'azopenai', 'sagemaker', 'ollama' or 'mock' [type=literal_error, input_value='llamacpp', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/literal_error
```

i used the default docker-compose.yaml :
`services:
  private-gpt:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: local
`

**Comment by levydanqc** [comment]
Still the same problems after git pull... is there a solution to this please ?

**Comment by giodegas** [comment]
same here, just git-pulled , docker compose up ends with:

    private-gpt-1  | PermissionError: [Errno 13] Permission denied: 'tiktoken_cache'
