### ISSUE TITLE
after yesterday update it get error , couldn't run it

### ISSUE THREAD

**Issue by rexzhang2023** [imartinez/privateGPT#20]
llama.cpp: loading model from ./models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 4113748.20 KB
llama_model_load_internal: mem required  = 5809.33 MB (+ 2052.00 MB per state)
...................................................................................................
.
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "/home/rex/privateGPT/privateGPT.py", line 39, in <module>
    main()
  File "/home/rex/privateGPT/privateGPT.py", line 15, in main
    llm = GPT4All(model='./models/ggml-gpt4all-j-v1.3-groovy.bin', backend='gptj', callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Could not import pygpt4all python package. Please install it with `pip install pygpt4all`. (type=value_error)
[2023-05-10 15:44:11,424] {duckdb.py:414} INFO - Persisting DB to disk, putting it in the save folder: db

try install pygpt4all already , but same errors.

**Comment by TylerWJ** [comment]
Getting the same error

**Comment by robinscherbatskyy** [comment]
I too am getting the same error.. 
has anybody found a fix for this?

**Comment by AKBuggy** [comment]
Getting the same error!!

**Comment by Chae4ek** [comment]
it's a langchain issue, see https://github.com/hwchase17/langchain/issues/3839#issuecomment-1544909631
