### ISSUE TITLE
run privateGPT.py error

### ISSUE THREAD

**Issue by zxzhangxiaozx** [imartinez/privateGPT#200]
when i run python privateGPT.py，it show errors like:
llama_print_timings:        load time =  4116.67 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time =  4115.12 ms /     8 tokens (  514.39 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time =  4121.87 ms
Traceback (most recent call last):
  File "/Users/zhangxiao/Resources/chatgpt/privateGPT/privateGPT.py", line 57, in <module>
    main()
  File "/Users/zhangxiao/Resources/chatgpt/privateGPT/privateGPT.py", line 42, in main
    res = qa(query)    
          ^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/vectorstores/base.py", line 366, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/vectorstores/chroma.py", line 181, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/vectorstores/chroma.py", line 228, in similarity_search_with_score
    results = self.__query_collection(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/utils.py", line 50, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/langchain/vectorstores/chroma.py", line 120, in __query_collection
    return self._collection.query(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/chromadb/api/models/Collection.py", line 219, in query
    return self._client._query(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/chromadb/api/local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/chromadb/db/clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangxiao/Library/Python/3.11/lib/python/site-packages/chromadb/db/index/hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by maozdemir** [comment]
You have to run `ingest.py` at least once with files.

**Comment by zxzhangxiaozx** [comment]
thank you

**Comment by asmgx** [comment]
I have the same problem.
I ran ingest.py first and still getting the same error when I type my query

    
    Enter a query: what did the president say about russia?
    Traceback (most recent call last):
      File "h:\__Git\privateGPT\privateGPT.py", line 76, in <module>
        main()
      File "h:\__Git\privateGPT\privateGPT.py", line 48, in main
        res = qa(query)
              ^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 140, in __call__
        raise e
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py", line 134, in __call__
        self._call(inputs, run_manager=run_manager)
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\retrieval_qa\base.py", line 119, in _call
        docs = self._get_docs(question)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\retrieval_qa\base.py", line 181, in _get_docs     
        return self.retriever.get_relevant_documents(question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\base.py", line 377, in get_relevant_documents
        docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 182, in similarity_search  
        docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 229, in similarity_search_with_score
        results = self.__query_collection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\utils.py", line 52, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 121, in __query_collection 
        return self._collection.query(
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\api\models\Collection.py", line 227, in query
        return self._client._query(
               ^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\api\local.py", line 437, in _query
        uuids, distances = self._db.get_nearest_neighbors(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\db\clickhouse.py", line 585, in get_nearest_neighbors     
        uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\ASMGX\AppData\Local\Programs\Python\Python311\Lib\site-packages\chromadb\db\index\hnswlib.py", line 240, in get_nearest_neighbors  
        raise NoIndexException(
    chromadb.errors.NoIndexException: Index not found, please create an instance before querying
    PS H:\__Git>

**Comment by diegotrigo** [comment]
Same error here. Any idea?

```Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "_/privateGPT/privateGPT.py", line 76, in <module>
    main()
  File "_/privateGPT/privateGPT.py", line 36, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Invalid model directory (type=value_error)````

**Comment by aceilort** [comment]
I literally have the exact same issue as @diegotrigo ...
