### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by algisju** [imartinez/privateGPT#202]
Whenever I try "ingest.py" I have the following result:

Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 tokens each)
llama.cpp: loading model from models/ggml-model-q4_0.bin
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 78, in validate_environment
    values["client"] = Llama(
                       ^^^^^^
  File "C:\Python311\Lib\site-packages\llama_cpp\llama.py", line 155, in __init__
    self.ctx = llama_cpp.llama_init_from_file(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\llama_cpp\llama_cpp.py", line 182, in llama_init_from_file
    return _lib.llama_init_from_file(path_model, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError -529697949] Windows Error 0xe06d7363

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\code\privateGPT\ingest.py", line 62, in <module>
    main()
  File "C:\code\privateGPT\ingest.py", line 53, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: models/ggml-model-q4_0.bin
Exception ignored in: <function Llama.__del__ at 0x000001A7CD136480>
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\llama_cpp\llama.py", line 978, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

===========================================================

Please help, thanks for your time

**Comment by algisju** [comment]
Issue FIXED - Redownload the .bin files.

**Comment by Bujiangjiu3** [comment]
Redownload the bin file ggml-gpt4all-j-v1.3-groovy.bin?
Or another version of the bin file?

**Comment by algisju** [comment]
Not another .bin => my first download might have been corrupted (?)

**Comment by Bujiangjiu3** [comment]
Oh, okay, maybe the problems we encountered are different. My problem is to change the MODEL_TYPE in the env configuration to LlamaCpp, and this error occurs. When it is GPT4All, it can work normally.
