### ISSUE TITLE
How do I configure my constants.py file

### ISSUE THREAD

**Issue by Crazygqq** [imartinez/privateGPT#232]
This error occurs when I run the ingest.py file：
Traceback (most recent call last):
  File "E:\Users\Crazy\PycharmProjects\pythonProject\Nd\privateGPT.py", line 18, in <module>
    from constants import CHROMA_SETTINGS
  File "E:\Users\Crazy\PycharmProjects\pythonProject\Nd\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

Process finished with exit code 1

**Comment by Crazygqq** [comment]
This is my configuration. Could you please check it for me? Thank you very much！


MODEL_TYPE: 'GPT4All'
PERSIST_DIRECTORY: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd'
LLAMA_EMBEDDINGS_MODEL: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd\ggml-gpt4all-j-v1.3-groovy.bin'
MODEL_PATH: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd\ggml-gpt4all-j-v1.3-groovy.bin'
MODEL_N_CTX: '2'



import os
from dotenv import load_dotenv
from chromadb.config import Settings

load_dotenv()

# Define the folder for storing database
PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY')

# Define the Chroma settings
CHROMA_SETTINGS = Settings(
        chroma_db_impl='duckdb+parquet',
        persist_directory=PERSIST_DIRECTORY,
        anonymized_telemetry=False
)

> looks like no environment var setting for the first sample variable in .env
> 
> I would check that
> 
> 1. you have renamed example.env to .env (or created your own .env)
> 2. that you have set the _PERSIST_DIRECTORY_ value, such as _PERSIST_DIRECTORY=db_



> looks like no environment var setting for the first sample variable in .env
> 
> I would check that
> 
> 1. you have renamed example.env to .env (or created your own .env)
> 2. that you have set the _PERSIST_DIRECTORY_ value, such as _PERSIST_DIRECTORY=db_

This is my configuration. Could you please check it for me? Thank you very much！


MODEL_TYPE: 'GPT4All'
PERSIST_DIRECTORY: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd'
LLAMA_EMBEDDINGS_MODEL: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd\ggml-gpt4all-j-v1.3-groovy.bin'
MODEL_PATH: 'E:\Users\Crazy\PycharmProjects\pythonProject\Nd\ggml-gpt4all-j-v1.3-groovy.bin'
MODEL_N_CTX: '2'



import os
from dotenv import load_dotenv
from chromadb.config import Settings

load_dotenv()

# Define the folder for storing database
PERSIST_DIRECTORY = os.environ.get('PERSIST_DIRECTORY')

# Define the Chroma settings
CHROMA_SETTINGS = Settings(
        chroma_db_impl='duckdb+parquet',
        persist_directory=PERSIST_DIRECTORY,
        anonymized_telemetry=False
)

**Comment by Multiheart** [comment]
rename example.env to .env by vscode or some other ways like terminal in macOS
