### ISSUE TITLE
Need help. chromadb.errors.NoIndexException

### ISSUE THREAD

**Issue by ado5** [imartinez/privateGPT#239]
Traceback (most recent call last):
  File "f:\ChatGPT\privateGPT\privateGPT.py", line 57, in <module>
    main()
  File "f:\ChatGPT\privateGPT\privateGPT.py", line 42, in main
    res = qa(query)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 119, in _call
    docs = self._get_docs(question)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\base.py", line 366, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 181, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 228, in similarity_search_with_score
    results = self.__query_collection(
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\utils.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "D:\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 120, in __query_collection
    return self._collection.query(
  File "D:\Programs\Python\Python310\lib\site-packages\chromadb\api\models\Collection.py", line 219, in query
    return self._client._query(
  File "D:\Programs\Python\Python310\lib\site-packages\chromadb\api\local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "D:\Programs\Python\Python310\lib\site-packages\chromadb\db\clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "D:\Programs\Python\Python310\lib\site-packages\chromadb\db\index\hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by Suniron** [comment]
Same with a fresh install in a Docker with image `python:3.10`

**Comment by hsm207** [comment]
@Suniron @ado5 there is already an issue for this. See [here](https://github.com/imartinez/privateGPT/issues/132#issuecomment-1551288459)

**Comment by Ji-Shao** [comment]
Same with a fresh install in a Docker with image python:3.10 and models from the readme

root@e27c6ff07235:/privateGPT# python3 --version
Python 3.11.3

**Comment by MichaelSebero** [comment]
System: Linux / NVIDIA GTX 1660
**Error Message**
Traceback (most recent call last):
File "/home/user/privateGPT/privateGPT.py", line 57, in
main()
File "/home/user/privateGPT/privateGPT.py", line 42, in main
res = qa(query)
^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/chains/base.py", line 140, in call
raise e
File "/home/user/.local/lib/python3.11/site-packages/langchain/chains/base.py", line 134, in call
self._call(inputs, run_manager=run_manager)
File "/home/user/.local/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
docs = self._get_docs(question)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
return self.retriever.get_relevant_documents(question)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 366, in get_relevant_documents
docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 181, in similarity_search
docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 228, in similarity_search_with_score
results = self.__query_collection(
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/utils.py", line 50, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 120, in __query_collection
return self._collection.query(
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 219, in query
return self._client._query(
^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/chromadb/api/local.py", line 408, in _query
uuids, distances = self._db.get_nearest_neighbors(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/chromadb/db/clickhouse.py", line 583, in get_nearest_neighbors
uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/user/.local/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 230, in get_nearest_neighbors
raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by omertalib42** [comment]
I'm encountering the same issue on my mac M1 as well.

**Comment by bidego** [comment]
Same error
Mac OS Intel
`Traceback (most recent call last):
  File "/Users/gonzalobide/Workspace/privateGPT/privateGPT.py", line 75, in <module>
    main()
  File "/Users/gonzalobide/Workspace/privateGPT/privateGPT.py", line 47, in main
    res = qa(query)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 366, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 181, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 228, in similarity_search_with_score
    results = self.__query_collection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 120, in __query_collection
    return self._collection.query(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 227, in query
    return self._client._query(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chromadb/api/local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 585, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 240, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying
 ✘ gonzalobide@orejotas-atlanta  ~/Workspace/privateGPT   main ±  py --version
Python 3.10.0
 gonzalobide@orejotas-atlanta  ~/Workspace/privateGPT   main ±  sw_vers 
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
`

**Comment by bidego** [comment]
You need to run ingest.py which will create chroma db
