### ISSUE TITLE
No sentence-transformers model found with name

### ISSUE THREAD

**Issue by rxf113** [imartinez/privateGPT#250]
Run python  ingest.py   output the log
No sentence-transformers model found with name xxx. Creating a new one with MEAN pooling

### example: 
```
Run python  ingest.py  
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 6 chunks of text (max. 500 characters each)
No sentence-transformers model found with name /home/rxf113/.cache/torch/sentence_transformers/GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
Using embedded DuckDB with persistence: data will be stored in: db
```

***But I'm sure this directory exists***

.env content 
```
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=GanymedeNil/text2vec-large-chinese
```

## Environment:
windows 10  WSL2 Ubuntu 20.04 
Python 3.11.3

**Comment by DanEdens** [comment]
I believe this is the same issue I am having after just having pulled the most recent commits

`➜  privateGPT  python3 ingest.py                       
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 characters each)
Traceback (most recent call last):
  File "ingest.py", line 97, in <module>
    main()
  File "ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/dan/.local/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
`

**Comment by DanEdens** [comment]
pydantic reports this was solved in version 2. 
Requirements have it at 1.10 currently.

**Comment by DanEdens** [comment]
https://docs.pydantic.dev/latest/

They are saying it can be fixed by using a fix branch.. which isn't ideal. I will keep digging

**Comment by imartinez** [comment]
@DanEdens what does your .env look like? Did you set a valid EMBEDDINGS_MODEL_NAME?

**Comment by rxf113** [comment]
> I believe this is the same issue I am having after just having pulled the most recent commits
> 
> `➜ privateGPT python3 ingest.py Loading documents from source_documents Loaded 1 documents from source_documents Split into 90 chunks of text (max. 500 characters each) Traceback (most recent call last): File "ingest.py", line 97, in <module> main() File "ingest.py", line 88, in main embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name) File "/home/dan/.local/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 44, in __init__ super().__init__(**kwargs) File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings model_name none is not an allowed value (type=type_error.none.not_allowed) `

I also encountered this problem when i sync the latest code . 
I also encountered this problem.  I solved it
It seems that it is necessary to modify the EMBEDDINGS of the. env file_ MODEL_ NAME uses a hugging face model. Instead of downloading the model locally as previously done

**Comment by rxf113** [comment]
> @rxf113 try with one of the available models in here https://huggingface.co/models?library=sentence-transformers. GanymedeNil/text2vec-large-chinese is not one of the supported models

I tried changing the model.  A new error has occurred

Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 6 chunks of text (max. 500 characters each)
Downloading (…)d9a57/.gitattributes: 100%|█████████████████████████████████████████| 1.23k/1.23k [00:00<00:00, 2.83MB/s]
Downloading (…)_Pooling/config.json: 100%|██████████████████████████████████████████████| 190/190 [00:00<00:00, 553kB/s]
Downloading (…)05abfd9a57/README.md: 100%|█████████████████████████████████████████| 3.66k/3.66k [00:00<00:00, 11.7MB/s]
Downloading (…)abfd9a57/config.json: 100%|█████████████████████████████████████████████| 831/831 [00:00<00:00, 2.23MB/s]
Downloading (…)ce_transformers.json: 100%|██████████████████████████████████████████████| 118/118 [00:00<00:00, 575kB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████| 409M/409M [00:39<00:00, 10.5MB/s]
Downloading (…)nce_bert_config.json: 100%|████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 160kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████| 112/112 [00:00<00:00, 384kB/s]
Downloading (…)d9a57/tokenizer.json: 100%|████████████████████████████████████████████| 439k/439k [00:00<00:00, 471kB/s]
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 339/339 [00:00<00:00, 1.06MB/s]
Downloading (…)05abfd9a57/vocab.txt: 100%|████████████████████████████████████████████| 110k/110k [00:00<00:00, 261kB/s]

Downloading (…)bfd9a57/modules.json: 100%|██████████████████████████████████████████████| 229/229 [00:00<00:00, 823kB/s]
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "/usr/local/gpt/privateGPT/ingest.py", line 97, in <module>
    main()
  File "/usr/local/gpt/privateGPT/ingest.py", line 91, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rxf113/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 413, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "/home/rxf113/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 381, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/home/rxf113/.local/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 159, in add_texts
    self._collection.add(
  File "/home/rxf113/.local/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 101, in add
    self._client._add(
  File "/home/rxf113/.local/lib/python3.11/site-packages/chromadb/api/local.py", line 223, in _add
    self._db.add_incremental(collection_uuid, added_uuids, embeddings)
  File "/home/rxf113/.local/lib/python3.11/site-packages/chromadb/db/clickhouse.py", line 605, in add_incremental
    index.add(uuids, embeddings)
  File "/home/rxf113/.local/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 132, in add
    self._check_dimensionality(embeddings)
  File "/home/rxf113/.local/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 119, in _check_dimensionality
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Dimensionality of (768) does not match index dimensionality (1024)

**Comment by imartinez** [comment]
You need to delete your previous `db` folder before ingesting with the new model.

**Comment by rxf113** [comment]
> You need to delete your previous folder before ingesting with the new model.`db`

Thank you, I forgot. I will close this issue. Thank you again for your efforts

**Comment by DanEdens** [comment]
I'm not sure i follow the fix, 
I've tried both 


PERSIST_DIRECTORY=db
  MODEL_TYPE=GPT4All  
  MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin  
  EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2  
  MODEL_N_CTX=1000  


and 

PERSIST_DIRECTORY=db  
MODEL_TYPE=GPT4All  
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin  
EMBEDDINGS_MODEL_NAME=models/ggml-model-q4_0.bin  
MODEL_N_CTX=1000  

Does it download the all-MiniLM-L6-v2 model or do i need to somehow do that manually. 


right now i get 

`Traceback (most recent call last):
  File "ingest.py", line 97, in <module>
    main()
  File "ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/dan/.local/lib/python3.8/site-packages/langchain/embeddings/huggingface.py", line 46, in __init__
    import sentence_transformers
  File "/home/dan/.local/lib/python3.8/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/dan/.local/lib/python3.8/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/dan/.local/lib/python3.8/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 5, in <module>
    import nltk
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/__init__.py", line 146, in <module>
    from nltk.chunk import *
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/chunk/__init__.py", line 155, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/chunk/api.py", line 13, in <module>
    from nltk.chunk.util import ChunkScore
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/chunk/util.py", line 12, in <module>
    from nltk.tag.mapping import map_tag
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential import (
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/classify/__init__.py", line 97, in <module>
    from nltk.classify.scikitlearn import SklearnClassifier
  File "/home/dan/.local/lib/python3.8/site-packages/nltk/classify/scikitlearn.py", line 38, in <module>
    from sklearn.feature_extraction import DictVectorizer
  File "/home/dan/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/dan/.local/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/dan/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 17, in <module>
    from scipy.sparse import issparse
  File "/usr/lib/python3/dist-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/usr/lib/python3/dist-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/usr/lib/python3/dist-packages/scipy/sparse/sputils.py", line 16, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/dan/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
`

**Comment by DanEdens** [comment]
i downgraded numpy to 1.23.5 from 1.24.3 and it resolved my issue.

**Comment by hnuzhoulin** [comment]
> > You need to delete your previous folder before ingesting with the new model.`db`
> 
> Thank you, I forgot. I will close this issue. Thank you again for your efforts

do you solve it ? which model do you using？

**Comment by rxf113** [comment]
> > > 在使用新模型进行摄取之前，需要删除以前的文件夹。`db`
> > 
> > 
> > 谢谢，我忘了。我将关闭此问题。再次感谢您的努力
> 
> 你解决吗？您使用哪种型号？

https://huggingface.co/models?library=sentence-transformers  链接里的都行吧，随便试了两个但是效果并不好

**Comment by hanwsf** [comment]
Tried several model from https://huggingface.co/models?library=sentence-transformers, ingestion successfull, but privateGPT output is characters not recognizable, pls suggest how to show correctly.

**Comment by rxf113** [comment]
> Tried several model from https://huggingface.co/models?library=sentence-transformers, ingestion successfull, but privateGPT output is characters not recognizable, pls suggest how to show correctly.

输出日志是啥

**Comment by hatgit** [comment]
why would this error happen when .env has 'MODEL_TYPE=GPT4All`:

 ` File "privateGPT.py", line 31
    match model_type:
                   ^
SyntaxError: invalid syntax`

**Comment by gexinhegexin** [comment]
Traceback (most recent call last):
  File "C:\Users\PC\privateGPT\privateGPT.py", line 76, in <module>
    main()
  File "C:\Users\PC\privateGPT\privateGPT.py", line 26, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain\embeddings\huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by gexinhegexin** [comment]
my example.env:

PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

**Comment by gexinhegexin** [comment]
C:\Users\PC\privateGPT>python privateGPT.py
Traceback (most recent call last):
  File "C:\Users\PC\privateGPT\privateGPT.py", line 76, in <module>
    main()
  File "C:\Users\PC\privateGPT\privateGPT.py", line 26, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain\embeddings\huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
