### ISSUE TITLE
 Hugging Face model hub for the SentenceTransformers model with the name "model_name" returned a 401 Unauthorized error

### ISSUE THREAD

**Issue by fingeronthebutton** [imartinez/privateGPT#273]
C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents>python ingest.py
Traceback (most recent call last):
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\utils\_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/sentence-transformers/model_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents\ingest.py", line 64, in <module>
    model = SentenceTransformer('model_name')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\hf_api.py", line 1604, in model_info
    hf_raise_for_status(r)
  File "C:\Users\sheld\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\huggingface_hub\utils\_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6464ae67-0f5fe99f7ba20092384ac129)

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/model_name.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

chatgpt
Yes, in the traceback, the error message indicates that the request to the Hugging Face model hub for the SentenceTransformers model with the name "model_name" returned a 401 Unauthorized error. This suggests that the model you are trying to access is not authorized or requires authentication.

You need to specify a valid and publicly accessible model name from the Hugging Face model hub. Make sure to use a model name that exists and is publicly available. If you are trying to access a private or gated model, you may need to provide proper authentication credentials to access it.

**Comment by fingeronthebutton** [comment]
figured it out, thanx.

**Comment by gaurav-cointab** [comment]
What was it that you did to fix it?

**Comment by amin-henteti** [comment]
i think this PR [feature/sentence-transformers-embeddings](https://github.com/imartinez/privateGPT/pull/224#issue-1712823293) adressed this issue. 
try to update the .env file with the given example.env [EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2](https://github.com/imartinez/privateGPT/blob/1590c5890fb1c9aa63530fb3df0fe172e0b7b5e3/example.env#L4)
