### ISSUE TITLE
Failed to import transformers.models.bert.modeling_bert

### ISSUE THREAD

**Issue by cibernicola** [imartinez/privateGPT#283]
**Describe the bug and how to reproduce it**
Error in initiating intake.
Install requirements and start with python ingest.py
log:

`Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 characters each)
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\transformers\models\bert\modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Python310\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Python310\lib\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Python310\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "C:\Python310\lib\site-packages\torch\utils\tensorboard\__init__.py", line 7, in <module>
    raise ImportError("TensorBoard logging requires TensorBoard version 1.15 or above")
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\gpt\privateGPT\ingest.py", line 97, in <module>
    main()
  File "J:\gpt\privateGPT\ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "C:\Python310\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 470, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 602, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 616, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
TensorBoard logging requires TensorBoard version 1.15 or above`

**Expected behavior**
Document intake for further processing.

**Environment (please complete the following information):**
 - OS / hardware: Win10Pro / 3090
 - Python version :3.10
- Other relevant information

**Additional context**

**Comment by maozdemir** [comment]
`ImportError: TensorBoard logging requires TensorBoard version 1.15 or above`

can you run `pip3 install tensorboard`

**Comment by cibernicola** [comment]
`J:\gpt\privateGPT>pip3 install tensorboard
Requirement already satisfied: tensorboard in c:\python310\lib\site-packages (2.12.1)
Requirement already satisfied: absl-py>=0.4 in c:\python310\lib\site-packages (from tensorboard) (1.2.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\python310\lib\site-packages (from tensorboard) (1.49.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\python310\lib\site-packages (from tensorboard) (2.17.2)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\python310\lib\site-packages (from tensorboard) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\python310\lib\site-packages (from tensorboard) (3.4.3)
Requirement already satisfied: numpy>=1.12.0 in c:\python310\lib\site-packages (from tensorboard) (1.23.5)
Requirement already satisfied: protobuf>=3.19.6 in c:\python310\lib\site-packages (from tensorboard) (3.20.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\python310\lib\site-packages (from tensorboard) (2.28.2)
Requirement already satisfied: setuptools>=41.0.0 in c:\python310\lib\site-packages (from tensorboard) (59.8.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\python310\lib\site-packages (from tensorboard) (0.7.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\python310\lib\site-packages (from tensorboard) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\python310\lib\site-packages (from tensorboard) (1.0.1)
Requirement already satisfied: wheel>=0.26 in c:\python310\lib\site-packages (from tensorboard) (0.37.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\python310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\python310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.2.8)
Requirement already satisfied: six>=1.9.0 in c:\python310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (1.16.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\python310\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\python310\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python310\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\python310\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python310\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\python310\lib\site-packages (from requests<3,>=2.21.0->tensorboard) (2023.5.7)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\python310\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\python310\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard) (3.2.1)

J:\gpt\privateGPT>python ingest.py
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 characters each)
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\transformers\models\bert\modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Python310\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Python310\lib\site-packages\accelerate\accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Python310\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "C:\Python310\lib\site-packages\torch\utils\tensorboard\__init__.py", line 7, in <module>
    raise ImportError("TensorBoard logging requires TensorBoard version 1.15 or above")
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "J:\gpt\privateGPT\ingest.py", line 97, in <module>
    main()
  File "J:\gpt\privateGPT\ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "C:\Python310\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 470, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 602, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 616, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
TensorBoard logging requires TensorBoard version 1.15 or above`

**Comment by DanEdens** [comment]
I'm having a similar issue importing sentence_transformers, despite having installed it with pip already

`Traceback (most recent call last):
  File "/home/dan/lab/ai/privateGPT/ingest.py", line 97, in <module>
    main()
  File "/home/dan/lab/ai/privateGPT/ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/dan/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 49, in __init__
    raise ValueError(
ValueError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.`

**Comment by DanEdens** [comment]
Seemlying also related:

➜  privateGPT  pip uninstall scipy 
Found existing installation: scipy 1.3.3
Not uninstalling scipy at /usr/lib/python3/dist-packages, outside environment /usr
Can't uninstall 'scipy'. No files were found to uninstall.
➜  privateGPT  pip install scipy                
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (1.3.3)

**Comment by DanEdens** [comment]
I fixed my problems by completely reinstalling into a new venv. ingest worked!

**Comment by Jeaudoir** [comment]
Yea boiii! Creating a new venv solved the issue for me as well. (Of course now I have another 1 GB of duplicated libraries filling up my hard drive ... oh well 😅)

**Comment by cibernicola** [comment]
same here,
