### ISSUE TITLE
 Index not found, please create an instance before querying

### ISSUE THREAD

**Issue by SuilandCoder** [imartinez/privateGPT#30]
Got this error when enter a query:

> Traceback (most recent call last):
  File "privateGPT.py", line 39, in <module>
    main()
  File "privateGPT.py", line 24, in main
    res = qa(query)
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 119, in _call
    return func(*args, **kwargs)
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\langchain\vectorstores\chroma.py", line 120, in __query_collection
    return self._collection.query(
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\chromadb\api\models\Collection.py", line 219, in query
    return self._client._query(
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\chromadb\api\local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\chromadb\db\clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "D:\software\code_tools\Anaconda\envs\py3.8\lib\site-packages\chromadb\db\index\hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by blushHair** [comment]
I have the same problem

**Comment by nexuslux** [comment]
Same here :P

**Comment by wekinu** [comment]
I have the same problem.

**Comment by nitay-bachrach** [comment]
same here.
I installed the requirements, downloaded the two files and put them in .models.
I'm using python 3.10.

**Comment by ErixM** [comment]
Have you guys tried ingesting the data first by running ingest.py?

**Comment by OmerFarukOruc** [comment]
> Have you guys tried ingesting the data first by running ingest.py?

```
Is it OK to run only ingest.py standalone or should I do anything else? I am asking because when i run it i get an error of:
Traceback (most recent call last):
  File "C:\Users\omer\Desktop\privateGPT-main\ingest.py", line 22, in <module>
    main()
  File "C:\Users\omer\Desktop\privateGPT-main\ingest.py", line 9, in main
    loader = TextLoader(argv[1], encoding="utf8")
                        ~~~~^^^
IndexError: list index out of range
```

**Comment by sander110419** [comment]
You did not ingest data, after running the ingest.py on your own dataset it will work.
By default there is NO data to use.

**Comment by ErixM** [comment]
> 

On the readme it says python ingest.py <path_to_your_txt_file>, so you should run `python ingest.py ./source_documents/state_of_the_union.txt`

**Comment by OmerFarukOruc** [comment]
Thanks i just fixed this, so it works great right now.

**Comment by Nickwang2010** [comment]
I meet the same problem?
how long will it take to ingest the txt?
I've been waiting for so long

**Comment by Devleed** [comment]
My ingest script is running for 3 hours now. How long does it take?

**Comment by Nickwang2010** [comment]
> 

I spent almost 10-20minites. and finally I successfully run it

**Comment by Nickwang2010** [comment]
> My ingest script is running for 3 hours now. How long does it take?

I spent almost 10-20minites. and finally I successfully run it

**Comment by imartinez** [comment]
Make sure to run `ingest` before running `privateGPT`. If you are ingesting the sample doc use:

`python ingest.py source_documents/state_of_the_union.txt`

Will take some minutes, depending on the file size and the machine. As a result it will create this `db` folder and contents in your project root folder:

db
-- index
--- index_metadata...
--- id_to_uuid...
--- ...
-- chroma-collections.parquet
-- chroma-embeddings.parquet
