### ISSUE TITLE
ingest.py fails on M1 Mac

### ISSUE THREAD

**Issue by csells** [imartinez/privateGPT#301]
**Describe the bug and how to reproduce it**
- follow the instructions in the README to download the models, rename the example.env file and pull the requirements
- run `python3 ingest.py` and see the following output

```sh
➜ python3 ingest.py
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 90 chunks of text (max. 500 characters each)
Downloading (…)e9125/.gitattributes: 100%|███████████████████████████████████████████████████████| 1.18k/1.18k [00:00<00:00, 3.18MB/s]
Downloading (…)_Pooling/config.json: 100%|███████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 1.36MB/s]
Downloading (…)7e55de9125/README.md: 100%|███████████████████████████████████████████████████████| 10.6k/10.6k [00:00<00:00, 16.9MB/s]
Downloading (…)55de9125/config.json: 100%|███████████████████████████████████████████████████████████| 612/612 [00:00<00:00, 1.63MB/s]
Downloading (…)ce_transformers.json: 100%|████████████████████████████████████████████████████████████| 116/116 [00:00<00:00, 347kB/s]
Downloading (…)125/data_config.json: 100%|███████████████████████████████████████████████████████| 39.3k/39.3k [00:00<00:00, 39.9MB/s]
Downloading pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████| 90.9M/90.9M [00:01<00:00, 85.0MB/s]
Downloading (…)nce_bert_config.json: 100%|██████████████████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 247kB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 389kB/s]
Downloading (…)e9125/tokenizer.json: 100%|█████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 6.26MB/s]
Downloading (…)okenizer_config.json: 100%|███████████████████████████████████████████████████████████| 350/350 [00:00<00:00, 1.19MB/s]
Downloading (…)9125/train_script.py: 100%|███████████████████████████████████████████████████████| 13.2k/13.2k [00:00<00:00, 25.1MB/s]
Downloading (…)7e55de9125/vocab.txt: 100%|█████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 3.59MB/s]
Downloading (…)5de9125/modules.json: 100%|███████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 1.13MB/s]
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "/Users/csells/Code/privateGPT/ingest.py", line 94, in <module>
    main()
  File "/Users/csells/Code/privateGPT/ingest.py", line 88, in main
    db = Chroma.from_documents(texts, embeddings, persist_directory=persist_directory, client_settings=CHROMA_SETTINGS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 413, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 381, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 159, in add_texts
    self._collection.add(
  File "/opt/homebrew/lib/python3.11/site-packages/chromadb/api/models/Collection.py", line 101, in add
    self._client._add(
  File "/opt/homebrew/lib/python3.11/site-packages/chromadb/api/local.py", line 223, in _add
    self._db.add_incremental(collection_uuid, added_uuids, embeddings)
  File "/opt/homebrew/lib/python3.11/site-packages/chromadb/db/clickhouse.py", line 605, in add_incremental
    index.add(uuids, embeddings)
  File "/opt/homebrew/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 132, in add
    self._check_dimensionality(embeddings)
  File "/opt/homebrew/lib/python3.11/site-packages/chromadb/db/index/hnswlib.py", line 119, in _check_dimensionality
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Dimensionality of (384) does not match index dimensionality (4096)
```

**Expected behavior**
I expect ingestion to work without error.

**Environment (please complete the following information):**
- macOS 13.3.1 (a) (22E772610a)
- Python 3.11.3

**Comment by imartinez** [comment]
You probably had an existing database from a previous ingestion. We changed the model used to do the ingestion, and that made previous databases incompatible with new ingestions (vector dimensions are different).

Remove the db folder and ingest again. Everything will work.

**Comment by csells** [comment]
That absolutely fixed my problem. Perhaps an entry in the README about ingestion issues and/or how to reset the database for other documents would be useful. Thanks.

**Comment by pascalandy** [comment]
works on my side. Here are the commands I used:

```bash
# check version
privateGPT|main ⇒ python --version
Python 2.7.17
privateGPT|main ⇒ python3 --version
Python 3.11.3

pip install -r requirements.txt

privateGPT|main ⇒ python3 ingest.py
Using embedded DuckDB with persistence: data will be stored in: db

privateGPT|main ⇒ python3 privateGPT.py
```
