### ISSUE TITLE
ValueError: Model path does not exist: LAMA_EMBEDDINGS_MODEL=C:/martinezchatgpt/models/ggml-model-q4_0.bin

### ISSUE THREAD

**Issue by fingeronthebutton** [imartinez/privateGPT#304]
Persistent error. 

(sheld) C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents>python -m ingest
Loading documents from source_documents
Loaded 1 documents from source_documents
Split into 0 chunks of text (max. 500 tokens each)
Traceback (most recent call last):
  File "C:\Users\sheld\.virtualenvs\sheld-ul37renh\Lib\site-packages\langchain\embeddings\llamacpp.py", line 78, in validate_environment
    values["client"] = Llama(
                       ^^^^^^
  File "C:\Users\sheld\.virtualenvs\sheld-ul37renh\Lib\site-packages\llama_cpp\llama.py", line 155, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: LAMA_EMBEDDINGS_MODEL=C:/martinezchatgpt/models/ggml-model-q4_0.bin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents\ingest.py", line 65, in <module>
    main()
  File "C:\martinezchatgpt\privateGPT-main\privateGPT-main\source_documents\ingest.py", line 55, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Users\sheld\.virtualenvs\sheld-ul37renh\Lib\site-packages\langchain\embeddings\llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: LAMA_EMBEDDINGS_MODEL=C:/martinezchatgpt/models/ggml-model-q4_0.bin
Exception ignored in: <function Llama.__del__ at 0x00000187B3EBC220>
Traceback (most recent call last):
  File "C:\Users\sheld\.virtualenvs\sheld-ul37renh\Lib\site-packages\llama_cpp\llama.py", line 1076, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by imartinez** [comment]
We moved away from llama embeddings. Pull the latest changes, install requirements, remove the `db` folder, and run the ingestion again.

**Comment by fingeronthebutton** [comment]
> We moved away from llama embeddings. Pull the latest changes, install requirements, remove the `db` folder, and run the ingestion again.

thank you...
