### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by yjb152-yjb** [imartinez/privateGPT#339]
# ubuntu18.04 

(chatgpt) flora@flora-Lenovo-Legion-Y70002021:~/下载/privateGPT-main$ python privateGPT.py 
Traceback (most recent call last):
  File "/home/flora/下载/privateGPT-main/privateGPT.py", line 20, in <module>
    from constants import CHROMA_SETTINGS
  File "/home/flora/下载/privateGPT-main/constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
------
example.env
```env
PERSIST_DIRECTORY=log
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
```

**Comment by PulpCattel** [comment]
Follow the instructions [here](https://github.com/imartinez/privateGPT#environment-setup).
Have you renamed `example.env` to `.env`?
