### ISSUE TITLE
It says killed after installing torch then no dotenv module

### ISSUE THREAD

**Issue by bitcoinmeetups** [imartinez/privateGPT#340]
Hi, 

I'm ByteMan, a very nice and polite guy.

After I run pip install -r requirements.txt and after it downloads torch it says killed and then the cursor disappears so I have to type reset.

Then when I try python ingest it says:

Traceback (most recent call last):
  File "/root/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
root@app-674cbcff87-jpkxb:~/privateGPT#

**Comment by ExoSilica** [comment]
same

**Comment by zirkuswurstikus** [comment]
Hello,
I was running into the same issue.
I could get "Ingestion complete! You can now run privateGPT.py to query your documents"

Tested on MBP M1

What I did:
```
virtualenv env
source env/bin/activate
./ingest.py
```

ZW

**Comment by Orrouk** [comment]
PROBLEM
C:\Git\PrivateGPT>python ingest.py
Traceback (most recent call last):
  File "C:\Git\PrivateGPT\ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

SOLUTION
pip install python-dotenv
