### ISSUE TITLE
ValueError: Requested tokens exceed context window of 1000

### ISSUE THREAD

**Issue by Pobedie** [imartinez/privateGPT#375]
After I ingest a file, run privateGPT and try to ask anything, I get following error:

```
Traceback (most recent call last):
  File "C:\Stable_Diffusion\privateGPT\privateGPT.py", line 75, in <module>
    main()
  File "C:\Stable_Diffusion\privateGPT\privateGPT.py", line 47, in main
    res = qa(query)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\retrieval_qa\base.py", line 120, in _call
    answer = self.combine_documents_chain.run(
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 239, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\combine_documents\base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\combine_documents\stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\llm.py", line 79, in generate
    return self.llm.generate_prompt(
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\base.py", line 134, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\base.py", line 191, in generate
    raise e
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\base.py", line 185, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\base.py", line 405, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 225, in _call
    for token in self.stream(prompt=prompt, stop=stop, run_manager=run_manager):
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\llms\llamacpp.py", line 274, in stream
    for chunk in result:
  File "C:\Users\olegt\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama.py", line 618, in _create_completion
    raise ValueError(
ValueError: Requested tokens exceed context window of 1000
```

I tried it with docx and pdf, used models are ggml-vic13b-q5_1.bin and stable-vicuna-13B.ggml.q4_0.bin.
During ingestion or loading privateGPT I get no error.

OS: Windows 10
CPU: Ryzen 7 3700
RAM: 32gb

**Comment by Pobedie** [comment]
> how? i'm having this too

I don't really know what happens that it fixed itself. Try different documents and formats, it began to work after I ingested a docx file. Try different terminals (cmd/powerShell)

**Comment by dmalyavin** [comment]
I have this issue after I ingest Whatapp chat history, maybe there are certain characters in there that screw up the tokens? if I convert the txt to a pdf and then ingest that the problem seems to go away.

**Comment by ksg97031** [comment]
Idk why but reducing the chunk_size in line 124 of the ingest.py file, as shown in this link (https://github.com/imartinez/privateGPT/blob/80b9b1d03eb11e90784da0e5cd0577741dd312e1/ingest.py#L124), resolved the issue for now.

**Comment by Danielyy** [comment]
This error still exists when inputting Chinese.

Enter a query: 李白的诗是什么风格？

`ValueError: Requested tokens exceed context window of 2048`

**Comment by suhas9727** [comment]
Increasing the Maximum tokens limit for the LLM worked for me.

I increased it from 1000 to 2000 in .env file
MODEL_N_CTX=2000
