### ISSUE TITLE
Emails ingestion fails entirely if one of the eml parsing throws an exception

### ISSUE THREAD

**Issue by slavag** [imartinez/privateGPT#378]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
Trying to ingest eml , downloaded from google takout, and one of the eml files throws an excption.

**Environment (please complete the following information):**
 - OS / hardware: macOS 13.3.1 / M1
 - Python version : 3.11.3

**Additional context**
Loading new documents:   0%|               | 11/75093 [00:03<6:40:35,  3.12it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 49, in load
    doc = UnstructuredEmailLoader.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 70, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/document_loaders/email.py", line 24, in _get_elements
    return partition_email(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/partition/email.py", line 265, in partition_email
    element.apply(_replace_mime_encodings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/documents/elements.py", line 154, in apply
    cleaned_text = cleaner(cleaned_text)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/unstructured/cleaners/core.py", line 197, in replace_mime_encodings
    return quopri.decodestring(text.encode()).decode(encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 90, in load_single_document
    return loader.load()[0]
           ^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 59, in load
    raise type(e)(f"{self.file_path}: {e}") from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function takes exactly 5 arguments (1 given)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 168, in <module>
    main()
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 158, in main
    texts = process_documents()
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 120, in process_documents
    documents = load_documents(source_directory, ignored_files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/privateGPT/ingest.py", line 109, in load_documents
    for i, doc in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
TypeError: function takes exactly 5 arguments (1 given)

**Comment by slavag** [comment]
This issue is very annoying as ingestion process of thousands of emls fails even if one of the eml is not parsed. Would expect to continue the process
