### ISSUE TITLE
Error: while loading ingest

### ISSUE THREAD

**Issue by AsaTyr2018** [imartinez/privateGPT#385]
**Describe the bug and how to reproduce it**
I Downloaded the latest git and installed the requirements (pip install -r requirements.txt)
No errors so far. 
I Downloaded the Vicunia Models (Should be compatible) and placed it in "models"
I Run the Ingest Script (python ingest.py) and get the error down below.

**Environment (please complete the following information):**
 - Windows 11 Enterprise / RTX 3090
 - Python 3.10.9

**Additional context**
Traceback (most recent call last):
  File "E:\AI\privateGPT\ingest.py", line 9, in <module>
    from langchain.document_loaders import (
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\tools\__init__.py", line 13, in <module>
    from langchain.tools.gmail import (
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\tools\gmail\__init__.py", line 3, in <module>
    from langchain.tools.gmail.create_draft import GmailCreateDraft
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\tools\gmail\create_draft.py", line 11, in <module>
    from langchain.tools.gmail.base import GmailBaseTool
  File "C:\Users\hle\AppData\Roaming\Python\Python39\site-packages\langchain\tools\gmail\base.py", line 17, in <module>
    from googleapiclient.discovery import Resource
  File "C:\ProgramData\Anaconda3\lib\site-packages\googleapiclient\discovery.py", line 57, in <module>
    from googleapiclient import _auth, mimeparse
  File "C:\ProgramData\Anaconda3\lib\site-packages\googleapiclient\_auth.py", line 34, in <module>
    import oauth2client.client
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\client.py", line 45, in <module>
    from oauth2client import crypt
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "C:\ProgramData\Anaconda3\lib\site-packages\oauth2client\_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\crypto.py", line 3279, in <module>
    _lib.OpenSSL_add_all_algorithms()
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by maozdemir** [comment]
> To use this software, you must have Python 3.10 or later installed. Earlier versions of Python will not compile.

You are running it on Python 3.9.

**Comment by AsaTyr2018** [comment]
wow thats odd. py is 3.10.9 and python is 3.9.7

but when i run py ingest.py this comes:
PS E:\AI\privateGPT> py ingest.py
py : Traceback (most recent call last):
In Zeile:1 Zeichen:1
+ py ingest.py
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

  File "E:\AI\privateGPT\ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by maozdemir** [comment]
(Windows) run it with `py -3.10 ingest.py` in order to specify the Python version.

**Comment by AsaTyr2018** [comment]
> So you have to install the requirements... `pip3 install -r requirements.txt`

Just deliver messages about "Requirement already satisfied" ^^ i installed all requirements. hmm maby the git clone is corpted. i redownload it now and check

**Comment by maozdemir** [comment]
Nah, it's not `git clone`. It's the joy of having multiple Python installations.
Use:
`py -3.10 -m pip install -r requirements.txt`

**Comment by AsaTyr2018** [comment]
> 

yea. true. currently i test several AI´s Image, Text/Story, Audio, Voice and now the PrivatGPT. in the hope i can get some sorting done with it ^^ 

Now the setup requires a lot of time.

**Comment by AsaTyr2018** [comment]
Solved. Was the wrong py env. its working now. ..... but now i run in this issue xD :  #343 

Thanks a lot for the help. i monitor the other ticket now =)

**Comment by maozdemir** [comment]
@AsaTyr2018 you can ignore that, they are just nothing but small warnings.

**Comment by AsaTyr2018** [comment]
> 

i would. but it just crash once i get this messages. so ignoring isn´t really possible.
