### ISSUE TITLE
ModuleNotFoundError: No module named 'lz4.frame'

### ISSUE THREAD

**Issue by araujofrancisco** [imartinez/privateGPT#464]
I am getting the error below when i run the ingest file. Already installed the required packages.

pip list | grep lz4 shows lz4 version 4.3.2

Appending to existing vectorstore at db
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "/home/franciscoa/repos/privateGPT/ingest.py", line 167, in <module>
    main()
  File "/home/franciscoa/repos/privateGPT/ingest.py", line 149, in main
    db = Chroma(persist_directory=persist_directory, embedding_function=embeddings, client_settings=CHROMA_SETTINGS)
  File "/home/franciscoa/.local/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 89, in __init__
    self._client = chromadb.Client(self._client_settings)
  File "/home/franciscoa/.local/lib/python3.10/site-packages/chromadb/__init__.py", line 94, in Client
    return chromadb.api.local.LocalAPI(settings, get_db(settings), telemetry_client)
  File "/home/franciscoa/.local/lib/python3.10/site-packages/chromadb/__init__.py", line 49, in get_db
    import chromadb.db.duckdb
  File "/home/franciscoa/.local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 3, in <module>
    from chromadb.db.clickhouse import (
  File "/home/franciscoa/.local/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 19, in <module>
    import clickhouse_connect
  File "/home/franciscoa/.local/lib/python3.10/site-packages/clickhouse_connect/__init__.py", line 1, in <module>
    from clickhouse_connect.driver import create_client
  File "/home/franciscoa/.local/lib/python3.10/site-packages/clickhouse_connect/driver/__init__.py", line 9, in <module>
    from clickhouse_connect.driver.httpclient import HttpClient
  File "/home/franciscoa/.local/lib/python3.10/site-packages/clickhouse_connect/driver/httpclient.py", line 20, in <module>
    from clickhouse_connect.driver.compression import available_compression
  File "/home/franciscoa/.local/lib/python3.10/site-packages/clickhouse_connect/driver/compression.py", line 6, in <module>
    import lz4.frame
ModuleNotFoundError: No module named 'lz4.frame'

OS: Ubuntu 22.04.2 LTS
Python: 3.10.6

**Comment by araujofrancisco** [comment]
Somehow the lz4 package got installed incomplete, so I uninstall and reinstall it and got it working.
