### ISSUE TITLE
PrivateGPT uses online?

### ISSUE THREAD

**Issue by jackfood** [imartinez/privateGPT#467]
When i get privateGPT to work in another PC without internet connection, it appears the following issues. It seems it is getting some information from huggingface. But when i move back to an online PC, it works again. How can i make it work offline? It is two different PC, one with internet and one without. Anyway, thanks for making such a great privategpt.

D:\PrivateGPT\Python310\privategpt\Scripts>python privategpt.py
Traceback (most recent call last):
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connection.py", line 200, in _new_conn
    sock = connection.create_connection(
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\PrivateGPT\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connectionpool.py", line 776, in urlopen
    self._prepare_proxy(conn)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connectionpool.py", line 1041, in _prepare_proxy
    conn.connect()
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connection.py", line 604, in connect
    self.sock = sock = self._new_conn()
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connection.py", line 207, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001BE777A7820>: Failed to resolve 'proxyx01.shs.com.sg' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BE777A7820>: Failed to resolve 'proxyx01.shs.com.sg' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BE777A7820>: Failed to resolve 'proxyx01.shs.com.sg' ([Errno 11001] getaddrinfo failed)")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PrivateGPT\Python310\privategpt\Scripts\privategpt.py", line 75, in <module>
    main()
  File "D:\PrivateGPT\Python310\privategpt\Scripts\privategpt.py", line 25, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\huggingface_hub\hf_api.py", line 1603, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\PrivateGPT\Python310\privategpt\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by ProxyError('Unable to connect to proxy', NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001BE777A7820>: Failed to resolve 'proxyx01.shs.com.sg' ([Errno 11001] getaddrinfo failed)")))

**Comment by jackmanners** [comment]
The readme notes the following:
> during the ingest process no data leaves your local environment. You could ingest without an internet connection, except for the first time you run the ingest script, when the embeddings model is downloaded.

Have you run the ingest.py script and downloaded the embedding model already?

**Comment by jackfood** [comment]
Yes i have run on an internet laptop. When i tried to move everything to another non-internet PC, this error appear. I am wondering whether can do it portable? Can i download the hugging embedding and store locally. But strangely, when i move all files back to internet environment, it works even without internet. I am running this through virtual env created using 'python -m venv privategpt'

**Comment by imartinez** [comment]
The current embeddings model is downloaded from huggingface the first time you run ingest.py, and stored in a cache folder as explained here: https://huggingface.co/docs/datasets/cache

If you want to port everything to another computer, you need to also move there the cached model, otherwise the script will try to download it again.

**Comment by jackfood** [comment]
I have tried to locate the cached model location, not definitely sure where it is. I guess should be somewhere in my main system drive rather than within the virtual environment.

**Comment by marouahamdi** [comment]
hello, i m facing this error : The virtual environment found in /opt/mamba/envs/private seems to be broken.

Recreating virtualenv private-gpt-I4W1ohS--py3.11 in /home/onyxia/.cache/pypoetry/virtualenvs/private-gpt-I4W1ohS--py3.11

when I try to copy the virtual env from a computer to another ( one is windows the other one linux ). plz any help
