### ISSUE TITLE
python privateGPT.py : core dumping

### ISSUE THREAD

**Issue by digitalw00t** [imartinez/privateGPT#47]
draeician@vivy:~/git/privateGPT$ python3 privateGPT.py
llama.cpp: loading model from ./models/ggml-model-q4_0.bin
llama.cpp: can't use mmap because tensors are not aligned; convert to new format to avoid this
llama_model_load_internal: format     = 'ggml' (old version with low tokenizer quality and no mmap support)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 4113748.20 KB
llama_model_load_internal: mem required  = 5809.33 MB (+ 2052.00 MB per state)
...................................................................................................
.
llama_init_from_file: kv self size  =  512.00 MB
AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
Using embedded DuckDB with persistence: data will be stored in: db
Illegal instruction (core dumped)

This machine has no gpu, but 200gb of ram.  So it's not a ram issue, and 24 cores.  There's 9tb of space free, it's got resources for days, just not sure why it's core dumping.

I tokenized the state of the union sample, and this is my first run at asking it questions.

**Comment by digitalw00t** [comment]
Did a cat /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d

Doesn't support avx2 either.  Wonder why they insist on that one capability?!?

**Comment by digitalw00t** [comment]
Odd that I can ingest, but can't do inference with the privateChat.py.

**Comment by digitalw00t** [comment]
Well.. it all the sudden decided to let me actually a query, and I get this error:
Enter a query: Summarize the presidential address in 5 bullet points.

llama_print_timings:        load time = 17451.47 ms
llama_print_timings:      sample time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings: prompt eval time = 30593.95 ms /    14 tokens ( 2185.28 ms per token)
llama_print_timings:        eval time =     0.00 ms /     1 runs   (    0.00 ms per run)
llama_print_timings:       total time = 30610.54 ms
Traceback (most recent call last):
  File "/mnt/c/ai/privateGPT/privateGPT.py", line 67, in <module>
    main()
  File "/mnt/c/ai/privateGPT/privateGPT.py", line 52, in main
    res = qa(query)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 140, in __call__
    raise e
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 333, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 181, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 227, in similarity_search_with_score
    results = self.__query_collection(
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/utils.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/home/draeician/.local/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 120, in __query_collection
    return self._collection.query(
  File "/home/draeician/.local/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 219, in query
    return self._client._query(
  File "/home/draeician/.local/lib/python3.10/site-packages/chromadb/api/local.py", line 408, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/home/draeician/.local/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 583, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "/home/draeician/.local/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 230, in get_nearest_neighbors
    raise NoIndexException(
chromadb.errors.NoIndexException: Index not found, please create an instance before querying

**Comment by digitalw00t** [comment]
And it stopped working again.  I'm not 100% sure what I'm doing with gdb, but here goes.

(venv) draeician@vivy:~/git/privateGPT$ gdb python
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...
(No debugging symbols found in python)
(gdb) run privateGPT.py
Starting program: /home/draeician/git/privateGPT/venv/bin/python privateGPT.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0fff640 (LWP 129322)]
[New Thread 0x7ffff07fe640 (LWP 129323)]
[New Thread 0x7fffedffd640 (LWP 129324)]
[New Thread 0x7fffeb7fc640 (LWP 129325)]
[New Thread 0x7fffe6ffb640 (LWP 129326)]
[New Thread 0x7fffe47fa640 (LWP 129327)]
[New Thread 0x7fffe3ff9640 (LWP 129328)]
[New Thread 0x7fffe17f8640 (LWP 129329)]
[New Thread 0x7fffdeff7640 (LWP 129330)]
[New Thread 0x7fffdc7f6640 (LWP 129331)]
[New Thread 0x7fffd7ff5640 (LWP 129332)]
[New Thread 0x7fffd57f4640 (LWP 129333)]
[New Thread 0x7fffd2ff3640 (LWP 129334)]
[New Thread 0x7fffd07f2640 (LWP 129335)]
[New Thread 0x7fffcfff1640 (LWP 129336)]
[New Thread 0x7fffcd7f0640 (LWP 129337)]
[New Thread 0x7fffcafef640 (LWP 129338)]
[New Thread 0x7fffc87ee640 (LWP 129339)]
[New Thread 0x7fffc5fed640 (LWP 129340)]
[New Thread 0x7fffc17ec640 (LWP 129341)]
[New Thread 0x7fffc0feb640 (LWP 129342)]
[New Thread 0x7fffbe7ea640 (LWP 129343)]
[New Thread 0x7fffbbfe9640 (LWP 129344)]
[New Thread 0x7fffb7124640 (LWP 129345)]
[New Thread 0x7fffb6923640 (LWP 129346)]
[New Thread 0x7fffb6122640 (LWP 129347)]
[New Thread 0x7fffb5921640 (LWP 129348)]
[New Thread 0x7fffb5120640 (LWP 129349)]
[New Thread 0x7fffb491f640 (LWP 129350)]
[New Thread 0x7fffb411e640 (LWP 129351)]
[New Thread 0x7fffb391d640 (LWP 129352)]
[New Thread 0x7fff169ff640 (LWP 129487)]
[New Thread 0x7fff161fe640 (LWP 129488)]
[New Thread 0x7fff119fd640 (LWP 129489)]
[New Thread 0x7fff111fc640 (LWP 129490)]
[New Thread 0x7fff0e9fb640 (LWP 129491)]
[New Thread 0x7fff0c1fa640 (LWP 129492)]
[New Thread 0x7fff099f9640 (LWP 129493)]
[New Thread 0x7fff051f8640 (LWP 129494)]
[New Thread 0x7fff029f7640 (LWP 129495)]
[New Thread 0x7fff001f6640 (LWP 129496)]
[New Thread 0x7ffefd9f5640 (LWP 129497)]
[New Thread 0x7ffefb1f4640 (LWP 129498)]
[New Thread 0x7ffefa9f3640 (LWP 129499)]
[New Thread 0x7ffef61f2640 (LWP 129500)]
[New Thread 0x7ffef39f1640 (LWP 129501)]
[New Thread 0x7ffef11f0640 (LWP 129502)]
[New Thread 0x7ffef09ef640 (LWP 129503)]
[New Thread 0x7ffeec1ee640 (LWP 129504)]
[New Thread 0x7ffee99ed640 (LWP 129505)]
[New Thread 0x7ffee71ec640 (LWP 129506)]
[New Thread 0x7ffee49eb640 (LWP 129507)]
[New Thread 0x7ffee21ea640 (LWP 129508)]
[New Thread 0x7ffedf9e9640 (LWP 129509)]
[New Thread 0x7ffed0493640 (LWP 129544)]
[New Thread 0x7ffecfc92640 (LWP 129545)]
[New Thread 0x7ffecf491640 (LWP 129546)]
[New Thread 0x7ffecec90640 (LWP 129547)]
[New Thread 0x7ffece48f640 (LWP 129548)]
[New Thread 0x7ffecdc8e640 (LWP 129549)]
[New Thread 0x7ffecd48d640 (LWP 129550)]
[New Thread 0x7ffeccc8c640 (LWP 129551)]
[New Thread 0x7ffecc48b640 (LWP 129552)]
[New Thread 0x7ffecbc8a640 (LWP 129553)]
[New Thread 0x7ffecb489640 (LWP 129554)]
[New Thread 0x7ffed5dff640 (LWP 129555)]
Using embedded DuckDB with persistence: data will be stored in: db
[New Thread 0x7ffed47ff640 (LWP 129567)]
[New Thread 0x7ffed3ffe640 (LWP 129568)]
[New Thread 0x7ffec3fff640 (LWP 129569)]
[New Thread 0x7ffec37fe640 (LWP 129570)]
[New Thread 0x7ffec2ffd640 (LWP 129571)]
[New Thread 0x7ffec27fc640 (LWP 129572)]
[New Thread 0x7ffec1ffb640 (LWP 129573)]
[New Thread 0x7ffec17fa640 (LWP 129574)]
[New Thread 0x7ffec0ff9640 (LWP 129575)]
[New Thread 0x7ffebbfff640 (LWP 129576)]
[New Thread 0x7ffebb7fe640 (LWP 129577)]
[New Thread 0x7ffebaffd640 (LWP 129578)]
[New Thread 0x7ffeba7fc640 (LWP 129579)]
[New Thread 0x7ffeb9ffb640 (LWP 129580)]
[New Thread 0x7ffeb97fa640 (LWP 129581)]
[New Thread 0x7ffeb8ff9640 (LWP 129582)]
[New Thread 0x7ffeb3fff640 (LWP 129583)]
[New Thread 0x7ffeb37fe640 (LWP 129584)]
[New Thread 0x7ffeb2ffd640 (LWP 129585)]
[New Thread 0x7ffeb27fc640 (LWP 129586)]
[New Thread 0x7ffeb1ffb640 (LWP 129587)]
[New Thread 0x7ffeb17fa640 (LWP 129588)]
[New Thread 0x7ffeb0ff9640 (LWP 129589)]
[New Thread 0x7ffeab7ff640 (LWP 129590)]
[New Thread 0x7ffeaaffe640 (LWP 129591)]
[New Thread 0x7ffeaa7fd640 (LWP 129592)]
[New Thread 0x7ffea9ffc640 (LWP 129593)]
[New Thread 0x7ffea97fb640 (LWP 129594)]
[New Thread 0x7ffea8ffa640 (LWP 129595)]
[New Thread 0x7ffea3fff640 (LWP 129596)]
[New Thread 0x7ffea37fe640 (LWP 129597)]
[New Thread 0x7ffea2ffd640 (LWP 129598)]
[New Thread 0x7ffea27fc640 (LWP 129599)]
[New Thread 0x7ffea1ffb640 (LWP 129600)]
[New Thread 0x7ffea17fa640 (LWP 129601)]
[New Thread 0x7ffea0ff9640 (LWP 129602)]
[New Thread 0x7ffe9bfff640 (LWP 129603)]
[New Thread 0x7ffe9b7fe640 (LWP 129604)]
[New Thread 0x7ffe9affd640 (LWP 129605)]
[New Thread 0x7ffe9a7fc640 (LWP 129606)]
[New Thread 0x7ffe99ffb640 (LWP 129607)]
[New Thread 0x7ffe997fa640 (LWP 129608)]
[New Thread 0x7ffe98ff9640 (LWP 129609)]
[New Thread 0x7ffe93fff640 (LWP 129610)]
[New Thread 0x7ffe937fe640 (LWP 129611)]
[New Thread 0x7ffe92ffd640 (LWP 129612)]

Thread 1 "python" received signal SIGILL, Illegal instruction.
0x00007ffed3723776 in ?? () from /home/draeician/git/privateGPT/venv/lib/python3.10/site-packages/_pyllamacpp.cpython-310-x86_64-linux-gnu.so
(gdb) exit
A debugging session is active.

        Inferior 1 [process 129297] will be killed.

Quit anyway? (y or n) y

Anyone know what needs to be recompiled so the AVX2 instruction set isn't required?
