### ISSUE TITLE
cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' 

### ISSUE THREAD

**Issue by dhosno** [imartinez/privateGPT#482]
The error comes when running ingest.py: 

Traceback (most recent call last):
  File "C:\Users\user\privateGPT\ingest.py", line 167, in <module>
    main()
  File "C:\Users\user\privateGPT\ingest.py", line 144, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "C:\Users\user\anaconda3\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 598, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 612, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 557, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1174, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (C:\Users\user\anaconda3\lib\site-packages\urllib3\util\ssl_.py)

Reinstalling urrlib3 didn't help 

**Environment:**
 - OS / hardware: Win10 
 - Python version 3.9.12

**Comment by Juusseli** [comment]
It looks like you have installed urllib3 version > 2, which is incompatible with some other packages that you may have installed, such as botocore and google-auth. This may cause errors or unexpected behavior when you use those packages. You may want to downgrade urllib3 to a compatible version, such as 1.26.7, using this command:

pip install --upgrade 'urllib3==1.26.7' --user

**Comment by dhosno** [comment]
hey @Juusseli, thanks! I should've mentioned that I tried downgrading - didn't work. Also weird that the requirements.txt in this repo specifies urllib3==2.0.2. 

this is the error when I downgrade:

Traceback (most recent call last):
  File "C:\Users\user\privateGPT\ingest.py", line 167, in <module>
    main()
  File "C:\Users\user\privateGPT\ingest.py", line 144, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "C:\Users\user\anaconda3\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Users\user\anaconda3\lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 598, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 612, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 557, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\user\anaconda3\lib\site-packages\transformers\utils\import_utils.py", line 1174, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

**Comment by fakabbir** [comment]
The issue is mainly due to some conflicting dependency and under python 3.9.
Try running with python3.10 fresh, things should get right.
