### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by acarionifmc** [imartinez/privateGPT#494]
When I run the "provateGPT.py" file with Python 3.10.11 (64bit) (Windows) I receive this error:

Traceback (most recent call last):
  File "c:\Users\acarioni\source\Python\privateGPT\privateGPT.py", line 3, in <module>
    from langchain.chains import RetrievalQA
  File "C:\Users\acarioni\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Users\acarioni\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 13, in <module>
    from pydantic import BaseModel, root_validator
  File "C:\Users\acarioni\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\__init__.py", line 2, in <module>
    from . import dataclasses
  File "C:\Users\acarioni\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\dataclasses.py", line 41, in <module>
    from typing_extensions import dataclass_transform
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by jferdous70** [comment]
Do `pip install typing-extensions`

**Comment by WAPiumiNavoda** [comment]
hi, i did the pip install typing-extensions this installation alos, but my code did not fix its? why that happen???
