### ISSUE TITLE
Issue on 1st run

### ISSUE THREAD

**Issue by paaalm07** [imartinez/privateGPT#497]
After installing all requirements i just want to run "python ingest.py" which fails, see traceback below.
LLM is there, .env was also adapted

 - Python version 3.11.3

Traceback (most recent call last):
  File "C:\privateGPT-main\ingest.py", line 9, in <module>
    from langchain.document_loaders import (
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\tools\__init__.py", line 26, in <module>
    from langchain.tools.openapi.utils.api_models import APIOperation
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\langchain\tools\openapi\utils\api_models.py", line 6, in <module>
    from openapi_schema_pydantic import MediaType, Parameter, Reference, RequestBody, Schema
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\__init__.py", line 3, in <module>
    from .v3 import *
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\__init__.py", line 1, in <module>
    from .v3_1_0 import *
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\__init__.py", line 9, in <module>
    from .open_api import OpenAPI
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\open_api.py", line 5, in <module>
    from .components import Components
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\components.py", line 7, in <module>
    from .header import Header
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\header.py", line 3, in <module>
    from .parameter import Parameter
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\parameter.py", line 6, in <module>
    from .media_type import MediaType
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\media_type.py", line 8, in <module>
    from .schema import Schema
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\site-packages\openapi_schema_pydantic\v3\v3_1_0\schema.py", line 10, in <module>
    class Schema(BaseModel):
  File "pydantic\main.py", line 292, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\utils.py", line 258, in pydantic.utils.generate_model_signature
  File "C:\Prog\WinPython\WPy64-31130\python-3.11.3.amd64\Lib\inspect.py", line 2722, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name

**Comment by 66north** [comment]
check if updating pydantic solves your problem?

**Comment by paaalm07** [comment]
Thanks, that solved the issue!
`pip install --upgrade pydantic`
(1.9.1 was upgraded to 1.10.8)
