### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'

### ISSUE THREAD

**Issue by sergiofagostinho** [imartinez/privateGPT#532]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
Trying to ingest with a significant set (~100) of documents (mostly `.pdf` and `.docx`). 

```
Creating new vectorstore
Loading documents from source_documents
Loading new documents:   0%|                            | 0/103 [00:08<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/sag02/git/public/privateGPT/ingest.py", line 89, in load_single_document
    return loader.load()[0]
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 71, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain/document_loaders/word_document.py", line 102, in _get_elements
    return partition_docx(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/docx.py", line 144, in partition_docx
    para_element: Optional[Text] = _paragraph_to_element(paragraph)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/docx.py", line 185, in _paragraph_to_element
    return _text_to_element(text)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/docx.py", line 201, in _text_to_element
    elif is_possible_narrative_text(text):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/text_type.py", line 86, in is_possible_narrative_text
    if (sentence_count(text, 3) < 2) and (not contains_verb(text)) and language == "en":
                                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/partition/text_type.py", line 189, in contains_verb
    pos_tags = pos_tag(text)
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/unstructured/nlp/tokenize.py", line 57, in pos_tag
    parts_of_speech.extend(_pos_tag(tokens))
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nltk/tag/__init__.py", line 165, in pos_tag
    tagger = _get_tagger(lang)
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nltk/tag/__init__.py", line 107, in _get_tagger
    tagger = PerceptronTagger()
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nltk/tag/perceptron.py", line 169, in __init__
    self.load(AP_MODEL_LOC)
  File "/usr/local/lib/python3.11/site-packages/nltk/tag/perceptron.py", line 252, in load
    self.model.weights, self.tagdict, self.classes = load(loc)
                                                     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nltk/data.py", line 755, in load
    resource_val = pickle.load(opened_resource)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, '\x00'.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sag02/git/public/privateGPT/./ingest.py", line 167, in <module>
    main()
  File "/Users/sag02/git/public/privateGPT/./ingest.py", line 157, in main
    texts = process_documents()
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/sag02/git/public/privateGPT/./ingest.py", line 119, in process_documents
    documents = load_documents(source_directory, ignored_files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sag02/git/public/privateGPT/./ingest.py", line 108, in load_documents
    for i, doc in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
_pickle.UnpicklingError: invalid load key, '\x00'.
```

**Expected behavior**
Ingestion to happen :)

**Environment (please complete the following information):**
 - OS / hardware: macOS 13.3.1 (a) / i7
 - Python version: 3.10.11
- Other relevant information

**Additional context**
N/A

**Comment by uright** [comment]
I have facing the same issue trying to load .md files.

**Comment by PhotoNomad0** [comment]
I am also seeing the same error when trying to load an `.md` file.

**Comment by lee-jian-hui** [comment]
facing the same issue trying to ingest .html files, converted them to .txt extensions for a dirty fix which works, however it is still only a quick and dirty fix, has anyone managed to find an appropriate fix (which includes slight modification of the code in the installed packages)?
