### ISSUE TITLE
error in running privategpt.py in windows 10 ? 

### ISSUE THREAD

**Issue by dadanrhem** [imartinez/privateGPT#537]
os: windows 10 64bit , ram 8gb

PrivateGPT install completed
ingest.py work well.

after running python privategpt.py i got below error.

F:\pgpt>python privategpt.py
Using embedded DuckDB with persistence: data will be stored in: db
Found model file.
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx = 2048
gptj_model_load: n_embd = 4096
gptj_model_load: n_head = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot = 64
gptj_model_load: f16 = 2
gptj_model_load: ggml ctx size = 5401.45 MB
Traceback (most recent call last):
File "F:\pgpt\privategpt.py", line 76, in
main()
File "F:\pgpt\privategpt.py", line 36, in main
llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
File "pydantic\main.py", line 339, in pydantic.main.BaseModel.init
File "pydantic\main.py", line 1102, in pydantic.main.validate_model
File "C:\Python\lib\site-packages\langchain\llms\gpt4all.py", line 139, in validate_environment
values["client"] = GPT4AllModel(
File "C:\Python\lib\site-packages\gpt4all\gpt4all.py", line 49, in init
self.model.load_model(model_dest)
File "C:\Python\lib\site-packages\gpt4all\pyllmodel.py", line 141, in load_model
llmodel.llmodel_loadModel(self.model, model_path.encode('utf-8'))
OSError: [WinError -1073741795] Windows Error 0xc000001d

Any one have idea what is wrong , what do I do ?

Thanks a lot

**Comment by dadanrhem** [comment]
pip3 cache purge
pip3 uninstall gpt4all
pip3 install gpt4all==.0.2.2

even with version 0.2.2 gpt4all I got exactly same error.
