### ISSUE TITLE
Cannot run ingest.py nor privategpt.py

### ISSUE THREAD

**Issue by SidSkiba** [imartinez/privateGPT#550]
PS C:\privategpt-main> python privategpt.py
Traceback (most recent call last):
  File "C:\Users\Sly\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\embeddings\huggingface.py", line 46, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\privategpt-main\privategpt.py", line 76, in <module>
    main()
  File "C:\privategpt-main\privategpt.py", line 26, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sly\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\embeddings\huggingface.py", line 49, in __init__
    raise ValueError(
ValueError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.

In did the `pip install sentence_transformers` but it did not change anything. I get the same error with both ingest.py and privategpt.py.

**Comment by yusufozben** [comment]
`pip install sentence-transformers==2.2.1`
This solved my issue

I solved it with this link;
https://github.com/UKPLab/sentence-transformers/issues/843#issuecomment-1327984985

**Comment by SamuraiDjvak** [comment]
> 
This work very nice thanks!

**Comment by veljkojoksimovic** [comment]
pip install sentence-transformers==2.2.1 not work
