### ISSUE TITLE
python ingest.py fail

### ISSUE THREAD

**Issue by Kashif-Raza6** [imartinez/privateGPT#553]
while running the `python ingest.py` file getting the following error:

`RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_'`

Detail is:

`
Traceback (most recent call last):
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1172, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\bert\modeling_bert.py", line 42, in <module>
    from ...modeling_utils import PreTrainedModel
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 84, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 30, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\__init__.py", line 105, in <module>
    from .launch import (
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\launch.py", line 24, in <module>
    from ..commands.config.config_args import SageMakerConfig
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\config\__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\config\config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\config\sagemaker.py", line 35, in <module>
    import boto3  # noqa: F401
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\boto3\__init__.py", line 17, in <module>
    from boto3.session import Session
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\session.py", line 26, in <module>
    import botocore.client
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\docs\__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\docs\service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\docs\client.py", line 17, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\docs\example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\docs\shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\utils.py", line 37, in <module>
    import botocore.httpsession
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\prvtgpt\privateGPT\ingest.py", line 167, in <module>
    main()
  File "D:\prvtgpt\privateGPT\ingest.py", line 144, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\embeddings\huggingface.py", line 54, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    model_class = _get_model_class(config, cls._model_mapping)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 360, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 598, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 612, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 557, in getattribute_from_module
    if hasattr(module, attr):
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1162, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\kashif.raza\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1174, in _get_module
    raise RuntimeError(
`

**Comment by Kashif-Raza6** [comment]
Here is the .env content:
`
PERSIST_DIRECTORY=db
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4
`

structure of folder is same just added the `models` folder and added folder.

**Comment by sarment0** [comment]
I'm having the same error message.

**Comment by MikoAL** [comment]
it might be a python version problem? I got the same error while using 3.9 but it worked when using 3.10

**Comment by Charmelink** [comment]
I had this problem as well. I found this comment elsewhere and it fixed the problem for me.

"DEFAULT_CIPHERS is removed from urllib3 2.0.0

If you encounter this in 2023 or later, you might want want to pin to a version < 2

pip install 'urllib3<2'
"
I hope this helps!

**Comment by imene-swaan** [comment]
I'm having the same issue
