### ISSUE TITLE
Could not import sentence_transformers python package when running "python privateGPT.py"

### ISSUE THREAD

**Issue by RocketScience11** [imartinez/privateGPT#570]
After ingesting the documents, when I run "python privateGPT.py", gives the following error:

Traceback (most recent call last):
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 46, in __init__
    import sentence_transformers
  File "/Users/pedrobeirao/privateGPT/sentence-transformers/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/Users/pedrobeirao/privateGPT/sentence-transformers/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/Users/pedrobeirao/privateGPT/sentence-transformers/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 5, in <module>
    import nltk
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/__init__.py", line 153, in <module>
    from nltk.translate import *
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/translate/__init__.py", line 24, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/translate/meteor_score.py", line 13, in <module>
    from nltk.corpus import WordNetCorpusReader, wordnet
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/corpus/__init__.py", line 64, in <module>
    from nltk.corpus.reader import *
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/corpus/reader/__init__.py", line 106, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/Users/pedrobeirao/mambaforge/lib/python3.10/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/pedrobeirao/mambaforge/lib/python3.10/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Users/pedrobeirao/mambaforge/lib/python3.10/lib-dynload/_sqlite3.cpython-310-darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/pedrobeirao/mambaforge/lib/python3.10/lib-dynload/_sqlite3.cpython-310-darwin.so
  Expected in: /usr/lib/libsqlite3.dylib

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedrobeirao/privateGPT/privateGPT.py", line 76, in <module>
    main()
  File "/Users/pedrobeirao/privateGPT/privateGPT.py", line 26, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/Users/pedrobeirao/privateGPT/venv/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 49, in __init__
    raise ValueError(
ValueError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.

-------------
MacBook Pro
Apple M1
MacOs Monterrey

**Comment by yusufozben** [comment]
Can you try it;
`pip install sentence-transformers==2.2.1`

**Comment by rostcheck** [comment]
Installing pip install sentence-transformers==2.2.1 doesn't work, the problem is the missing symbol _sqlite3_enable_load_extension. You can fix it by re-configuring and recompiling python with the sqlite extensions:
 ./configure --enable-loadable-sqlite-extensions && make && sudo make install
 
 See https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

**Comment by RocketScience11** [comment]
Thanks! I cloned privateGPT and installed the requirements on a base conda
environment instead of a dedicated environment as I did before, and it's
now working.

**Comment by mertsengil** [comment]
> Can you try it; `pip install sentence-transformers==2.2.1`

thank you so much, this solved my problem
