### ISSUE TITLE
FR: Can docker deployment be provided?

### ISSUE THREAD

**Issue by 1-2-3** [imartinez/privateGPT#60]

**Comment by mpadge** [comment]
``` bash
FROM ubuntu

RUN apt-get update -qq && apt-get install -y \
    git \
    python \
    python-is-python3 \
    pip \
    wget

RUN git clone https://github.com/imartinez/privateGPT.git \
    && cd privateGPT \
    && pip install requirements.txt

RUN echo -e \
"PERSIST_DIRECTORY=db\n
LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bib\n
MODEL_TYPE=GPT4Alb\n
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bib\n
MODEL_N_CTX=1000" > .env \
    && chmod a+x .env

RUN mkdir models \
    && cd models
    && wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin \
    && wget https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin \
    && cd ..
```

plus open ports and put an endpoint on if you want to query it, or just run directly and mount local volume into `source_documents`. (And thanks loads @imartinez for this awesome contribution!)

**Comment by imartinez** [comment]
That looks great, and really helpful. Do you think we should add a section for that on the Readme @mpadge? Maybe you could open a PR, would love to have you as contributor!

**Comment by Rots** [comment]
I see there's already a pull request https://github.com/imartinez/privateGPT/pull/120

**Comment by Deepansharora27** [comment]
Everytime I am trying to build an image using this Dockerfile, I get the Error Message that: 

Not Enough Space Left on your Device

Even though I have ample of space present on my Host Machine. What should be the workaround for this ? 
Thanks !!

**Comment by drifter75** [comment]
I am getting below error:

```
#7 465.6 Successfully built llama-cpp-python pandoc olefile red-black-tree-mod compressed-rtf hnswlib python-docx python-pptx
#7 465.6 ERROR: Exception:
#7 465.6 Traceback (most recent call last):
#7 465.6   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
#7 465.6     status = run_func(*args)
#7 465.6   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#7 465.6     return func(self, options, args)
#7 465.6   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
#7 465.6     to_install = resolver.get_installation_order(requirement_set)
#7 465.6   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
#7 465.6     weights = get_topological_weights(
#7 465.6   File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
#7 465.6     assert len(weights) == expected_node_count
#7 465.6 AssertionError
```
