### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Exagram** [imartinez/privateGPT#605]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**

I am trying to run ingest with a bunch of PDF's and am having the following error:

```
python3 ingest.py
Creating new vectorstore
Loading documents from source_documents
Loading new documents:  30%|██████▎              | 9/30 [01:22<03:12,  9.19s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/REDACTED/Documents/repos/privateGPT/ingest.py", line 89, in load_single_document
    return loader.load()
  File "/home/REDACTED/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 207, in load
    return list(self.lazy_load())
  File "/home/REDACTED/.local/lib/python3.10/site-packages/langchain/document_loaders/pdf.py", line 214, in lazy_load
    yield from self.parser.parse(blob)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/langchain/document_loaders/base.py", line 87, in parse
    return list(self.lazy_parse(blob))
  File "/home/REDACTED/.local/lib/python3.10/site-packages/langchain/document_loaders/parsers/pdf.py", line 35, in lazy_parse
    text = extract_text(pdf_file_obj)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/high_level.py", line 175, in extract_text
    interpreter.process_page(page)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 997, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 1016, in render_contents
    self.execute(list_value(streams))
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 1021, in execute
    parser = PDFContentParser(streams)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 251, in __init__
    PSStackParser.__init__(self, None)  # type: ignore[arg-type]
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/psparser.py", line 545, in __init__
    PSBaseParser.__init__(self, fp)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/psparser.py", line 193, in __init__
    self.seek(0)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 263, in seek
    self.fillfp()
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdfinterp.py", line 260, in fillfp
    self.fp = BytesIO(strm.get_data())
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdftypes.py", line 396, in get_data
    self.decode()
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/pdftypes.py", line 349, in decode
    data = lzwdecode(data)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/lzw.py", line 103, in lzwdecode
    return b"".join(s)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/lzw.py", line 85, in run
    x = self.feed(code)
  File "/home/REDACTED/.local/lib/python3.10/site-packages/pdfminer/lzw.py", line 58, in feed
    x = self.prevbuf = cast(bytes, self.table[code])  # assume not None
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/REDACTED/Documents/repos/privateGPT/ingest.py", line 166, in <module>
    main()
  File "/home/REDACTED/Documents/repos/privateGPT/ingest.py", line 156, in main
    texts = process_documents()
  File "/home/REDACTED/Documents/repos/privateGPT/ingest.py", line 118, in process_documents
    documents = load_documents(source_directory, ignored_files)
  File "/home/REDACTED/Documents/repos/privateGPT/ingest.py", line 107, in load_documents
    for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
IndexError: list index out of range
```

**Expected behavior**

Ingest should work.

**Environment (please complete the following information):**
 - OS / hardware: Linux Mint 21
 - Python version 3.10.6
- Other relevant information

**Additional context**

P.S. What a horrible error message? How does this vague error help the end user/developer?

**Comment by pseudotensor** [comment]
Don't recommend pdfminer, better to use pypdf or even pymupdf like in h2oGPT or localGPT. https://github.com/h2oai/h2ogpt

I've found bad experience with pdfminer.
