### ISSUE TITLE
ingest.py fails to complete

### ISSUE THREAD

**Issue by wandering-wombat** [imartinez/privateGPT#614]
**Describe the bug and how to reproduce it**

...  privateGPT % python3 ingest.py
Traceback (most recent call last):
  File "/Users/user1/Desktop/privateGPT/ingest.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Expected behavior**

**Environment (please complete the following information):**
working on my initial installation on a mac mini 8BG memory 
macOS v 13.4
python3 v 3.11.1

**Additional context**

privateGPT directory created with the following contents:
ls -la
drwxr-xr-x@ 16 user1  staff    512 Jun  3 22:35 .
drwx------@ 85 user1   staff   2720 Jun  3 22:35 ..
-rw-r--r--@  1 user1  staff    246 Jun  4 13:08 .env
drwxr-xr-x@ 12 user1   staff    384 Jun  3 15:03 .git
drwxr-xr-x@  3 user1   staff     96 Jun  3 15:03 .github
-rw-r--r--@  1 user1   staff   3145 Jun  3 15:03 .gitignore
-rw-r--r--@  1 user1   staff   1375 Jun  3 15:03 .pre-commit-config.yaml
-rw-r--r--@  1 user1   staff  11357 Jun  3 15:03 LICENSE
-rw-r--r--@  1 user1   staff   6688 Jun  3 15:03 README.md
-rw-r--r--@  1 user1   staff    372 Jun  3 15:03 constants.py
drwxr-xr-x@  2 user1   staff     64 Jun  4 13:12 db
-rwxr-xr-x@  1 user1  staff   6158 Jun  3 15:40 ingest.py
drwxr-xr-x@  3 user1   staff     96 Jun  3 22:35 models
-rwxr-xr-x@  1 user1   staff   3037 Jun  3 15:03 privateGPT.py
-rw-r--r--@  1 user1   staff    231 Jun  3 15:03 requirements.txt
drwxr-xr-x@  3 user1   staff     96 Jun  3 15:03 source_documents

.env contents

PERSIST_DIRECTORY=/Users/user1/Desktop/privateGPT/db
MODEL_TYPE=GPT4All
MODEL_PATH=/Users/user1/Desktop/privateGPT/models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
MODEL_N_CTX=1000
TARGET_SOURCE_CHUNKS=4

**Comment by maozdemir** [comment]
https://pypi.org/project/python-dotenv/

**Comment by cjenkscybercom** [comment]
Same here, M2 Mac.

**Comment by cjenkscybercom** [comment]
I'm a bit rusty with python 3 and how it's managing installations on different systems nowadays, but generally I've gotten this to work with `python3 -m pip install -r requirements.txt` whereas `pip3 install -r requirements.txt` doesn't work. I suspect this is an environment setup problem.

But it also appears to be a package / repo thing too? It appears I cannot pull anything from langchain past 0.0.27 even though they've definitely [released 0.0.177](https://github.com/hwchase17/langchain/releases/tag/v0.0.177)

```
ERROR: Could not find a version that satisfies the requirement langchain==0.0.177 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27)
ERROR: No matching distribution found for langchain==0.0.177
```

**Comment by slaughters85j** [comment]
Same here M1 Mac.  Full error below.  I also tried: python -m pip install dotenv; pip install dotenv --use-pep517

(base) x@Mac-Studio privateGPT % pip install dotenv          
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [76 lines of output]
      /Users/x/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [16 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-wheel-vcu37v_2/distribute_efd98f20827742e39a959bea9791899d/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/Users/johnsaunders/anaconda3/lib/python3.10/site-packages/setuptools/installer.py", line 96, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Users/x/anaconda3/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/x/anaconda3/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/tmp0wiajmxg', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/pip-install-gkzlszrj/dotenv_3e42b192141645ffba0b06ffefe8d996/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/x/anaconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/Users/x/anaconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/x/anaconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/Users/x/anaconda3/lib/python3.10/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/x/anaconda3/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/8b/9szcn471411822dvxds_c1780000gn/T/tmp0wiajmxg', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SriramKalki** [comment]
I realized that I was installing packages using a different python version of pip, and then trying to run a file with another different version. python3 -m pip worked for me.

**Comment by slaughters85j** [comment]
Yes.  I just discovered this too.  I assumed I was using the right one as I was using (base) but VSCode was still using an older version.

**Comment by derrickstaten** [comment]
I'm using `venv`, I'm inside my environment and i've run `pip3 install -r requirements.txt`. Everything is successfully installed. Even after that I still get `ModuleNotFoundError: No module named 'dotenv'` when running ingest.py. Struggle.

**Comment by maozdemir** [comment]
> I'm using `venv`, I'm inside my environment and i've run `pip3 install -r requirements.txt`. Everything is successfully installed. Even after that I still get `ModuleNotFoundError: No module named 'dotenv'` when running ingest.py. Struggle.

I suggest you refer to this fork: https://github.com/maozdemir/privateGPT Since this repo seems to be unmaintained, this is the most up-to-date fork atm.
