### ISSUE TITLE
none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by EletrixtimeYT** [imartinez/privateGPT#666]
Traceback (most recent call last):
  File "privateGPT.py", line 21, in <module>
    from constants import CHROMA_SETTINGS
  File "constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by jamestbrown** [comment]
Did you follow the step `Rename example.env to .env and edit the variables appropriately.`  and make sure that the directory exists?

**Comment by rivindubandara** [comment]
I fixed this error by downloading all the dependencies, making sure the environment variables were set properly. I also had to download visual studio build tools because some dependencies did not work without it.
