### ISSUE TITLE
Unable to run ingest.py

### ISSUE THREAD

**Issue by gournath1** [imartinez/privateGPT#687]
Traceback (most recent call last):
  File "/home/g30097220/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 46, in __init__
    import sentence_transformers
  File "/home/g30097220/.local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/g30097220/.local/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/g30097220/.local/lib/python3.10/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/home/g30097220/.local/lib/python3.10/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/g30097220/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclRedOpDestroy

The above exception was the direct cause of the following exception:

ingest.py is throwing below error
undefined symbol: ncclRedOpDestroy

Can someone please advise a remedy

Traceback (most recent call last):
  File "/home/jupyter/LocalLLM/privateGPT/privateGPT.py", line 76, in <module>
    main()
  File "/home/jupyter/LocalLLM/privateGPT/privateGPT.py", line 26, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/g30097220/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 49, in __init__
    raise ValueError(
ValueError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.

**Comment by kyxap** [comment]
have you tried to do as advised ?
```bash
ValueError: Could not import sentence_transformers python package. Please install it with pip install sentence_transformers
```

**Comment by some1ataplace** [comment]
I got this error running an old mac OS:

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sentencepiece/_sentencepiece.cpython-311-darwin.so, 2): Symbol not found: ____chkstk_darwin

pip3 install sentence_transformers
pip3 install sentencepiece

Neither of these are working.

**Comment by TyrsDev** [comment]
None of the suggestions I could find in issues here worked, but doing everything within pipenv solved the problem:
`pipenv install -r requirements.txt`
`pipenv run python ingest.py`
`pipenv run python privateGPT.py`
