### ISSUE TITLE
python3 privateGPT.py

### ISSUE THREAD

**Issue by anxiufang-tal** [imartinez/privateGPT#690]
python3 ingest.py
Appending to existing vectorstore at db
Using embedded DuckDB with persistence: data will be stored in: db
Loading documents from source_documents
Loading new documents: 0it [00:00, ?it/s]
No new documents to load

and run python3 privateGPT.py error
Using embedded DuckDB with persistence: data will be stored in: db
Traceback (most recent call last):
  File "/Users/xiaoan/Desktop/project/privateGPT-1/privateGPT.py", line 75, in <module>
    main()
  File "/Users/xiaoan/Desktop/project/privateGPT-1/privateGPT.py", line 35, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/llms/gpt4all.py", line 133, in validate_environment
    from gpt4all import GPT4All as GPT4AllModel
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .pyllmodel import LLModel # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 55, in <module>
    llmodel, llama = load_llmodel_library()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 49, in load_llmodel_library
    llama_lib = ctypes.CDLL(llama_dir, mode=ctypes.RTLD_GLOBAL)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.dylib, 10): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

**Comment by namronservices** [comment]
I had the same error when my OSX version was <12.6.  After I've upgraded to Monterey (12.6.6.), this problem was solved.
What osx version do you have?

**Comment by anxiufang-tal** [comment]
> I had the same error when my OSX version was <12.6. After I've upgraded to Monterey (12.6.6.), this problem was solved. What osx version do you have?

11.7.4

**Comment by namronservices** [comment]
I believe an upgrade will solve this for you since the error says:
Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.dylib **(which was built for Mac OS X 12.6)**
Expected in: /usr/lib/libc++.1.dylib

**Comment by anxiufang-tal** [comment]
> I believe an upgrade will solve this for you since the error says: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv Referenced from: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.dylib **(which was built for Mac OS X 12.6)** Expected in: /usr/lib/libc++.1.dylib

ok,thanks，let me try
