### ISSUE TITLE
Invalid model file : Unable to instantiate model (type=value_error)

### ISSUE THREAD

**Issue by boral** [imartinez/privateGPT#707]
**Describe the bug and how to reproduce it**
Getting following error on running python privateGPT.py

```
(myenv) (base) PS C:\Users\hp\Downloads\privateGPT-main> python privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  models/ggml-v3-13b-hermes-q5_1.bin
Invalid model file
Traceback (most recent call last):
  File "C:\Users\hp\Downloads\privateGPT-main\privateGPT.py", line 82, in <module>
    main()
  File "C:\Users\hp\Downloads\privateGPT-main\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)
```

**Expected behavior**
python privateGPT.py should run properly

**Environment (please complete the following information):**
 - OS / hardware: Windows 10
 - Python version 3.10.9

**Comment by Friedrich-hue** [comment]
how to upgrade to 0.3.4?

**Comment by PJHinker** [comment]
Same problem here running Ubuntu 20.04.  Works on Windows 10.  Both are running python 3.10.6.  Would really like to get it running on the Linux machine as it's a much more capable machine.

**Comment by gevezex** [comment]
Same problem with a Mac M1 pro max

**Comment by freakynit** [comment]
Update: 

My ggml v3 model worked with `llama-cpp-python` `v0.1.68`. Haven't tested with older ones though.

**Comment by chanwitkepha** [comment]
I have same problem too. I use conda to create environment using python=3.10
OS: Ubuntu 18.04.6 LTS
CUDA: 12.1 and 11.8 (However this user will set PATH to /usr/local/cuda-11.8/bin)

```
(private_gpt) devteam@devteam-pc:~/privateGPT$ python3.10 privateGPT.py
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
Invalid model file
Traceback (most recent call last):
  File "/ssd-disk2/home/devteam/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/ssd-disk2/home/devteam/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/home/devteam/anaconda3/envs/private_gpt/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model (type=value_error)
(private_gpt) devteam@devteam-pc:~/privateGPT$
(private_gpt) devteam@devteam-pc:~/privateGPT$ python --version
Python 3.10.12
(private_gpt) devteam@devteam-pc:~/privateGPT$ pip3 --version
pip 23.2.1 from /home/devteam/anaconda3/envs/private_gpt/lib/python3.10/site-packages/pip (python 3.10)
(private_gpt) devteam@devteam-pc:~/privateGPT$
```

```
(private_gpt) devteam@devteam-pc:~/privateGPT$ pip3 list | grep llama-cpp-python
llama-cpp-python         0.1.68
(private_gpt) devteam@devteam-pc:~/privateGPT$

```
