### ISSUE TITLE
Not sure what's happening here after the latest update! 

### ISSUE THREAD

**Issue by sharansabi** [imartinez/privateGPT#72]
**~/dev/privateGPT$ python ingest.py** 

```
Traceback (most recent call last):
  File "/home/sharan/dev/privateGPT/ingest.py", line 7, in <module>
    from constants import CHROMA_SETTINGS
  File "/home/sharan/dev/privateGPT/constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

```

**Comment by sharansabi** [comment]
my bad

**Comment by omerta222** [comment]
> **~/dev/privateGPT$ python ingest.py**
> 
> ```
> Traceback (most recent call last):
>   File "/home/sharan/dev/privateGPT/ingest.py", line 7, in <module>
>     from constants import CHROMA_SETTINGS
>   File "/home/sharan/dev/privateGPT/constants.py", line 11, in <module>
>     CHROMA_SETTINGS = Settings(
>   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for Settings
> persist_directory
>   none is not an allowed value (type=type_error.none.not_allowed)
> ```
