### ISSUE TITLE
KeyError: 'elements' while I try to submit query

### ISSUE THREAD

**Issue by pligor** [imartinez/privateGPT#749]
Full output:
```
python privateGPT.py

Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  /Users/gp/Library/Application Support/nomic.ai/GPT4All/ggml-gpt4all-j-v1.3-groovy.bin
gptj_model_load: loading model from '/Users/gp/Library/Application Support/nomic.ai/GPT4All/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query:
Enter a query: Are you there ?
Traceback (most recent call last):
  File "/Users/gp/Desktop/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/Users/gp/Desktop/privateGPT/privateGPT.py", line 54, in main
    res = qa(query)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 119, in _call
    docs = self._get_docs(question)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 181, in _get_docs
    return self.retriever.get_relevant_documents(question)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 392, in get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 182, in similarity_search
    docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 230, in similarity_search_with_score
    results = self.__query_collection(
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/utils.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 227, in query
    return self._client._query(
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/api/local.py", line 437, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 584, in get_nearest_neighbors
    index = self._index(collection_uuid)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/db/clickhouse.py", line 98, in _index
    index = Hnswlib(collection_id, self._settings, collection_metadata)
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 94, in __init__
    self._load()
  File "/Users/gp/.pyenv/versions/locallm/lib/python3.10/site-packages/chromadb/db/index/hnswlib.py", line 231, in _load
    max_elements=self._index_metadata["elements"],
KeyError: 'elements'
```
Could you attend to it ?

**Comment by tkreuder** [comment]
Same here. I did `rm -rf db` and then `python ingest.py`. Now it works.
