### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by kpennell** [imartinez/privateGPT#754]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
Tried installing on MacOS and hit a bug when trying to install the requirements

**Expected behavior**
Hoped it would install.

**Environment (please complete the following information):**
- ﻿macOS Monterey / Version 12.6.6 (21G646) / Processor 2.6 GHz 6-Core Intel Core i7
- Python 3.12.0b3

**Additional context**
Here's what I'm seeing. Fresh Python3 install, pip3, setuptools, etc.

```

(myenv) kylepennell@Kyles-MacBook-Pro privateGPT-main % pip3 install -r requirements.txt
Collecting langchain==0.0.197 (from -r requirements.txt (line 1))
  Downloading langchain-0.0.197-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 11.9 MB/s eta 0:00:00
Collecting gpt4all==0.3.4 (from -r requirements.txt (line 2))
  Downloading gpt4all-0.3.4-py3-none-macosx_10_9_universal2.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 7.6 MB/s eta 0:00:00
Collecting chromadb==0.3.23 (from -r requirements.txt (line 3))
  Downloading chromadb-0.3.23-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.3/71.3 kB 2.4 MB/s eta 0:00:00
Collecting llama-cpp-python==0.1.50 (from -r requirements.txt (line 4))
  Downloading llama_cpp_python-0.1.50.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 18.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3==2.0.2 (from -r requirements.txt (line 5))
  Downloading urllib3-2.0.2-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.2/123.2 kB 3.5 MB/s eta 0:00:00
Collecting PyMuPDF==1.22.3 (from -r requirements.txt (line 6))
  Downloading PyMuPDF-1.22.3.tar.gz (59.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 MB 10.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dotenv==1.0.0 (from -r requirements.txt (line 7))
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting unstructured==0.6.6 (from -r requirements.txt (line 8))
  Downloading unstructured-0.6.6-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 21.3 MB/s eta 0:00:00
Collecting extract-msg==0.41.1 (from -r requirements.txt (line 9))
  Downloading extract_msg-0.41.1-py2.py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.5/184.5 kB 5.7 MB/s eta 0:00:00
Collecting tabulate==0.9.0 (from -r requirements.txt (line 10))
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting pandoc==2.3 (from -r requirements.txt (line 11))
  Downloading pandoc-2.3.tar.gz (33 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pypandoc==1.11 (from -r requirements.txt (line 12))
  Downloading pypandoc-1.11-py3-none-any.whl (20 kB)
Collecting tqdm==4.65.0 (from -r requirements.txt (line 13))
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 2.3 MB/s eta 0:00:00
Collecting PyYAML>=5.4.1 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 4.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting SQLAlchemy<3,>=1.4 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading SQLAlchemy-2.0.16-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 24.5 MB/s eta 0:00:00
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading aiohttp-3.8.4.tar.gz (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 32.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dataclasses-json<0.6.0,>=0.5.7 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading dataclasses_json-0.5.8-py3-none-any.whl (26 kB)
Collecting langchainplus-sdk>=0.0.7 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading langchainplus_sdk-0.0.16-py3-none-any.whl (24 kB)
Collecting numexpr<3.0.0,>=2.8.4 (from langchain==0.0.197->-r requirements.txt (line 1))
  Downloading numexpr-2.8.4.tar.gz (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 3.6 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [112 lines of output]
      Collecting setuptools
        Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting oldest-supported-numpy
        Downloading oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
      Collecting numpy (from oldest-supported-numpy)
        Downloading numpy-1.25.0.tar.gz (10.4 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 33.1 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
      ERROR: Exception:
      Traceback (most recent call last):
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
          status = run_func(*args)
                   ^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
          return func(self, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 377, in run
          requirement_set = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
                                  ^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
          failure_causes = self._attempt_to_pin_criterion(name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
          criteria = self._get_updated_criteria(candidate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 230, in _get_updated_criteria
          self._add_to_criteria(criteria, requirement, parent=candidate)
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
          if not criterion.candidates:
                 ^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
          return bool(self._sequence)
                 ^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
                 ^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
                      ^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
                                             ^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
          super().__init__(
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
          self.dist = self._prepare()
                      ^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
          dist = self._prepare_distribution()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
          abstract_dist.prepare_distribution_metadata(
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
          self._install_build_reqs(finder)
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
          build_reqs = self._get_build_requires_wheel()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
          return backend.get_requires_for_build_wheel()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_internal/utils/misc.py", line 692, in get_requires_for_build_wheel
          return super().get_requires_for_build_wheel(config_settings=cs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
          return self._call_hook('get_requires_for_build_wheel', {
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
          raise BackendUnavailable(data.get('traceback', ''))
      pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
        File "/Users/kylepennell/myenv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1216, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1293, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1266, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1237, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 841, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 400, in _call_with_frames_removed
        File "/private/var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/pip-build-env-pt_74nbj/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
          import distutils.core
      ModuleNotFoundError: No module named 'distutils'
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(myenv) kylepennell@Kyles-MacBook-Pro privateGPT-main % python3 --version
Python 3.12.0b3


```

**Comment by kpennell** [comment]
ok, I installed python 3.11.4 (I think I was on a pre-release) then I created a new virtual env and now I'm getting much further along

**Comment by kpennell** [comment]
new errors

```
r olefile (pyproject.toml) ... done
  Created wheel for olefile: filename=olefile-0.46-py2.py3-none-any.whl size=35417 sha256=b0458a1e8ef0f146c21f71cc7faefdcce1959b1afa7c92e40ed49bc94a75d644
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/7a/28/c9/4745d0108b03ae5933fd107bd3946eec0d9fa794f8ce837a46
  Building wheel for red-black-tree-mod (pyproject.toml) ... done
  Created wheel for red-black-tree-mod: filename=red_black_tree_mod-1.20-py3-none-any.whl size=18623 sha256=240a737b107707449950fd11a3299edbbec8ab4ec9a3a7cce9adbe1c980173aa
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/ef/a1/4a/56417ac7cb331323b07533b8e04ec40f698d4f58e33654d743
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_ext
      creating var
      creating var/folders
      creating var/folders/n_
      creating var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp
      creating var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/kylepennell/Desktop/myenv2/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/tmplusasnoj.cpp -o var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/tmplusasnoj.o -std=c++14
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/kylepennell/Desktop/myenv2/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c /var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/tmph48a3fss.cpp -o var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/tmph48a3fss.o -fvisibility=hidden
      building 'hnswlib' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/python_bindings
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/pip-build-env-92eq_6sm/overlay/lib/python3.11/site-packages/pybind11/include -I/private/var/folders/n_/9s7r3j892cb73zbj5bnb04v00000gp/T/pip-build-env-92eq_6sm/overlay/lib/python3.11/site-packages/numpy/core/include -I./hnswlib/ -I/Users/kylepennell/Desktop/myenv2/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c ./python_bindings/bindings.cpp -o build/temp.macosx-10.9-universal2-cpython-311/./python_bindings/bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.7.0\" -std=c++14 -fvisibility=hidden
      clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
  Building wheel for sentence-transformers (pyproject.toml) ... done
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125926 sha256=97ffff60888af8a02eaea8c7053aab6469964aff38918a0b754cf84883ca96be
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/ff/27/bf/ffba8b318b02d7f691a57084ee154e26ed24d012b0c7805881
  Building wheel for lxml (pyproject.toml) ... done
  Created wheel for lxml: filename=lxml-4.9.2-cp311-cp311-macosx_10_9_universal2.whl size=3129869 sha256=d9e7ae360554b362cd30d64b1fd59a09ee16ec7517129abbfe5e5200aaf81d5d
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/fb/5b/f7/0a27880b4a007daeff53a196d01901627f640392b7e76e76e5
  Building wheel for python-docx (pyproject.toml) ... done
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184491 sha256=ace12d30f07f07fa3d40803273b72d86533e7ce05119f3e65679d9a79f2f23a7
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/b2/11/b8/209e41af524253c9ba6c2a8b8ecec0f98ecbc28c732512803c
  Building wheel for python-pptx (pyproject.toml) ... done
  Created wheel for python-pptx: filename=python_pptx-0.6.21-py3-none-any.whl size=470935 sha256=6f54bccb40aa0ca218b2a96c28a029b411cb86c0ee7fb7798e3e99d18597b43d
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/f4/c7/af/d1d91f3decfaa7621033f30b69a29bf0b1206005663d233e7a
  Building wheel for wrapt (pyproject.toml) ... done
  Created wheel for wrapt: filename=wrapt-1.14.1-cp311-cp311-macosx_10_9_universal2.whl size=50048 sha256=8a9cf686a3255a2cb7c66ad0fdfda451c321656d7e984c3fb499031ecb30b19b
  Stored in directory: /Users/kylepennell/Library/Caches/pip/wheels/eb/b6/fa/5ab6f4107cad63fa04c54ad78d75bb7035119bdd4f751df5ae
Successfully built llama-cpp-python pandoc compressed-rtf olefile red-black-tree-mod sentence-transformers lxml python-docx python-pptx wrapt
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
```

**Comment by tonyennis** [comment]
hnswlib is problematic. Are you running an AMD processor?

**Comment by kpennell** [comment]
macOS Monterey / Version 12.6.6 (21G646) / Processor 2.6 GHz 6-Core Intel Core i7

**Comment by tonyennis** [comment]
Try this:

https://github.com/imartinez/privateGPT/issues/302#issuecomment-1599410890

**Comment by kpennell** [comment]
thank you. This seems to work

`export HNSWLIB_NO_NATIVE=1`

https://stackoverflow.com/a/75870031
 
and now `Successfully built hnswlib`

**Comment by kpennell** [comment]
I think fixed

**Comment by Enzolp2** [comment]
> hnswlib is problematic. Are you running an AMD processor?

I'm still facing this error:

**The original error:**
   `error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120`

**Original Variables:**
> PROCESSOR_ARCHITECTURE=AMD64
> PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
> VCToolsVersion=14.34.31933
> VSCMD_ARG_HOST_ARCH=x86
> VSCMD_ARG_TGT_ARCH=x86

Inside Developer Command Prompt I run `set VSCMD_ARG_TGT_ARCH="x64"` but the error persists.
Error: `error: command C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120`

Then I tried to: 
`set VSCMD_ARG_TGT_ARCH=x64`
`set VSCMD_ARG_HOST_ARCH=x64`
`set VCToolsVersion=14.36.32532` (actual latest version installed)

Error:
    `error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120`

I noticed that even setting `VSCMD_ARG_HOST_ARCH=x64` still poiting to _Hostx86_ 

Do I have to use conda environment?
