### ISSUE TITLE
unable to injust cvs file

### ISSUE THREAD

**Issue by harivinod** [imartinez/privateGPT#762]
using windows 11 with python 3.10.5, if i put the file as .txt it loads the data but if i put it as csv i am getting below error

Creating new vectorstore
Loading documents from source_documents
Loading new documents:   0%|                              | 0/1 [00:03<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\gptmodels\privateGPT\ingest.py", line 89, in load_single_document
    return loader.load()
  File "C:\Python310\lib\site-packages\langchain\document_loaders\csv_loader.py", line 51, in load
    for i, row in enumerate(csv_reader):
  File "C:\Python310\lib\csv.py", line 111, in __next__
    row = next(self.reader)
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3388: character maps to <undefined>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\gptmodels\privateGPT\ingest.py", line 166, in <module>
    main()
  File "D:\gptmodels\privateGPT\ingest.py", line 156, in main
    texts = process_documents()
  File "D:\gptmodels\privateGPT\ingest.py", line 118, in process_documents
    documents = load_documents(source_directory, ignored_files)
  File "D:\gptmodels\privateGPT\ingest.py", line 107, in load_documents
    for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "C:\Python310\lib\multiprocessing\pool.py", line 870, in next
    raise value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3388: character maps to <undefined>

**Comment by ShadowMikado** [comment]
I have the exact same error, does anyone have a fix?

**Comment by abamrah** [comment]
make sure its .csv file and not .csv UTF-8

**Comment by marouahamdi** [comment]
any solution? i have the same error
