### ISSUE TITLE
pydantic ValidationError - none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by siames3** [imartinez/privateGPT#78]
I'm getting an error when trying to execute on google colab (this same code was working just yesterday) - may be related to updated packages?

Error message:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/content/privateGPT/ingest.py", line 7, in <module>
    from constants import CHROMA_SETTINGS
  File "/content/privateGPT/constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
```

How to reproduce the error in Google Colab:

```
!git clone https://github.com/imartinez/privateGPT
!pip install -r privateGPT/requirements.txt

!mkdir models
!cd models && wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
!cd models && wget https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

!wget https://raw.githubusercontent.com/imartinez/privateGPT/main/source_documents/state_of_the_union.txt

!python privateGPT/ingest.py state_of_the_union.txt
```

Thanks!

**Comment by siames3** [comment]
The same code seems to work if I run:

**Comment by chandujin123** [comment]
rename example.env to .env

**Comment by zuomirror** [comment]
thanks

**Comment by rabotone** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 78, in validate_environment
    values["client"] = Llama(
                       ^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\llama_cpp\llama.py", line 153, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: models/ggml-model-q4_0.bin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\privateGPT-main\ingest.py", line 35, in <module>
    main()
  File "G:\privateGPT-main\ingest.py", line 28, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Program Files\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: models/ggml-model-q4_0.bin
Exception ignored in: <function Llama.__del__ at 0x000002AE4688C040>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\llama_cpp\llama.py", line 978, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by TrixCoder** [comment]
> 
!pip install -r privateGPT/requirements.txt

!mkdir models
!cd models && wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin
!cd models && wget https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

!wget https://raw.githubusercontent.com/imartinez/privateGPT/main/source_documents/state_of_the_union.txt

Use this and transfer all the files into privateGPT folder in the below format
![image](https://github.com/imartinez/privateGPT/assets/17105303/728cf9ac-a4d2-401c-ac6b-a2ad18ce6ca2)

Then try to run the file after going inside privateGPT folder like: "~/Downloads/privateGPT$ python3 ingest.py state_of_the_union.txt". It should fix the issue.

**Comment by joru10** [comment]
I am getting also this error after completing an ingestion of 944 files...

Traceback (most recent call last):
  File "c:\Users\jose\privateGPT\ingest.py", line 97, in <module>
    main()
  File "c:\Users\jose\privateGPT\ingest.py", line 88, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jose\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\embeddings\huggingface.py", line 44, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_name
  none is not an allowed value (type=type_error.none.not_allowed)
  
  Ideas?
