### ISSUE TITLE
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

### ISSUE THREAD

**Issue by anishgoswami10** [imartinez/privateGPT#802]
Enter a query: "Who is the president of Ukraine?" 
Traceback (most recent call last):
  File "C:\Users\ASUS\Documents\gpt\privateGPT\privateGPT.py", line 86, in <module>
    main()
  File "C:\Users\ASUS\Documents\gpt\privateGPT\privateGPT.py", line 57, in main
    res = qa(query)
          ^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\retrieval_qa\base.py", line 120, in _call
    answer = self.combine_documents_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 293, in run
    return self(kwargs, callbacks=callbacks, tags=tags)[_output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\combine_documents\base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\combine_documents\stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\chains\llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\base.py", line 141, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\base.py", line 227, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\base.py", line 178, in _generate_helper
    raise e
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\base.py", line 165, in _generate_helper
    self._generate(
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\base.py", line 525, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages\langchain\llms\gpt4all.py", line 208, in _call
    for token in self.client.generate(prompt, **params):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

=================================================================================

Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
A clear and concise description of what the bug is and the steps to reproduce the behavior.

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: [e.g. macOS 12.6 / M1]
 - Python version [e.g. 3.11.3]
- Other relevant information

**Additional context**

**Comment by LeoArtaza** [comment]
> Which versions of Langchain and gpt4all you are using? Newer versions then mentioned in requirements.txt seem to have this effect. I solved it by desinstalling those packages and reïnstalling them with the version mentioned.

Same here but why is it happening? I personally searched and found nothing yet.

**Comment by LeoArtaza** [comment]
I just found this PR that solves the problem: https://github.com/hwchase17/langchain/pull/7093

**Comment by rlancemartin** [comment]
Yes, I also hit this yesterday and put up a PR to resolve:

https://github.com/hwchase17/langchain/pull/7093
