### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 2150: invalid continuation byte

### ISSUE THREAD

**Issue by ne0YT** [imartinez/privateGPT#807]
**Describe the bug and how to reproduce it**
I used my own .csv file with it. while running the ingest.py it fails to load:
python ingest.py
Creating new vectorstore
Loading documents from source_documents
Loading new documents:   0%|                              | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/privateGPT/ingest.py", line 89, in load_single_document
    return loader.load()
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/csv_loader.py", line 51, in load
    for i, row in enumerate(csv_reader):
  File "/usr/lib/python3.10/csv.py", line 110, in __next__
    self.fieldnames
  File "/usr/lib/python3.10/csv.py", line 97, in fieldnames
    self._fieldnames = next(self.reader)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 2150: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/privateGPT/ingest.py", line 166, in <module>
    main()
  File "/opt/privateGPT/ingest.py", line 156, in main
    texts = process_documents()
  File "/opt/privateGPT/ingest.py", line 118, in process_documents
    documents = load_documents(source_directory, ignored_files)
  File "/opt/privateGPT/ingest.py", line 107, in load_documents
    for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 2150: invalid continuation byte

**Expected behavior**

**Environment (please complete the following information):**
 - OS / hardware: virtualized Linux using KVM 12 cores 12 GB RAM
 - Python version 3.11.3

**Comment by ne0YT** [comment]
I cannot share the document I used.

**Comment by ne0YT** [comment]
after converting it to UTF8 it results in:
https://github.com/hwchase17/langchain/issues/2074
