### ISSUE TITLE
how can i run it?

### ISSUE THREAD

**Issue by whoisliinh** [imartinez/privateGPT#82]

**Comment by Abhinavcode13** [comment]
What's the issue?

**Comment by rabotone** [comment]
Traceback (most recent call last):
  File "G:\privateGPT-main\ingest.py", line 7, in <module>
    from constants import CHROMA_SETTINGS
  File "G:\privateGPT-main\constants.py", line 11, in <module>
    CHROMA_SETTINGS = Settings(
                      ^^^^^^^^^
  File "pydantic\env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
persist_directory
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by zuomirror** [comment]
Rename example.env to .env and edit the variables appropriately.

**Comment by rabotone** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 78, in validate_environment
    values["client"] = Llama(
                       ^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\llama_cpp\llama.py", line 153, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: models/ggml-model-q4_0.bin

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\privateGPT-main\ingest.py", line 35, in <module>
    main()
  File "G:\privateGPT-main\ingest.py", line 28, in main
    llama = LlamaCppEmbeddings(model_path=llama_embeddings_model, n_ctx=model_n_ctx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Program Files\Python311\Lib\site-packages\langchain\embeddings\llamacpp.py", line 98, in validate_environment
    raise NameError(f"Could not load Llama model from path: {model_path}")
NameError: Could not load Llama model from path: models/ggml-model-q4_0.bin
Exception ignored in: <function Llama.__del__ at 0x000002AE4688C040>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\llama_cpp\llama.py", line 978, in __del__
    if self.ctx is not None:
       ^^^^^^^^
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by rabotone** [comment]
how to edit the variables appropriately.

**Comment by rabotone** [comment]
@zuomirror

**Comment by zuomirror** [comment]
@rabotone 
![image](https://github.com/imartinez/privateGPT/assets/18322275/ac3a58fa-92ce-48a9-beb2-1c5442a1f2c7)
PERSIST_DIRECTORY=db
LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin
MODEL_TYPE=GPT4All
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
MODEL_N_CTX=1000

**Comment by rabotone** [comment]
> @rabotone ![图像](https://user-images.githubusercontent.com/18322275/238115061-ac3a58fa-92ce-48a9-beb2-1c5442a1f2c7.png) PERSIST_DIRECTORY=db LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin MODEL_TYPE=GPT4All MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin MODEL_N_CTX=1000

Can you only use linux? Can you use windows

**Comment by rabotone** [comment]
@zuomirror

**Comment by andreakiro** [comment]
You need to provide the absolute path to your `LLAMA` model in the `.env` file. See #68 for details.

**Comment by j4acks0n** [comment]
Isn't It Already Explained?

**Comment by IamHellToday** [comment]
I am getting this error, although I have set up all as zuomirror did.

<img width="580" alt="image" src="https://github.com/imartinez/privateGPT/assets/20611522/fd698c7d-5a54-4b2e-8085-2133ae808eee">

**Comment by j4acks0n** [comment]
> Rename example.env to .env and edit the variables appropriately.

I Think Conda Is Better Right? 🤔

**Comment by j4acks0n** [comment]
> I am getting this error, although I have set up all as zuomirror did.
> 
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/20611522/238151949-fd698c7d-5a54-4b2e-8085-2133ae808eee.png">

Make Sure Your Spell Is Correct,Haven't You? 
Or Reinstall It

**Comment by IamHellToday** [comment]
All solved now - guys keep your python updated, lol.
