### ISSUE TITLE
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

### ISSUE THREAD

**Issue by fcbfcb** [imartinez/privateGPT#844]
**Environment (please complete the following information):**
- MacOS Catalina (10.15.7) on Intel Mac
- Python 3.10

**Expected behavior**
I intended to test one of the queries offered by example, and got the error below:
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

**Describe the bug and how to reproduce it**

The out-of-shelf installation from here didn't work, as I was getting an dlopen OSError similar to the one described here:
[884](https://github.com/nomic-ai/gpt4all/issues/884)

"Referenced from: /Users/user/miniconda3/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.dylib (which was built for Mac OS X 12.6)
Expected in: /usr/lib/libc++.1.dylib"

I used the git submodules update --recursive command and installed gpt4all (as described [here](https://github.com/nomic-ai/gpt4all/tree/f4a1f7340c76e7d925035fda89315aaeb69f09f0/gpt4all-bindings/python) and I noticed that the previous gpt4all installation under /Users/florentin/miniconda3/lib/python3.10/gpt4all changed, but at this point, the initial dlopen OSError went away, I was able to load the model and enter a query (see below), but the process failed with a new error:

"TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'"

Ant ideas how to go around this?

Thanks!

**Additional context**

Here is the full output:

(base) Mon 2023.07.10 19:12:25 florentin@Brutus:~/privateGPT > python3 privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: db
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin
objc[26340]: Class GGMLMetalClass is implemented in both /Users/florentin/gpt4all/gpt4all-bindings/python/gpt4all/llmodel_DO_NOT_MODIFY/build/libreplit-mainline-metal.dylib (0x14cc51648) and /Users/florentin/gpt4all/gpt4all-bindings/python/gpt4all/llmodel_DO_NOT_MODIFY/build/libllamamodel-mainline-metal.dylib (0x14cee16b8). One of the two will be used. Which one is undefined.
gptj_model_load: loading model from 'models/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
gptj_model_load: kv self size  =  896.00 MB
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285

Enter a query: what's the name of the pandemic that kept everyone appart
Traceback (most recent call last):
  File "/Users/florentin/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/Users/florentin/privateGPT/privateGPT.py", line 54, in main
    res = qa(query)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py", line 120, in _call
    answer = self.combine_documents_chain.run(
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 259, in run
    return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/chains/llm.py", line 79, in generate
    return self.llm.generate_prompt(
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 138, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 201, in generate
    raise e
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 193, in generate
    self._generate(
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/llms/base.py", line 488, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/Users/florentin/miniconda3/lib/python3.10/site-packages/langchain/llms/gpt4all.py", line 208, in _call
    for token in self.client.generate(prompt, **params):
TypeError: GPT4All.generate() got an unexpected keyword argument 'n_ctx'

**Comment by adrisalcedo00** [comment]
GPT4All has remove the "n_ctx" argument recently and replaced by "max_tokens" argument. You can upgrade GPT4All and LangChain packages  (I recomend reinstall langchain from github: pip install git+https://github.com/hwchase17/langchain.git) and replace n_ctx by max_tokens.

**Comment by adrisalcedo00** [comment]
> > GPT4All has remove the "n_ctx" argument recently and replaced by "max_tokens" argument. You can upgrade GPT4All and LangChain packages (I recomend reinstall langchain from github: pip install git+https://github.com/hwchase17/langchain.git) and replace n_ctx by max_tokens.
> 
> how do i change n_ctx to max_tokens on the model?


I mean the name of the argument in the constructor `GPT4ALL`.
