### ISSUE TITLE
Not supporting llama model

### ISSUE THREAD

**Issue by Vignesh1489** [imartinez/privateGPT#872]
**Describe the bug and how to reproduce it**
Privategpt.py is not working with llama models. i have tried with llama 1 & llama2 throwing error. I have updated the llama model name in .env but still its not working

**Expected behavior**
PrivateGPT is expected to work as it works like GPT4All models

**Environment (please complete the following information):**
 - OS / hardware: [RHEL 9]
 - Python version [e.g. 3.10]
- Other relevant information

Error:
Traceback (most recent call last):
  File "/home/ec2-user/chatbot/privategpt.py", line 83, in <module>
    main()
  File "/home/ec2-user/chatbot/privategpt.py", line 35, in main
    llm = LlamaCpp(model=model_path, n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/home/ec2-user/.local/lib/python3.9/site-packages/langchain/llms/llamacpp.py", line 112, in validate_environment
    model_path = values["model_path"]
KeyError: 'model_path'

**Comment by Charles4code** [comment]
I know very little about it.
to my understanding, privateGPT only supports GPT4All and LlammaCpp.
it cannot directly use large model, such as LLaMMa or llamma2.
We need wait for GPT4All to upgrade to LLamma2.
