### ISSUE TITLE
I got a Traceback error while running privateGPT on Ubuntu 22.04

### ISSUE THREAD

**Issue by denniswksit** [imartinez/privateGPT#875]
While running privateGPT.py, the error started after "gptj_model_load: model size = 3609.38 MB / num tensors = 285". The error reads as follows:

Traceback (most recent call last):
  File "/home/dennis/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/home/dennis/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/home/dennis/.local/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
n_ctx
  extra fields not permitted (type=value_error.extra)

I have no idea what's happening here. Could anyone be able to fix it so that I can try privateGPT on my Ubuntu 22.04 on an old iMac late 2012?

**Comment by r0n0c** [comment]
`pip3 uninstall langchain`
`pip3 install langchain==0.0.197` 
and try again

**Comment by donshifu** [comment]
you need gpt4all at version 0.3.6, i recently try with this, and this is ok

pip install langchain==0.0.220 gpt4all==0.3.6

**Comment by thebetauser** [comment]
https://github.com/imartinez/privateGPT/issues/865#issuecomment-1644360071

**Comment by denniswksit** [comment]
Thank you very much! I finally resolved the problem. I have adopted Imatinez's solution, that is to change  “n_ctx=model_n_ctx“, in line 38 main() into “max_tokens=model_n_ctx”. It works!

**Comment by SamuraiDjvak** [comment]
I don't have that sucsses with this I tried also with old requirements and also not working.
Traceback (most recent call last):
  File "C:\Users\GankZilla\Desktop\PrivateGpt\privateGPT.py", line 83, in <module>
    main()
  File "C:\Users\GankZilla\Desktop\PrivateGpt\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GankZilla\Desktop\PrivateGpt\env\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for GPT4All
max_tokens
  extra fields not permitted (type=value_error.extra)
__root__
  Failed to retrieve model (type=value_error)
  
  
  please help.
