### ISSUE TITLE
Poetry Requirements Missing Sentence Transformers

### ISSUE THREAD

**Issue by MichaelSebero** [imartinez/privateGPT#876]
**Running [ cd privateGPT && poetry run python privateGPT.py ] gives this error**

Traceback (most recent call last):
  File "/home/user/.cache/pypoetry/virtualenvs/privategpt-_FLeM6AB-py3.11/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 51, in __init__
    import sentence_transformers
ModuleNotFoundError: No module named 'sentence_transformers'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/home/user/privateGPT/privateGPT.py", line 28, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/privategpt-_FLeM6AB-py3.11/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 54, in __init__
    raise ImportError(
ImportError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.

**Expected behavior**
I expected to load the program through poetry.

**Environment (please complete the following information):**
 - OS / hardware: [Linux]
 - Python version [3.11.3]

**Comment by TerminatedProcess** [comment]
In the meantime, I guess poetry add sentence_transformers..

**Comment by AITEK-DEV** [comment]
Error

Traceback (most recent call last):
File "/home/user/.cache/pypoetry/virtualenvs/privategpt-_FLeM6AB-py3.11/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 51, in import_sentence_transformers
raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'sentence_transformers'

Here's the Explanation

The error occurs because the `sentence_transformers` module is not installed in your virtual environment. Please install it first using `pip install sentence_transformers`. Once you have the module installed, try running the script again.

Regarding the Expected Behavior

The program was expected to load through poetry.

Try this:

Install the `sentence_transformers` module by running the command `pip install sentence_transformers`. Once the module is installed, run the script again.

If you encounter the error again, verify that you are using the correct version of Python. The script requires Python 3.11 or later.

I hope this helps.

**Comment by TerminatedProcess** [comment]
Thank you for your reply! Just to clarify, I opened this issue because Sentence_transformers was not part of pyproject.toml. When I manually added with poetry, it still didn't work unless I added it with pip instead of poetry. I do have the project running correctly though. Just wanted to make sure that you guys were aware of this issue. Thanks!

**Comment by TiagoGouvea** [comment]
The only solution that worked for me was: `conda install -c conda-forge sentence-transformers` from issue [843](https://github.com/UKPLab/sentence-transformers/issues/843#issuecomment-1205085561)

**Comment by ThomasVuillaume** [comment]
On my side I had this error : 

```
Traceback (most recent call last):
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.server.ingest.ingest_service.IngestService'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 798, in get
    return self._context[key]
           ~~~~~~~~~~~~~^^^^^
KeyError: <class 'private_gpt.components.embedding.embedding_component.EmbeddingComponent'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\llama_index\embeddings\huggingface.py", line 50, in __init__
    from transformers import AutoModel, AutoTokenizer
ModuleNotFoundError: No module named 'transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vuith\GitRepositories\privateGPT\private_gpt\__main__.py", line 5, in <module>
    from private_gpt.main import app
  File "C:\Users\vuith\GitRepositories\privateGPT\private_gpt\main.py", line 124, in <module>
    PrivateGptUi().mount_in_app(app)
    ^^^^^^^^^^^^^^
  File "C:\Users\vuith\GitRepositories\privateGPT\private_gpt\ui\ui.py", line 28, in __init__
    self._ingest_service = root_injector.get(IngestService)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 1031, in call_with_injection
    dependencies = self.args_to_inject(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 1079, in args_to_inject
    instance: Any = self.get(interface)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 974, in get
    provider_instance = scope_instance.get(interface, binding.provider)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 91, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 800, in get
    instance = self._get_instance(key, provider, self.injector)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 811, in _get_instance
    return provider.get(injector)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 264, in get
    return injector.create_object(self._cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 998, in create_object
    self.call_with_injection(init, self_=instance, kwargs=additional_kwargs)
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\injector\__init__.py", line 1040, in call_with_injection
    return callable(*full_args, **dependencies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\GitRepositories\privateGPT\private_gpt\components\embedding\embedding_component.py", line 19, in __init__
    self.embedding_model = HuggingFaceEmbedding(
                           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vuith\AppData\Local\pypoetry\Cache\virtualenvs\private-gpt-cN6b2GW5-py3.11\Lib\site-packages\llama_index\embeddings\huggingface.py", line 52, in __init__
    raise ImportError(
ImportError: HuggingFaceEmbedding requires transformers to be installed.
Please install transformers with `pip install transformers`.
```

I tried `pip install transformers` as suggested, but I had to use `poetry add transformers` instead to get rid of the error
