### ISSUE TITLE
Getting Error: OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by Kunalgroy** [imartinez/privateGPT#878]
Full Error Code: 
`Traceback (most recent call last):
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/langchain/llms/gpt4all.py", line 130, in validate_environment
    from gpt4all import GPT4All as GPT4AllModel
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import GPT4All  # noqa
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/gpt4all/gpt4all.py", line 13, in <module>
    from . import pyllmodel
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 57, in <module>
    llmodel = load_llmodel_library()
  File "/app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 52, in load_llmodel_library
    llmodel_lib = ctypes.CDLL(llmodel_dir)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /app/home_ext/testuser/gen-ai/gpt/privateGPT/venv/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)`

While running: `python3.10 privateGPT.py`
All modules are properly installed under virtual environment.

System Details:
Linux cloudserver 4.18.0-477.15.1.el8_8.x86_64 #1 SMP Fri Jun 2 08:27:19 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
RHEL8

**Comment by chunhualiao** [comment]
I saw the same problem when running talk-codebase which in turn uses gpt4all.

**Comment by mvnpavan** [comment]
Any update on this bug?

**Comment by chunhualiao** [comment]
I switched to a macbook pro laptop instead and the program disappears. I think RHEL 8 is too old and did not bother to upgrade g++ etc. for now.

**Comment by gwd666** [comment]
RHEL 8 does not support (/include) GLIBCXX_3.4.26; 
so far only viable solution I found would be to update to RHEL 9
