### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by JSVJ** [imartinez/privateGPT#893]
Thanks for this beautiful repository. I am able to ingest some documents but when I try to run python privateGPT.py it is always showing this access violation error. Kindly advice is it related to problem with my system or something else?

```
`(gpt_venv) PS D:\Generative_Text\privateGPT> python .\privateGPT.py
Using embedded DuckDB with persistence: data will be stored in: D:\Generative_Text\persist_directory
Found model file at  D:\\Generative_Text\\ggml-gpt4all-j-v1.3-groovy.bin
gptj_model_load: loading model from 'D:\\Generative_Text\\ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 5401.45 MB
Traceback (most recent call last):
  File "D:\Generative_Text\privateGPT\privateGPT.py", line 83, in <module>
    main()
  File "D:\Generative_Text\privateGPT\privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "D:\Generative_Text\gpt_venv\Lib\site-packages\langchain\llms\gpt4all.py", line 147, in validate_environment
    values["client"] = GPT4AllModel(
                       ^^^^^^^^^^^^^
  File "D:\Generative_Text\gpt_venv\Lib\site-packages\gpt4all\gpt4all.py", line 41, in __init__
    self.model.load_model(model_dest)
  File "D:\Generative_Text\gpt_venv\Lib\site-packages\gpt4all\pyllmodel.py", line 151, in load_model
    llmodel.llmodel_loadModel(self.model, model_path_enc)
OSError: exception: access violation reading 0x00000095599F0000`
```

**Comment by msizec** [comment]
Same here
