### ISSUE TITLE
Error while building the PrivateGPT Docker Image on Ubuntu 

### ISSUE THREAD

**Issue by Deepansharora27** [imartinez/privateGPT#894]
Note: if you'd like to *ask a question* or *open a discussion*, head over to the [Discussions](https://github.com/imartinez/privateGPT/discussions) section and post it there.

**Describe the bug and how to reproduce it**
When I am trying to build the Dockerfile provided for PrivateGPT, I get the Following Error: 

```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
The command '/bin/sh -c cd home     && git clone https://github.com/imartinez/privateGPT.git     && cd privateGPT     && pip install -r requirements.txt' returned a non-zero code: 2
```

**Expected behavior**
The Error Should Not Prevail 

**Environment (please complete the following information):**
 - OS / hardware: Ubuntu 18.04 LTS 
 - Python version 3.6.9 
- Other relevant information

**Additional context**

**Comment by ianpurton** [comment]
@Deepansharora27 What dockerfile are you using?

**Comment by Deepansharora27** [comment]
@ianpurton This is the Dockerfile: 

```
FROM ubuntu:latest

RUN apt-get update -qq && apt-get install -y \
    git \
    python3 \
    python-is-python3 \
    pip \
    wget

RUN cd home \
    && git clone https://github.com/imartinez/privateGPT.git \
    && cd privateGPT \
    && pip install -r requirements.txt

# put these back as single line; split here for readability:
RUN echo "PERSIST_DIRECTORY=db\n LLAMA_EMBEDDINGS_MODEL=models/ggml-model-q4_0.bin\n MODEL_TYPE=GPT4All\n MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin\n MODEL_N_CTX=1000" > home/privateGPT/.env \
    && chmod a+x home/privateGPT/.env

RUN mkdir home/privateGPT/models \
    && cd home/privateGPT/models \
    && wget https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin \
    && wget https://huggingface.co/Pi3141/alpaca-native-7B-ggml/resolve/397e872bf4c83f4c642317a5bf65ce84a105786e/ggml-model-q4_0.bin

```

**Comment by ianpurton** [comment]
On the front page the system requirements state that a c++ compiler is required. Might that be the issue?

**Comment by Deepansharora27** [comment]
@ianpurton Just checked, already have it : 

```
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ianpurton** [comment]
There's also this big PR https://github.com/imartinez/privateGPT/pull/120

Maybe that helps. Sorry, I'm not a maintainer here, I was just passing by.
