### ISSUE TITLE
Error while "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by DivyBajpai** [imartinez/privateGPT#895]
Unable to connect optimized C data functions [No module named '_testbuffer'], falling back to pure Python
Found model file at  models/ggml-gpt4all-j-v1.3-groovy.bin

**Comment by conacts** [comment]
Could you elaborate on your issue?
1. What is your OS and version?
2. What is your python version?
3. Did you use a virtual enviornment?

**Comment by tounsicorp** [comment]
Same here.  Always crashes and fails at (pyproject.toml) - while trying to prepare metadata.

**Comment by tounsicorp** [comment]
> 



Just for the additional info.  I'm on Windows 10 pro.  python is on 3.11.4.  And the venv or not, it won't work.

**Comment by tounsicorp** [comment]
This is what I get.  

  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      Traceback (most recent call last):
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 81, in __getattr__
          return next(
                 ^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 82, in <genexpr>
          ast.literal_eval(value)
        File "directory_where it needs to be\\Local\Programs\Python\Python311\Lib\ast.py", line 110, in literal_eval
          return _convert(node_or_string)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Programs\Python\Python311\Lib\ast.py", line 109, in _convert
          return _convert_signed_num(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Programs\Python\Python311\Lib\ast.py", line 83, in _convert_signed_num
          return _convert_num(node)
                 ^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Programs\Python\Python311\Lib\ast.py", line 74, in _convert_num
          _raise_malformed_node(node)
        File "directory_where it needs to be\\Local\Programs\Python\Python311\Lib\ast.py", line 71, in _raise_malformed_node
          raise ValueError(msg + f': {node!r}')
      ValueError: malformed node or string on line 2: <ast.Call object at 0x000001E94A1F5330>
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 191, in read_attr
          return getattr(StaticModule(module_name, spec), attr_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 87, in __getattr__
          raise AttributeError(f"{self.name} has no attribute {attr}") from e
      AttributeError: wrapt has no attribute __version__
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "D:\GPT\gpt\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>      
          main()
        File "D:\GPT\gpt\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\GPT\gpt\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 41, in <module>
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\__init__.py", line 
107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 159, in setup
          dist.parse_config_files()
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\dist.py", line 894, in parse_config_files
          setupcfg.parse_configuration(
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 189, in parse_configuration
          meta.parse()
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 500, in parse
          section_parser_method(section_options)
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 475, in parse_section
          self[name] = value
          ~~~~^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 293, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 606, in _parse_version
          return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in _parse_attr
          return expand.read_attr(attr_desc, package_dir, root_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 194, in read_attr
          module = _load_spec(spec, module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "directory_where it needs to be\\Local\Temp\pip-build-env-rmqkt6ge\overlay\Lib\site-packages\setuptools\config\expand.py", 
line 214, in _load_spec
          spec.loader.exec_module(module)  # type: ignore
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap_external>", line 940, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "directory_where it needs to be\\Local\Temp\pip-install-t94fhfm6\wrapt_064fb97cb47e4fefb5b7b45c18437bdd\src\wrapt\__init__.py", line 10, in <module>
          from .decorators import (adapter_factory, AdapterFactory, decorator,
        File "directory_where it needs to be\\Local\Temp\pip-install-t94fhfm6\wrapt_064fb97cb47e4fefb5b7b45c18437bdd\src\wrapt\decorators.py", line 34, in <module>
          from inspect import ismethod, isclass, formatargspec
      ImportError: cannot import name 'formatargspec' from 'inspect' (C:\Users\winan\AppData\Local\Programs\Python\Python311\Lib\inspect.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by AndrewsPanda** [comment]
I am also getting this issue on both windows and linux

**Comment by jjaaybee** [comment]
From GPT:
The error message indicates that there is an issue with the wrapt package installation. The root cause appears to be an incompatibility between the version of the wrapt package you are trying to install and Python 3.11.

Since the error occurs during the package metadata generation, it's likely that the wrapt package is not compatible with Python 3.11, specifically due to the removal of the formatargspec function from the inspect module in Python 3.11.

**Comment by jjaaybee** [comment]
"The error you encountered seems to be related to an issue with the wrapt package, which is a dependency of your project. The error specifically points to an ImportError that occurred during the import of the formatargspec function from the inspect module."

Seems formatargspec was replaced by signature? Updated Wrapt to no avail.

**Comment by arcbra** [comment]
I had the same error. i managed to solve it upgrating pip, setuptools and wheel:
```shell
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade setuptools wheel
```

**Comment by moztech** [comment]
For the benefit of others, my workaround was to add a working wrapt version to the requirements.txt i.e.
`echo "wrapt==1.14.0">> requirements.txt`   

Then install as normal via `pip3 install -r requirements.txt`
