### ISSUE TITLE
ingest.py failed with SSLError

### ISSUE THREAD

**Issue by SmileXie** [imartinez/privateGPT#897]
**Describe the bug and how to reproduce it**
I got SSLError when executing `python3 ingest.py` with following log. 

privateGPT claims it is able to run **offline**. However it seems that there is still a connection is to `huggingface.co`.
May I use it **real offline** ?

```
$ python3 ingest.py 
Traceback (most recent call last):
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rj-vran/privateGPT/ingest.py", line 166, in <module>
    main()
  File "/home/rj-vran/privateGPT/ingest.py", line 143, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 59, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/rj-vran/privateGPT/.privategpt_env/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))"), '(Request ID: 85a4bf57-31b5-404d-94d8-dff23ce2833e)')
```

**Expected behavior**
Run `python3 ingest.py` withou errors.

**Environment (please complete the following information):**
 - Ubuntu 22.04.2 LTS
 - Python 3.10.6
 - In a venv context

**Comment by SmileXie** [comment]
Note: because of the way langchain loads the SentenceTransformers embeddings, the first time you run the script it will require internet connection to download the embeddings model itself.

i took notice of this upper paragraph in readme.md,
And the ssl connection error is caused by my environment.
