### ISSUE TITLE
Unable to run privateGPT.py 

### ISSUE THREAD

**Issue by Zaheer-10** [imartinez/privateGPT#959]
(pdf_env) C:\Users\--\PRIVATE_GPT\privateGPT>py privateGPT.py
C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Traceback (most recent call last):
  File "C:\Users\soulo\PRIVATE_GPT\privateGPT\privateGPT.py", line 85, in <module>
    main()
  File "C:\Users\--\PRIVATE_GPT\privateGPT\privateGPT.py", line 31, in main
    db = Chroma(persist_directory=persist_directory, embedding_function=embeddings, client_settings=CHROMA_SETTINGS)
  File "C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 120, in __init__
    self._client = chromadb.Client(_client_settings)
  File "C:\Users\==\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\__init__.py", line 140, in Client
    system = System(settings)
  File "C:\Users\==\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\config.py", line 175, in __init__
    if settings[key] is not None:
  File "C:\Users\==\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\config.py", line 110, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Comment by Zaheer-10** [comment]
I resolved the problem with Chroma by reinstalling an older version .
