### ISSUE TITLE
Command "python privateGPT.py" not working

### ISSUE THREAD

**Issue by sghosh37** [imartinez/privateGPT#972]
### Discussed in https://github.com/imartinez/privateGPT/discussions/971

<div type='discussions-op-text'>

<sup>Originally posted by **sghosh37** August 22, 2023</sup>
Getting the below error while executing the command 
#:~/chatGPT/privateGPT$ python privateGPT.py
Traceback (most recent call last):
  File "/home/sumang/chatGPT/privateGPT/privateGPT.py", line 83, in <module>
    main()
  File "/home/sumang/chatGPT/privateGPT/privateGPT.py", line 38, in main
    llm = GPT4All(model=model_path, max_tokens=model_n_ctx, backend='gptj', n_batch=model_n_batch, callbacks=callbacks, verbose=False)
  File "/home/sumang/.local/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "/home/sumang/.local/lib/python3.10/site-packages/pydantic/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/home/sumang/.local/lib/python3.10/site-packages/pydantic/main.py", line 1102, in validate_model
    values = validator(cls_, values)
  File "/home/sumang/.local/lib/python3.10/site-packages/langchain/llms/gpt4all.py", line 130, in validate_environment
    from gpt4all import GPT4All as GPT4AllModel
  File "/home/sumang/.local/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module>
    from . import gpt4all # noqa
  File "/home/sumang/.local/lib/python3.10/site-packages/gpt4all/gpt4all.py", line 6, in <module>
    from . import pyllmodel
  File "/home/sumang/.local/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 39, in <module>
    llmodel, llama = load_llmodel_library()
  File "/home/sumang/.local/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
    llama_lib = ctypes.CDLL(llama_dir, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sumang/.local/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.so: cannot open shared object file: No such file or directory

#:~/chatGPT/privateGPT$ python --version
Python 3.10.12

All packages are installed successfully. Except gpt4all==1.0.3. Version 1.0.3 was not available. Got the below error. Hence installed version 0.1.7

#:~/chatGPT/privateGPT$ pip3 install gpt4all==1.0.3
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement gpt4all==1.0.3 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==1.0.3

I am using ubuntu on ARM64</div>

**Comment by RickardAhlstedt** [comment]
Having a similiar issue, trying to run it on a docker-container built on ubuntu 22 with python 3.10.12:

root@81bcff9b4c02:/src# pip3 install -r requirements.txt 
Collecting langchain==0.0.274
  Downloading langchain-0.0.274-py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement gpt4all==1.0.8 (from versions: 0.1.5, 0.1.6, 0.1.7)
ERROR: No matching distribution found for gpt4all==1.0.8

Host-machine is a Macbook pro M2 Pro

**Comment by minixxie** [comment]
> Having a similiar issue, trying to run it on a docker-container built on ubuntu 22 with python 3.10.12:
> 
> root@81bcff9b4c02:/src# pip3 install -r requirements.txt Collecting langchain==0.0.274 Downloading langchain-0.0.274-py3-none-any.whl (1.6 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.6 MB/s eta 0:00:00 ERROR: Could not find a version that satisfies the requirement gpt4all==1.0.8 (from versions: 0.1.5, 0.1.6, 0.1.7) ERROR: No matching distribution found for gpt4all==1.0.8
> 
> Host-machine is a Macbook pro M2 Pro

I faced the same issue today. After searching on the https://pypi.org/project/gpt4all/1.0.8/#files , I believe it's due to the fact that the built distributions for gpt4all only have x86_64 for Linux (your guest OS which runs docker). I'm going to try emulating x86_64 with colima + rosetta, see if it works.
