### ISSUE TITLE
Issue when ingesting PDFs

### ISSUE THREAD

**Issue by iainvdp** [imartinez/privateGPT#976]
Description:
Following issue occurs when running ingest.py on PDF documents uploaded to source documents

Appending to existing vectorstore at db
Loading documents from source_documents
Loading new documents:   0%|                              | 0/1 [00:03<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/document_loaders/pdf.py", line 297, in __init__
    import fitz  # noqa:F401
    ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fitz/__init__.py", line 22, in <module>
    from fitz.fitz import *
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fitz/fitz.py", line 14, in <module>
    from . import _fitz
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fitz/_fitz.so, 0x0002): tried: '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fitz/_fitz.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/iainvanderpost/Desktop/gpt_project/privateGPT/ingest.py", line 88, in load_single_document
    loader = loader_class(file_path, **loader_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/document_loaders/pdf.py", line 299, in __init__
    raise ImportError(
ImportError: `PyMuPDF` package not found, please install it with `pip install pymupdf`
"""

Environment:
 - OS / hardware: macOS 12.5.1 / M1
 - Python version e.g. 3.11.4

**Additional context**
Have successfully installed pymupdf but same error persists.

Any assistance would be greatly appreciated.

Thanks,

**Comment by 0xcabrex** [comment]
I believe the command 

`pip install pymupdf`

Must solve the error

**Comment by SuperCowboyDinosaur** [comment]
> I believe the command
> 
> `pip install pymupdf`
> 
> Must solve the error

it doesnt. but also the original comment already says that it persists after installing.

**Comment by SuperCowboyDinosaur** [comment]
i'm finding the same issue 
m2 same os.

**Comment by SuperCowboyDinosaur** [comment]
i seem to get away by adding import fitz at the top (this is the actual module name) and uninstalling and re-installing pymupdf (i.e. pip uninstall pymupdf and pip install pymupdf , to ensure the arm version is being used) 
answer here if it works for you, for future reference!

**Comment by thiagobapti** [comment]
> i seem to get away by adding import fitz at the top (this is the actual module name) and uninstalling and re-installing pymupdf (i.e. pip uninstall pymupdf and pip install pymupdf , to ensure the arm version is being used) answer here if it works for you, for future reference!

"pip uninstall pymupdf and pip install pymupdf " worked for me
Thanks

**Comment by iainvdp** [comment]
Hey all install pymupdf v 1.22.5 and fixed issue.

**Comment by mick-spc** [comment]
had to uninstall pymudpf and install 1.22.5 and it worked.

**Comment by prosuvinhere** [comment]
> i seem to get away by adding import fitz at the top (this is the actual module name) and uninstalling and re-installing pymupdf (i.e. pip uninstall pymupdf and pip install pymupdf , to ensure the arm version is being used) answer here if it works for you, for future reference!

which file should import be added

**Comment by prosuvinhere** [comment]
okay, so I encountered a different problem I had installed using Brew and also installed the direct-way.
you need to uninstall both of the pymupdf and then reinstall only using the direct method.
brew has an older version of pymupdf so it will not work.
avoid brew.

**Comment by prosuvinhere** [comment]
this is happening because of the duplication of files
use comand 
pip3 uninstall PyMuPDFb
to uninstall duplicate

**Comment by williamtu** [comment]
I uninstall and install pymupdf, but then hit another issue
```
                              | 0/1 [00:02<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/witu/Downloads/privateGPT/ingest.py", line 92, in load_single_document
    return loader.load()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/pdf.py", line 311, in load
    return parser.parse(blob)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/base.py", line 95, in parse
    return list(self.lazy_parse(blob))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/parsers/pdf.py", line 60, in lazy_parse
    doc = fitz.open(file_path)  # open document
          ^^^^^^^^^
AttributeError: module 'fitz' has no attribute 'open'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/witu/Downloads/privateGPT/ingest.py", line 185, in <module>
    main()
  File "/Users/witu/Downloads/privateGPT/ingest.py", line 164, in main
    documents = process_documents([metadata['source'] for metadata in collection['metadatas']])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/witu/Downloads/privateGPT/ingest.py", line 124, in process_documents
    documents = load_documents(source_directory, ignored_files)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/witu/Downloads/privateGPT/ingest.py", line 113, in load_documents
    for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
AttributeError: module 'fitz' has no attribute 'open'
```

**Comment by dwwnz** [comment]
> I uninstall and install pymupdf, but then hit another issue
> 
> ```
>                               | 0/1 [00:02<?, ?it/s]
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>                     ^^^^^^^^^^^^^^^^^^^
>   File "/Users/witu/Downloads/privateGPT/ingest.py", line 92, in load_single_document
>     return loader.load()
>            ^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/pdf.py", line 311, in load
>     return parser.parse(blob)
>            ^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/base.py", line 95, in parse
>     return list(self.lazy_parse(blob))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/parsers/pdf.py", line 60, in lazy_parse
>     doc = fitz.open(file_path)  # open document
>           ^^^^^^^^^
> AttributeError: module 'fitz' has no attribute 'open'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/witu/Downloads/privateGPT/ingest.py", line 185, in <module>
>     main()
>   File "/Users/witu/Downloads/privateGPT/ingest.py", line 164, in main
>     documents = process_documents([metadata['source'] for metadata in collection['metadatas']])
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/witu/Downloads/privateGPT/ingest.py", line 124, in process_documents
>     documents = load_documents(source_directory, ignored_files)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/witu/Downloads/privateGPT/ingest.py", line 113, in load_documents
>     for i, docs in enumerate(pool.imap_unordered(load_single_document, filtered_files)):
>   File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 873, in next
>     raise value
> AttributeError: module 'fitz' has no attribute 'open'
> ```

I have the same issue after uninstalling and reinstalling pymupdf

**Comment by groovybits** [comment]
I am hitting this too. Is there any solution?
