### ISSUE TITLE
privateGPT seems to want to use GPU instead CPU

### ISSUE THREAD

**Issue by pihomeserver** [imartinez/privateGPT#977]
Following instrcutions i have privateGPT installed on a VPS with no GPU
Trying to start the doc command to ingest the default document fails : 

```
(privategpt-py3.11) chris@host:~/chat/privateGPT$ python ingest.py
Traceback (most recent call last):
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/chat/privateGPT/ingest.py", line 169, in <module>
    main()
  File "/home/chris/chat/privateGPT/ingest.py", line 146, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 51, in __init__
    import sentence_transformers
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 189, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/chris/chat/privateGPT', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/home/chris/.cache/pypoetry/virtualenvs/privategpt-SzYMEnM_-py3.11/lib/python3.11/site-packages']
```

Seems that Nvidia CURAnd lib is required but i was expecting to bypass that by default with a CPU only version

Am i wrong ? Do i must have a GPU to test privateGPT ?

**Comment by pihomeserver** [comment]
I've solved the situation by adding the following to `pyproject.toml` in the tool.poetry.dependencies section
```
torch = ">=2.0.0, !=2.0.1"
```

**Comment by ChanJoon** [comment]
This not worked for me. Python 3.11 with only CPU / Ubuntu 20.04

**Comment by wstealth3** [comment]
I solve this problem ! Thank you very much!
